SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




        
CREATE  View [dbo].[vwIPRNewCustDS]              
as                 
 select               
  case when dm.customerid like '0%'               
    then substring(dm.customerid,2,LEN(dm.customerid))               
    else dm.customerid               
    end AS CustomerID,              
  CustomerSinceDate,              
  IntlPurchaseDate,              
  coalesce(IntlPurchaseOrderID,'0') as IntlPurchaseOrderID ,              
  Coalesce(case when A1.adcode is null then 3523 else IntlPurchaseAdCode end ,0) as IntlPurchaseAdCode,              
  A1.IPR_Channel, 
  A1.MD_Channel,
  A1.MD_PromotionType,
  A1.MD_PriceType,
  IntlPurchAmount,              
  coalesce(replace(case when IntlSubjectPref in ('H','HS','HM') then 'X' else IntlSubjectPref end,'FW','BL'),'X') as IntlSubjectPref,              
  coalesce(IntlFormatMediaPref,'X') as IntlFormatMediaPref,              
  coalesce(IntlFormatAVPref,'X') as IntlFormatAVPref,              
  coalesce(FlagFormatAVPrefTied,0) as FlagFormatAVPrefTied,              
  coalesce(IntlFormatADPref,'X') as IntlFormatADPref ,              
  coalesce(IntlOrderSource,'X') as IntlOrderSource,             
  cast(coalesce(DM.IntlAvgOrderBin,'XX') as char(2))as IntlAvgOrderBin,              
  IntlParts,              
  coalesce(IntlPartsBin,'00-00     ') as IntlPartsBin,              
  IntlNumOfCOurses,              
  DM.IntlCoursesBin,              
  coalesce(SPFlag,0)SPFlag,              
  DSDays,              
  SPFlag3Mth,              
  SPFlag6Mth,              
  SPFlag12Mth,              
  DM.CountryCode,              
  CASE WHEN IntlPurchAmount > 0 and IntlPurchAmount <= 50 then 'B1'           
    WHEN IntlPurchAmount > 50 and IntlPurchAmount <= 75 then 'B2'           
    WHEN IntlPurchAmount > 75 and IntlPurchAmount <= 100 then 'B3'           
    WHEN IntlPurchAmount > 100 and IntlPurchAmount <= 150 then 'B4'           
    WHEN IntlPurchAmount > 150 then 'B5'           
    else 'XX'         
 end as  IntlAvgOrderBin_2,
 		DS1moSales,
		DS2moSales,
		DS3moSales,
		DS4moSales,
		DS5moSales,
		DS6moSales,
		DS7moSales,
		DS8moSales,
		DS9moSales,
		DS10moSales,
		DS11moSales,
		DS12moSales,
		DS24moSales,
		DS36moSales,
		DS48moSales,
		DS60moSales,
		DS72moSales,
		DS84moSales,
		DS96moSales,
		DS108moSales,
		DS120moSales,
		DS132moSales,
		DS144moSales,
		DS156moSales,
		DS168moSales,
		DS180moSales,
		DS1moOrders,
		DS2moOrders,
		DS3moOrders,
		DS4moOrders,
		DS5moOrders,
		DS6moOrders,
		DS7moOrders,
		DS8moOrders,
		DS9moOrders,
		DS10moOrders,
		DS11moOrders,
		DS12moOrders,
		DS24moOrders,
		DS36moOrders,
		DS48moOrders,
		DS60moOrders,
		DS72moOrders,
		DS84moOrders,
		DS96moOrders,
		DS108moOrders,
		DS120moOrders,
		DS132moOrders,
		DS144moOrders,
		DS156moOrders,
		DS168moOrders,
		DS180moOrders,
		DS1moFlagRepeatByr,
		DS2moFlagRepeatByr,
		DS3moFlagRepeatByr,
		DS4moFlagRepeatByr,
		DS5moFlagRepeatByr,
		DS6moFlagRepeatByr,
		DS7moFlagRepeatByr,
		DS8moFlagRepeatByr,
		DS9moFlagRepeatByr,
		DS10moFlagRepeatByr,
		DS11moFlagRepeatByr,
		DS12moFlagRepeatByr,
		DS24moFlagRepeatByr,
		DS36moFlagRepeatByr,
		DS48moFlagRepeatByr,
		DS60moFlagRepeatByr,
		DS72moFlagRepeatByr,
		DS84moFlagRepeatByr,
		DS96moFlagRepeatByr,
		DS108moFlagRepeatByr,
		DS120moFlagRepeatByr,
		DS132moFlagRepeatByr,
		DS144moFlagRepeatByr,
		DS156moFlagRepeatByr,
		DS168moFlagRepeatByr,
		DS180moFlagRepeatByr,
		DS1moOrderUnits,
		DS2moOrderUnits,
		DS3moOrderUnits,
		DS4moOrderUnits,
		DS5moOrderUnits,
		DS6moOrderUnits,
		DS7moOrderUnits,
		DS8moOrderUnits,
		DS9moOrderUnits,
		DS10moOrderUnits,
		DS11moOrderUnits,
		DS12moOrderUnits
		DS24moOrderUnits,
		DS36moOrderUnits,
		DS48moOrderUnits,
		DS60moOrderUnits,
		DS72moOrderUnits,
		DS84moOrderUnits,
		DS96moOrderUnits,
		DS108moOrderUnits,
		DS120moOrderUnits,
		DS132moOrderUnits
		DS144moOrderUnits,
		DS156moOrderUnits,
		DS168moOrderUnits,
		DS180moOrderUnits,
		DS1moEmailContacts,
		DS2moEmailContacts,
		DS3moEmailContacts,
		DS6moEmailContacts,
		DS12moEmailContacts,
		DS18moEmailContacts,
		DS24moEmailContacts,
		DS1momailContacts,
		DS2momailContacts,
		DS3momailContacts,
		DS6momailContacts,
		DS12momailContacts,
		DS18momailContacts,
		DS24momailContacts,
		DS1moParts,
		DS2moParts,
		DS3moParts,
		DS4moParts,
		DS5moParts,
		DS6moParts,
		DS7moParts,
		DS8moParts,
		DS9moParts,
		DS10moParts,
		DS11moParts,
		DS12moParts,
		DS24moParts,
		DS36moParts,
		DS48moParts,
		DS60moParts,
		DS72moParts,
		DS84moParts,
		DS96moParts,
		DS108moParts,
		DS120moParts,
		DS132moParts,
		DS144moParts,
		DS156moParts,
		DS168moParts,
		DS180moParts              
 from DataWarehouse.Marketing.DMCustomerStaticNew DM  
 left join 	datawarehouse.Marketing.DMDownStreamMonthlyNew DS
 on DM.customerid=DS.customerid
 left join DAXImports..CustomerExport Cust 
 on DM.CustomerID = Cust.Customerid 
 left join DataWarehouse.Mapping.vwAdcodesAll A1(nolock)
 on A1.AdCode = Dm.IntlPurchaseAdCode
 left join DataWarehouse.Mapping.vwAdcodesAll A2(nolock)
 on A2.AdCode = Dm.SPAdcode
 where cust.JSMERGEDROOT = ''  



GO
