SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
Create Proc [staging].[SP_TTCProd_to_DaxImportsStage_TTC_AUDITCUSTOPTINCHANGES]
as

/* This routine is used to export TTC_AUDITCUSTOPTINCHANGES. 
Date Written: 2017-01-10 BondugulaV
Last Updated: 2017-01-10 BondugulaV Initial

*/


Begin

truncate table [staging].[TTC_AUDITCUSTOPTINCHANGES]


Insert into [staging].[TTC_AUDITCUSTOPTINCHANGES] 
select ACTIONREQUESTED,OPTINID,CUSTACCOUNT,MODIFIEDDATETIME,MODIFIEDBY,CREATEDDATETIME,CREATEDBY,DATAAREAID,RECVERSION,RECID 
from TTCPROD2009..[TTC_AUDITCUSTOPTINCHANGES]

End



GO
