IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TEACHCO\PRITCHETTC')
CREATE LOGIN [TEACHCO\PRITCHETTC] FROM WINDOWS
GO
CREATE USER [TEACHCO\PRITCHETTC] FOR LOGIN [TEACHCO\PRITCHETTC]
GO
