IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TEACHCO\CAROTHERSW')
CREATE LOGIN [TEACHCO\CAROTHERSW] FROM WINDOWS
GO
CREATE USER [TEACHCO\CAROTHERSW] FOR LOGIN [TEACHCO\CAROTHERSW]
GO
