CREATE TABLE [Archive].[Mail_US_MayJFY_20160520]
(
[Customerid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mf] [int] NULL,
[ComboID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Concatenated] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FMPullDate] [datetime] NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailAddress] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagEmail] [int] NULL,
[FlagValidEmail] [tinyint] NULL,
[StartDate] [date] NULL,
[FlagEmailPref] [int] NULL,
[FlagValidRegionUS] [bit] NULL,
[FlagInternational] [bit] NULL,
[FlagMail] [int] NULL,
[CustomerSince] [datetime] NULL,
[PublicLibrary] [int] NULL,
[CG_Gender] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTDPurchasesBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRComboID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumHits] [int] NULL,
[AH] [int] NULL,
[EC] [int] NULL,
[FA] [int] NULL,
[HS] [int] NULL,
[LIT] [int] NULL,
[MH] [int] NULL,
[PH] [int] NULL,
[RL] [int] NULL,
[SC] [int] NULL,
[PreferredCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagReceivedJFYBefore] [int] NOT NULL,
[JFYAdcode] [int] NOT NULL,
[JFYAdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagJFYHoldout] [int] NOT NULL,
[JFYHoldoutAdcode] [int] NOT NULL,
[JFYHoldoutAdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Audio] [tinyint] NULL,
[Video] [tinyint] NULL,
[CD] [tinyint] NULL,
[DVD] [tinyint] NULL,
[DownLoads] [tinyint] NULL,
[HSFormat] [tinyint] NULL,
[VideoDownloads] [int] NOT NULL,
[CustGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagCDOnly] [int] NOT NULL,
[FlagDVDOnly] [int] NOT NULL,
[FlagMultiformat] [int] NOT NULL,
[FlagMFCDPref] [int] NOT NULL,
[FlagMFDVDPref] [int] NOT NULL,
[FormatPref] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Version] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adcode] [int] NULL,
[AdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode] [int] NOT NULL,
[CatalogName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagWebLTM18] [int] NOT NULL,
[FlagPhone] [int] NOT NULL,
[FlagHSOnly] [int] NOT NULL,
[FormatType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URLExtension] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagWebPurchBfr] [tinyint] NULL,
[OfferType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExpirationDate] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailDate] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSLPurchase] [int] NULL,
[Recency] [int] NULL,
[IntlAOS] [money] NULL,
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlFormat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlPromotionTypeID] [smallint] NULL,
[CustomerSegmentNew] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TenureDays] [int] NULL,
[LTDPurchases] [int] NULL,
[R3FormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTB] [float] NULL,
[R3OrderSourcePref] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecencyBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTDAvgAOS_Bin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eWGroup] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTD_LVHV_Flag] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonEngagedFlag] [int] NULL,
[FlagEmailOrder] [int] NULL,
[DRTV] [int] NULL,
[PriorPurchaseOrderID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorPurchaseOrderDate] [date] NULL,
[PriorPurchaseOrderAmount] [money] NULL,
[PriorPurchaseOrderSource] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorPurchaseAdcode] [int] NULL,
[CustomerSegmentPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegment2Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnlPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrequencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewsegPrior] [int] NULL,
[NamePrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12mfPrior] [int] NULL,
[PriorSales] [money] NULL,
[PriorOrders] [int] NULL,
[PriorAOS] [money] NULL,
[ConcatenatedPrior] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonetaryValuePrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prior12MonthOrders] [int] NULL,
[Prior6MonthOrders] [int] NULL,
[Decile] [int] NULL,
[DemiDecile] [int] NULL,
[ActiveMultiSelect] [int] NULL
) ON [PRIMARY]
GO
