CREATE TABLE [Archive].[DMMPINPUT_BKP20130212]
(
[GENDER_09] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DWELLTYPE_09] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMERID] [int] NOT NULL,
[NUMHITS_09] [int] NULL,
[NUMHITSCategory_09] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABCScore_09] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated_09] [smalldatetime] NULL,
[NUMHITS_08] [int] NULL,
[NUMHITSCategory_08] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABCScore_08] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated_08] [smalldatetime] NULL,
[NUMHITS_07] [int] NULL,
[NUMHITSCategory_07] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABCscore_07] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated_07] [smalldatetime] NULL,
[NUMHITS_06] [int] NULL,
[NUMHITSCATEGORY_06] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATED_06] [smalldatetime] NULL,
[NUMHITS_05] [int] NULL,
[NUMHITSCATEGORY_05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATED_05] [smalldatetime] NULL,
[ALUMNIHITS_05] [int] NULL,
[ALUMNIHITSCATEGORY_05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMHITS_04] [int] NULL,
[NUMHITSCATEGORY_04] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATED_04] [smalldatetime] NULL,
[NUMHITS_03] [int] NULL,
[NUMHITSCATEGORY_03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATED_03] [smalldatetime] NULL,
[NUMHITS_Sum_03To05] [int] NULL,
[NUMHITSCATEGORY_Sum_03To05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMHITS_Max_03To05] [int] NULL,
[NUMHITSCATEGORY_Max_03To05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMHITS_Avg_03To05] [float] NULL,
[NUMHITSCATEGORY_Avg_03To05] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENDER_10] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DWELLTYPE_10] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMHITS_10] [int] NULL,
[NUMHITSCategory_10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABCScore_10] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated_10] [smalldatetime] NULL,
[Gender] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwellType] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Numhits] [int] NULL,
[NUMHITSCategory] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABCScore] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateCreated] [smalldatetime] NULL
) ON [PRIMARY]
GO
