CREATE TABLE [Archive].[CTMonitor_CallSummary]
(
[CallSummaryId] [int] NOT NULL,
[SwitchId] [int] NOT NULL,
[CallDirectionId] [tinyint] NOT NULL,
[AlertingDateTime] [datetime] NULL,
[CallStartDateTime] [datetime] NOT NULL,
[CallQueuedDateTime] [datetime] NULL,
[CallAnswerDateTime] [datetime] NULL,
[CallEndDateTime] [datetime] NULL,
[AlertingNumber] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallFromNumber] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallToNumber] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrunkGroupDeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrunkGroupMemberId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SplitDeviceId] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredCodeData] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredCodeVDN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistributingDevice] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistributingVDN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserData] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UCID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NewUCID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OldUCID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Abandon] [bit] NULL,
[CallId] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryCallId] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryCallId] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agent1DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Station1DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agent2DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Station2DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call2Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agent3DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Station3DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call3Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agent4DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Station4DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call4Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agent5DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Station5DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call5Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agent6DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Station6DeviceId] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call6Type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMLastupdated] [datetime] NULL CONSTRAINT [DF__CTMonitor__DMLas__4DBEA09E] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [Archive].[CTMonitor_CallSummary] ADD CONSTRAINT [PK_CTMonitor_CallSummary] PRIMARY KEY CLUSTERED  ([CallSummaryId]) ON [PRIMARY]
GO
