CREATE TABLE [Archive].[EmailCaptureReportByEmailSignUp]
(
[Email1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_date] [datetime] NULL,
[registration_source_id] [int] NULL,
[RegistrationSource] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[snooze_start_date] [datetime] NULL,
[snooze_end_date] [datetime] NULL,
[Snoozed] [int] NULL,
[NewCourseAnnouncements] [int] NULL,
[FreeLecturesClipsandInterviews] [int] NULL,
[ExclusiveOffers] [int] NULL,
[Frequency] [int] NULL,
[Subscribed] [int] NULL,
[HardBounce] [int] NULL,
[Blacklist] [int] NULL,
[SoftBounce] [int] NULL,
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MagentoDaxMapped_Flag] [int] NULL,
[ChildCustomerid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_Flag] [int] NULL,
[Reinstated] [bit] NULL,
[Lastupdated] [datetime] NULL,
[CustomerSince] [datetime] NULL,
[CustType] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[JSCOUPONNUMBER] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyCode] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coupon] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponDesc] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orders] [int] NOT NULL,
[Sales] [money] NOT NULL,
[DMlastupdated] [datetime] NOT NULL
) ON [PRIMARY]
GO
