CREATE TABLE [Archive].[BV_Ratings_ReviewTxt]
(
[ReviewID] [int] NOT NULL,
[SubmissionDate] [date] NULL,
[InitialPublishDate] [date] NULL,
[ModerationStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductID] [int] NULL,
[CategoryHierarchy] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MeritRank] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRatingsOnlyReview] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewTitle] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserNickname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserLocation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverallRating] [int] NULL,
[CourseContent] [int] NULL,
[ProfessorPresentation] [int] NULL,
[CourseValue] [int] NULL,
[RecommendToFriend] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewText] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumofCmmnts] [int] NULL,
[NumofCmmntsApproved] [int] NULL,
[NumofCmmntsRejected] [int] NULL,
[NumofCmmntsInModeration] [int] NULL,
[NumofCmmntsWithPhoto] [int] NULL,
[NumofCmmntsWithVideo] [int] NULL,
[NumofHelpfulVotes] [int] NULL,
[NumofNotHelpfulVotes] [int] NULL,
[NumofInappropriateVotes] [int] NULL,
[FormatType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorSubjectKnowledge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VerifiedPurchaser] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CmmntID] [int] NULL,
[CmmntText] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CmmntModerationStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CmmntSubmissionDate] [date] NULL,
[CmmntInitialPublishDate] [date] NULL,
[CmmnterId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CmmnterNickname] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CmmnterLocation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CmmnterMeritRank] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsertedDate] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
