CREATE TABLE [Archive].[tgcplus_churnmodeldata]
(
[CustomerID] [bigint] NULL,
[Domain] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSMonthCancelled_new] [int] NULL,
[country] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidType] [varchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TGCCustomerType] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TGCCustSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[HouseHoldIncomeBin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EducationBin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlCampaignName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlMD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlMD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSubDate] [date] NULL,
[IntlSubPaymentHandler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlPaidDate] [date] NULL,
[IntlPaidAmt] [float] NOT NULL,
[LastPaidDate] [date] NULL,
[LTDPaidAmt] [float] NOT NULL,
[LastPaidAmt] [float] NOT NULL,
[DSDayCancelled] [int] NULL,
[registered_via_platform] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstDeviceCategory] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrowserSignUp] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstStreamDate] [date] NULL,
[Days_Join_Stream] [int] NULL,
[FirstPlatform] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstBrowser] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstCourse] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstLecture] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstLectureNumber] [int] NULL,
[FirstGenre] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstFilmType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseholdIncome_Median] [float] NULL,
[ZipPopulation] [float] NULL,
[Categories_7days] [int] NOT NULL,
[Courses_7days] [int] NOT NULL,
[Lectures_7days] [int] NOT NULL,
[StreamedMins_7days] [numeric] (38, 1) NOT NULL,
[Categories_14days] [int] NOT NULL,
[Courses_14days] [int] NOT NULL,
[Lectures_14days] [int] NOT NULL,
[StreamedMins_14days] [numeric] (38, 1) NOT NULL,
[Categories_30days] [int] NOT NULL,
[Courses_30days] [int] NOT NULL,
[Lectures_30days] [int] NOT NULL,
[StreamedMins_30days] [numeric] (38, 1) NOT NULL,
[CardBrand] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardFunding] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day1Consumption] [numeric] (38, 1) NOT NULL,
[Day2Consumption] [numeric] (38, 1) NOT NULL,
[Day3Consumption] [numeric] (38, 1) NOT NULL,
[Day4Consumption] [numeric] (38, 1) NOT NULL,
[Day5Consumption] [numeric] (38, 1) NOT NULL,
[Day6Consumption] [numeric] (38, 1) NOT NULL,
[Day7Consumption] [numeric] (38, 1) NOT NULL,
[Day8Consumption] [numeric] (38, 1) NOT NULL,
[Day9Consumption] [numeric] (38, 1) NOT NULL,
[Day10Consumption] [numeric] (38, 1) NOT NULL,
[Day11Consumption] [numeric] (38, 1) NOT NULL,
[Day12Consumption] [numeric] (38, 1) NOT NULL,
[Day13Consumption] [numeric] (38, 1) NOT NULL,
[Day14Consumption] [numeric] (38, 1) NOT NULL,
[Day15Consumption] [numeric] (38, 1) NOT NULL,
[Day16Consumption] [numeric] (38, 1) NOT NULL,
[Day17Consumption] [numeric] (38, 1) NOT NULL,
[Day18Consumption] [numeric] (38, 1) NOT NULL,
[Day19Consumption] [numeric] (38, 1) NOT NULL,
[Day20Consumption] [numeric] (38, 1) NOT NULL,
[Day21Consumption] [numeric] (38, 1) NOT NULL,
[Day22Consumption] [numeric] (38, 1) NOT NULL,
[Day23Consumption] [numeric] (38, 1) NOT NULL,
[Day24Consumption] [numeric] (38, 1) NOT NULL,
[Day25Consumption] [numeric] (38, 1) NOT NULL,
[Day26Consumption] [numeric] (38, 1) NOT NULL,
[Day27Consumption] [numeric] (38, 1) NOT NULL,
[Day28Consumption] [numeric] (38, 1) NOT NULL,
[Day29Consumption] [numeric] (38, 1) NOT NULL,
[Day30Consumption] [numeric] (38, 1) NOT NULL,
[Day1Genres] [int] NOT NULL,
[Day2Genres] [int] NOT NULL,
[Day3Genres] [int] NOT NULL,
[Day4Genres] [int] NOT NULL,
[Day5Genres] [int] NOT NULL,
[Day6Genres] [int] NOT NULL,
[Day7Genres] [int] NOT NULL,
[Day8Genres] [int] NOT NULL,
[Day9Genres] [int] NOT NULL,
[Day10Genres] [int] NOT NULL,
[Day11Genres] [int] NOT NULL,
[Day12Genres] [int] NOT NULL,
[Day13Genres] [int] NOT NULL,
[Day14Genres] [int] NOT NULL,
[Day15Genres] [int] NOT NULL,
[Day16Genres] [int] NOT NULL,
[Day17Genres] [int] NOT NULL,
[Day18Genres] [int] NOT NULL,
[Day19Genres] [int] NOT NULL,
[Day20Genres] [int] NOT NULL,
[Day21Genres] [int] NOT NULL,
[Day22Genres] [int] NOT NULL,
[Day23Genres] [int] NOT NULL,
[Day24Genres] [int] NOT NULL,
[Day25Genres] [int] NOT NULL,
[Day26Genres] [int] NOT NULL,
[Day27Genres] [int] NOT NULL,
[Day28Genres] [int] NOT NULL,
[Day29Genres] [int] NOT NULL,
[Day30Genres] [int] NOT NULL,
[Day1Lectures] [int] NOT NULL,
[Day2Lectures] [int] NOT NULL,
[Day3Lectures] [int] NOT NULL,
[Day4Lectures] [int] NOT NULL,
[Day5Lectures] [int] NOT NULL,
[Day6Lectures] [int] NOT NULL,
[Day7Lectures] [int] NOT NULL,
[Day8Lectures] [int] NOT NULL,
[Day9Lectures] [int] NOT NULL,
[Day10Lectures] [int] NOT NULL,
[Day11Lectures] [int] NOT NULL,
[Day12Lectures] [int] NOT NULL,
[Day13Lectures] [int] NOT NULL,
[Day14Lectures] [int] NOT NULL,
[Day15Lectures] [int] NOT NULL,
[Day16Lectures] [int] NOT NULL,
[Day17Lectures] [int] NOT NULL,
[Day18Lectures] [int] NOT NULL,
[Day19Lectures] [int] NOT NULL,
[Day20Lectures] [int] NOT NULL,
[Day21Lectures] [int] NOT NULL,
[Day22Lectures] [int] NOT NULL,
[Day23Lectures] [int] NOT NULL,
[Day24Lectures] [int] NOT NULL,
[Day25Lectures] [int] NOT NULL,
[Day26Lectures] [int] NOT NULL,
[Day27Lectures] [int] NOT NULL,
[Day28Lectures] [int] NOT NULL,
[Day29Lectures] [int] NOT NULL,
[Day30Lectures] [int] NOT NULL,
[AdobePageActivity_AccountPageVisits] [bigint] NOT NULL,
[AdobePageActivity_FAQVisits] [bigint] NOT NULL,
[AdobePageActivity_SocialPageVisits] [bigint] NOT NULL,
[AdobePageActivity_RegistrationPageVisits] [bigint] NOT NULL,
[AdobePageActivity_CancelPageVisits] [bigint] NOT NULL,
[Day1_FR] [numeric] (38, 6) NOT NULL,
[Day2_FR] [numeric] (38, 6) NOT NULL,
[Day3_FR] [numeric] (38, 6) NOT NULL,
[Day4_FR] [numeric] (38, 6) NOT NULL,
[Day5_FR] [numeric] (38, 6) NOT NULL,
[Day6_FR] [numeric] (38, 6) NOT NULL,
[Day7_FR] [numeric] (38, 6) NOT NULL,
[Day8_FR] [numeric] (38, 6) NOT NULL,
[Day9_FR] [numeric] (38, 6) NOT NULL,
[Day10_FR] [numeric] (38, 6) NOT NULL,
[Day11_FR] [numeric] (38, 6) NOT NULL,
[Day12_FR] [numeric] (38, 6) NOT NULL,
[Day13_FR] [numeric] (38, 6) NOT NULL,
[Day14_FR] [numeric] (38, 6) NOT NULL,
[Day15_FR] [numeric] (38, 6) NOT NULL,
[Day16_FR] [numeric] (38, 6) NOT NULL,
[Day17_FR] [numeric] (38, 6) NOT NULL,
[Day18_FR] [numeric] (38, 6) NOT NULL,
[Day19_FR] [numeric] (38, 6) NOT NULL,
[Day20_FR] [numeric] (38, 6) NOT NULL,
[Day21_FR] [numeric] (38, 6) NOT NULL,
[Day22_FR] [numeric] (38, 6) NOT NULL,
[Day23_FR] [numeric] (38, 6) NOT NULL,
[Day24_FR] [numeric] (38, 6) NOT NULL,
[Day25_FR] [numeric] (38, 6) NOT NULL,
[Day26_FR] [numeric] (38, 6) NOT NULL,
[Day27_FR] [numeric] (38, 6) NOT NULL,
[Day28_FR] [numeric] (38, 6) NOT NULL,
[Day29_FR] [numeric] (38, 6) NOT NULL,
[Day30_FR] [numeric] (38, 6) NOT NULL,
[Day1_FinishedLectures] [int] NOT NULL,
[Day2_FinishedLectures] [int] NOT NULL,
[Day3_FinishedLectures] [int] NOT NULL,
[Day4_FinishedLectures] [int] NOT NULL,
[Day5_FinishedLectures] [int] NOT NULL,
[Day6_FinishedLectures] [int] NOT NULL,
[Day7_FinishedLectures] [int] NOT NULL,
[Day8_FinishedLectures] [int] NOT NULL,
[Day9_FinishedLectures] [int] NOT NULL,
[Day10_FinishedLectures] [int] NOT NULL,
[Day11_FinishedLectures] [int] NOT NULL,
[Day12_FinishedLectures] [int] NOT NULL,
[Day13_FinishedLectures] [int] NOT NULL,
[Day14_FinishedLectures] [int] NOT NULL,
[Day15_FinishedLectures] [int] NOT NULL,
[Day16_FinishedLectures] [int] NOT NULL,
[Day17_FinishedLectures] [int] NOT NULL,
[Day18_FinishedLectures] [int] NOT NULL,
[Day19_FinishedLectures] [int] NOT NULL,
[Day20_FinishedLectures] [int] NOT NULL,
[Day21_FinishedLectures] [int] NOT NULL,
[Day22_FinishedLectures] [int] NOT NULL,
[Day23_FinishedLectures] [int] NOT NULL,
[Day24_FinishedLectures] [int] NOT NULL,
[Day25_FinishedLectures] [int] NOT NULL,
[Day26_FinishedLectures] [int] NOT NULL,
[Day27_FinishedLectures] [int] NOT NULL,
[Day28_FinishedLectures] [int] NOT NULL,
[Day29_FinishedLectures] [int] NOT NULL,
[Day30_FinishedLectures] [int] NOT NULL,
[BehindtheScenes_FR] [numeric] (38, 6) NULL,
[BonusFeatures_FR] [numeric] (38, 6) NULL,
[Economics_FR] [numeric] (38, 6) NULL,
[FoodWine_FR] [numeric] (38, 6) NULL,
[Health_FR] [numeric] (38, 6) NULL,
[History_FR] [numeric] (38, 6) NULL,
[Hobby_FR] [numeric] (38, 6) NULL,
[Literature_FR] [numeric] (38, 6) NULL,
[Mathematics_FR] [numeric] (38, 6) NULL,
[Music_FR] [numeric] (38, 6) NULL,
[NatGeo_FR] [numeric] (38, 6) NULL,
[Phil_FR] [numeric] (38, 6) NULL,
[Professional_FR] [numeric] (38, 6) NULL,
[Science_FR] [numeric] (38, 6) NULL,
[Trailers_FR] [numeric] (38, 6) NULL,
[Travel_FR] [numeric] (38, 6) NULL,
[LastStreamedDate_FreeTrialMonth] [date] NULL,
[Day1_OpenRate] [numeric] (38, 11) NULL,
[Day2_OpenRate] [numeric] (38, 11) NULL,
[Day3_OpenRate] [numeric] (38, 11) NULL,
[Day4_OpenRate] [numeric] (38, 11) NULL,
[Day5_OpenRate] [numeric] (38, 11) NULL,
[Day6_OpenRate] [numeric] (38, 11) NULL,
[Day7_OpenRate] [numeric] (38, 11) NULL,
[Day8_OpenRate] [numeric] (38, 11) NULL,
[Day9_OpenRate] [numeric] (38, 11) NULL,
[Day10_OpenRate] [numeric] (38, 11) NULL,
[Day11_OpenRate] [numeric] (38, 11) NULL,
[Day12_OpenRate] [numeric] (38, 11) NULL,
[Day13_OpenRate] [numeric] (38, 11) NULL,
[Day14_OpenRate] [numeric] (38, 11) NULL,
[Day15_OpenRate] [numeric] (38, 11) NULL,
[Day16_OpenRate] [numeric] (38, 11) NULL,
[Day17_OpenRate] [numeric] (38, 11) NULL,
[Day18_OpenRate] [numeric] (38, 11) NULL,
[Day19_OpenRate] [numeric] (38, 11) NULL,
[Day20_OpenRate] [numeric] (38, 11) NULL,
[Day21_OpenRate] [numeric] (38, 11) NULL,
[Day22_OpenRate] [numeric] (38, 11) NULL,
[Day23_OpenRate] [numeric] (38, 11) NULL,
[Day24_OpenRate] [numeric] (38, 11) NULL,
[Day25_OpenRate] [numeric] (38, 11) NULL,
[Day26_OpenRate] [numeric] (38, 11) NULL,
[Day27_OpenRate] [numeric] (38, 11) NULL,
[Day28_OpenRate] [numeric] (38, 11) NULL,
[Day29_OpenRate] [numeric] (38, 11) NULL,
[Day30_OpenRate] [numeric] (38, 11) NULL,
[Day1_ClickRate] [numeric] (38, 11) NULL,
[Day2_ClickRate] [numeric] (38, 11) NULL,
[Day3_ClickRate] [numeric] (38, 11) NULL,
[Day4_ClickRate] [numeric] (38, 11) NULL,
[Day5_ClickRate] [numeric] (38, 11) NULL,
[Day6_ClickRate] [numeric] (38, 11) NULL,
[Day7_ClickRate] [numeric] (38, 11) NULL,
[Day8_ClickRate] [numeric] (38, 11) NULL,
[Day9_ClickRate] [numeric] (38, 11) NULL,
[Day10_ClickRate] [numeric] (38, 11) NULL,
[Day11_ClickRate] [numeric] (38, 11) NULL,
[Day12_ClickRate] [numeric] (38, 11) NULL,
[Day13_ClickRate] [numeric] (38, 11) NULL,
[Day14_ClickRate] [numeric] (38, 11) NULL,
[Day15_ClickRate] [numeric] (38, 11) NULL,
[Day16_ClickRate] [numeric] (38, 11) NULL,
[Day17_ClickRate] [numeric] (38, 11) NULL,
[Day18_ClickRate] [numeric] (38, 11) NULL,
[Day19_ClickRate] [numeric] (38, 11) NULL,
[Day20_ClickRate] [numeric] (38, 11) NULL,
[Day21_ClickRate] [numeric] (38, 11) NULL,
[Day22_ClickRate] [numeric] (38, 11) NULL,
[Day23_ClickRate] [numeric] (38, 11) NULL,
[Day24_ClickRate] [numeric] (38, 11) NULL,
[Day25_ClickRate] [numeric] (38, 11) NULL,
[Day26_ClickRate] [numeric] (38, 11) NULL,
[Day27_ClickRate] [numeric] (38, 11) NULL,
[Day28_ClickRate] [numeric] (38, 11) NULL,
[Day29_ClickRate] [numeric] (38, 11) NULL,
[Day30_ClickRate] [numeric] (38, 11) NULL,
[Day1_Sends] [int] NULL,
[Day2_Sends] [int] NULL,
[Day3_Sends] [int] NULL,
[Day4_Sends] [int] NULL,
[Day5_Sends] [int] NULL,
[Day6_Sends] [int] NULL,
[Day7_Sends] [int] NULL,
[Day8_Sends] [int] NULL,
[Day9_Sends] [int] NULL,
[Day10_Sends] [int] NULL,
[Day11_Sends] [int] NULL,
[Day12_Sends] [int] NULL,
[Day13_Sends] [int] NULL,
[Day14_Sends] [int] NULL,
[Day15_Sends] [int] NULL,
[Day16_Sends] [int] NULL,
[Day17_Sends] [int] NULL,
[Day18_Sends] [int] NULL,
[Day19_Sends] [int] NULL,
[Day20_Sends] [int] NULL,
[Day21_Sends] [int] NULL,
[Day22_Sends] [int] NULL,
[Day23_Sends] [int] NULL,
[Day24_Sends] [int] NULL,
[Day25_Sends] [int] NULL,
[Day26_Sends] [int] NULL,
[Day27_Sends] [int] NULL,
[Day28_Sends] [int] NULL,
[Day29_Sends] [int] NULL,
[Day30_Sends] [int] NULL,
[Day1_Opens] [int] NULL,
[Day2_Opens] [int] NULL,
[Day3_Opens] [int] NULL,
[Day4_Opens] [int] NULL,
[Day5_Opens] [int] NULL,
[Day6_Opens] [int] NULL,
[Day7_Opens] [int] NULL,
[Day8_Opens] [int] NULL,
[Day9_Opens] [int] NULL,
[Day10_Opens] [int] NULL,
[Day11_Opens] [int] NULL,
[Day12_Opens] [int] NULL,
[Day13_Opens] [int] NULL,
[Day14_Opens] [int] NULL,
[Day15_Opens] [int] NULL,
[Day16_Opens] [int] NULL,
[Day17_Opens] [int] NULL,
[Day18_Opens] [int] NULL,
[Day19_Opens] [int] NULL,
[Day20_Opens] [int] NULL,
[Day21_Opens] [int] NULL,
[Day22_Opens] [int] NULL,
[Day23_Opens] [int] NULL,
[Day24_Opens] [int] NULL,
[Day25_Opens] [int] NULL,
[Day26_Opens] [int] NULL,
[Day27_Opens] [int] NULL,
[Day28_Opens] [int] NULL,
[Day29_Opens] [int] NULL,
[Day30_Opens] [int] NULL,
[Day1_RawOpens] [int] NULL,
[Day2_RawOpens] [int] NULL,
[Day3_RawOpens] [int] NULL,
[Day4_RawOpens] [int] NULL,
[Day5_RawOpens] [int] NULL,
[Day6_RawOpens] [int] NULL,
[Day7_RawOpens] [int] NULL,
[Day8_RawOpens] [int] NULL,
[Day9_RawOpens] [int] NULL,
[Day10_RawOpens] [int] NULL,
[Day11_RawOpens] [int] NULL,
[Day12_RawOpens] [int] NULL,
[Day13_RawOpens] [int] NULL,
[Day14_RawOpens] [int] NULL,
[Day15_RawOpens] [int] NULL,
[Day16_RawOpens] [int] NULL,
[Day17_RawOpens] [int] NULL,
[Day18_RawOpens] [int] NULL,
[Day19_RawOpens] [int] NULL,
[Day20_RawOpens] [int] NULL,
[Day21_RawOpens] [int] NULL,
[Day22_RawOpens] [int] NULL,
[Day23_RawOpens] [int] NULL,
[Day24_RawOpens] [int] NULL,
[Day25_RawOpens] [int] NULL,
[Day26_RawOpens] [int] NULL,
[Day27_RawOpens] [int] NULL,
[Day28_RawOpens] [int] NULL,
[Day29_RawOpens] [int] NULL,
[Day30_RawOpens] [int] NULL,
[PrePlusFinalSales] [money] NOT NULL,
[PrePlusOrders] [int] NOT NULL,
[PostPlusFinalSales] [money] NOT NULL,
[PostPlusOrders] [int] NOT NULL,
[Day1_OptOutIndicator] [int] NOT NULL,
[Day2_OptOutIndicator] [int] NOT NULL,
[Day3_OptOutIndicator] [int] NOT NULL,
[Day4_OptOutIndicator] [int] NOT NULL,
[Day5_OptOutIndicator] [int] NOT NULL,
[Day6_OptOutIndicator] [int] NOT NULL,
[Day7_OptOutIndicator] [int] NOT NULL,
[Day8_OptOutIndicator] [int] NOT NULL,
[Day9_OptOutIndicator] [int] NOT NULL,
[Day10_OptOutIndicator] [int] NOT NULL,
[Day11_OptOutIndicator] [int] NOT NULL,
[Day12_OptOutIndicator] [int] NOT NULL,
[Day13_OptOutIndicator] [int] NOT NULL,
[Day14_OptOutIndicator] [int] NOT NULL,
[Day15_OptOutIndicator] [int] NOT NULL,
[Day16_OptOutIndicator] [int] NOT NULL,
[Day17_OptOutIndicator] [int] NOT NULL,
[Day18_OptOutIndicator] [int] NOT NULL,
[Day19_OptOutIndicator] [int] NOT NULL,
[Day20_OptOutIndicator] [int] NOT NULL,
[Day21_OptOutIndicator] [int] NOT NULL,
[Day22_OptOutIndicator] [int] NOT NULL,
[Day23_OptOutIndicator] [int] NOT NULL,
[Day24_OptOutIndicator] [int] NOT NULL,
[Day25_OptOutIndicator] [int] NOT NULL,
[Day26_OptOutIndicator] [int] NOT NULL,
[Day27_OptOutIndicator] [int] NOT NULL,
[Day28_OptOutIndicator] [int] NOT NULL,
[Day29_OptOutIndicator] [int] NOT NULL,
[Day30_OptOutIndicator] [int] NOT NULL,
[Optout_time] [datetime] NULL,
[Freedays] [int] NULL,
[DMLastupdated] [datetime] NOT NULL
) ON [PRIMARY]
GO
