CREATE TABLE [Archive].[SM_TRACKING_LOG]
(
[SM_TRACKING_LOG_ID] [int] NOT NULL IDENTITY(1, 1),
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateStamp] [datetime] NULL,
[TType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [Archive].[SM_TRACKING_LOG] ADD CONSTRAINT [pk_SM_TRACKING_LOG_ID] PRIMARY KEY CLUSTERED  ([SM_TRACKING_LOG_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_SM_TRACKING_LOG_test] ON [Archive].[SM_TRACKING_LOG] ([Email]) INCLUDE ([DateStamp], [TType]) ON [PRIMARY]
GO
