CREATE TABLE [Archive].[TGCPlusRadioMaster_Ujval]
(
[Offer ID] [float] NULL,
[Offer Code Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Offer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Creative (Copy)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGCPlusCampaign] [float] NULL,
[Landing Page Template (High Price)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Landing Page Template (Low Price)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[# Spots] [float] NULL,
[Run Date Spot 1] [datetime] NULL,
[Run Date Spot 2] [datetime] NULL,
[Run Date Spot 3] [datetime] NULL,
[Run Date Spot 4] [datetime] NULL,
[Run Date Spot 5] [datetime] NULL,
[Run Date Spot 6] [datetime] NULL,
[Run Date Spot 7] [datetime] NULL,
[Run Date Spot 8] [datetime] NULL,
[Run Date Spot 9] [datetime] NULL,
[Run Date Spot 10] [datetime] NULL,
[Source Code 1 (Higher Price Test)] [float] NULL,
[Source Code 2 (Lower Price Test)] [float] NULL,
[Source Code 3 (Redirect from TGC#com Higher Price)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Code 4 (Redirect from TGC#com Lower Price)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Code 5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Code 6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Date Spot Run] [datetime] NULL,
[Start Week] [datetime] NULL,
[Start Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Start Year] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
["Expiration"] [datetime] NULL,
[Flag Complete] [float] NULL,
[Agency or Direct Buy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program Abbreviation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URL Advertised] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Advertisement Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spot Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spot Length] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spots per Episode] [float] NULL,
[Program Category or Format] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost (Per Episode or SOV) ] [money] NULL,
[Avg Episode Impressions] [float] NULL,
[CPM] [money] NULL,
[Total Impressions] [float] NULL,
[Total Cost] [money] NULL,
[Sessions] [float] NULL,
[Finished Registration (Goal 1 Completions)] [float] NULL,
[Signed up For Subscription (Goal 2 Completions)] [float] NULL,
[Cost Per Signup] [money] NULL,
[Response Rate] [float] NULL,
[Website Conversion Rate (Sessions to Signups)] [float] NULL,
[Invoice #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Invoice Submitted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test (1) or Renewal (0)] [float] NULL,
[Control (High Price URL) including HTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Low Price URL (Test) including HTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGC Redirect High Price URL including HTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGC Redirect Low Price URL including HTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
