CREATE TABLE [Archive].[DMCourse_BKP20120225]
(
[CourseID] [int] NULL,
[CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbbrvCourseName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseParts] [decimal] (18, 2) NULL,
[CourseHours] [float] NULL,
[ReleaseDate] [datetime] NULL,
[SubjectCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectCategoryID] [int] NULL,
[PCASubjectCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BundleFlag] [tinyint] NULL,
[PreReleaseCoursePref] [float] NULL,
[PostReleaseCourseSat] [float] NULL,
[CSATAsOfDate] [datetime] NULL,
[FlagActive] [tinyint] NULL,
[TerminationDate] [smalldatetime] NULL,
[PreReleaseSubjectMultiplier] [float] NULL,
[PrefPoint] [float] NULL,
[PDSubjectCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalPaidImages] [int] NULL,
[CostPaidImages] [money] NULL,
[TotalFreeImages] [int] NULL,
[Topic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubTopic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioDL] [tinyint] NULL,
[FlagVideoDL] [tinyint] NULL,
[VideoDL_ReleaseDate] [datetime] NULL,
[FlagCD] [tinyint] NULL,
[FlagDVD] [tinyint] NULL,
[FlagAudioDLOnly] [tinyint] NULL,
[FlagBuffetSet] [bit] NULL
) ON [PRIMARY]
GO
