CREATE TABLE [dbo].[NCOA_CHNGS_TGC_Test10k]
(
[fullname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addtype] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sublist] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[list] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mailkey] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[multi] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crrt] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coa_type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zapcode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vulname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vuladdr] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[old_zip] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dlvrblty] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acctno] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lacsflag] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[aptappend] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coa_date] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip4rcdtyp] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acctno_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pre] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sufname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ttcadd1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ttcadd2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[old_city] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[old_state] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[old_zip_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inpprecat] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inpcusseg] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inpcustyp] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[odate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
