CREATE TABLE [dbo].[TGCFBA_20160228FromJames]
(
[amazon-order-id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipment-id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipment-item-id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amazon-order-item-id] [float] NULL,
[purchase-date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[payments-date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipment-date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reporting-date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyer-email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyer-name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sku] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[product-name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quantity-shipped] [float] NULL,
[currency] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item-price] [float] NULL,
[item-tax] [float] NULL,
[shipping-price] [float] NULL,
[shipping-tax] [float] NULL,
[ship-service-level] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[recipient-name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship-address-1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship-city] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship-state] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship-postal-code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship-country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item-promotion-discount] [float] NULL,
[ship-promotion-discount] [float] NULL,
[carrier] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tracking-number] [float] NULL,
[estimated-arrival-date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fulfillment-center-id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fulfillment-channel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales-channel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
