CREATE TABLE [dbo].[DigialCust_analysis_20161109BKPDEL]
(
[CustomerID] [dbo].[udtCustomerID] NULL,
[StartDate] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EndDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustSegmentAsOfDate] [datetime] NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mf] [int] NULL,
[FmtPD_DigitalOnly] [int] NULL,
[FmtPD_PhysicalOnly] [int] NULL,
[FmtPD_BothDgtlPhscl] [int] NULL,
[FmtPD_None] [int] NULL,
[FmtPD_Digital] [int] NULL,
[FmtPD_Physical] [int] NULL,
[FmtAV_VideoOnly] [int] NULL,
[FmtAV_AudioOnly] [int] NULL,
[FmtAV_BothAudioVidoe] [int] NULL,
[FmtAV_None] [int] NULL,
[FmtAV_Video] [int] NULL,
[FmtAV_Audio] [int] NULL,
[FMT_DigitalAudio] [int] NULL,
[FMT_DVD] [int] NULL,
[FMT_CD] [int] NULL,
[FMT_DigitalVideo] [int] NULL,
[FMT_Transcript] [int] NULL,
[FMT_DigitalTranscript] [int] NULL,
[Sales_DigitalAudio] [money] NULL,
[Sales_DVD] [money] NULL,
[Sales_CD] [money] NULL,
[Sales_DigitalVideo] [money] NULL,
[Sales_Transcript] [money] NULL,
[Sales_DigitalTranscript] [money] NULL,
[TotalSalesOrd] [money] NULL,
[TotalOrders] [int] NULL,
[Source_Web] [int] NULL,
[Source_NonWeb] [int] NULL,
[Sales_Web] [numeric] (38, 5) NULL,
[Sales_NonWeb] [numeric] (38, 5) NULL
) ON [PRIMARY]
GO
