CREATE TABLE [dbo].[TN_ContactAnalysis_20120927_FnlSMRY]
(
[AsofYear] [smallint] NOT NULL,
[AsOfDate] [date] NOT NULL,
[Newseg] [tinyint] NOT NULL,
[Name] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[A12MF] [tinyint] NOT NULL,
[CustomerSegment] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Frequency] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTD_AOS_Bin] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecencyBin] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CountryCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R3OrderSource] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlAvgOrderBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_CourseCategory] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgeBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlPromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Numhits_Bin_2010] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Numhits_Bin_2011] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Totalcustomers] [int] NULL,
[TotalSalesYTD] [money] NULL,
[TotalOrdersYTD] [int] NULL,
[TotalUnitsYTD] [int] NULL,
[TotalPartsYTD] [dbo].[udtCourseParts] NULL,
[TotalContactsYTD] [int] NULL,
[TotalSalesFY] [money] NULL,
[TotalOrdersFY] [int] NULL,
[TotalUnitsFY] [int] NULL,
[TotalPartsFY] [money] NULL,
[TotalContactsFY] [int] NULL
) ON [PRIMARY]
GO
