CREATE TABLE [dbo].[ANIData_Input]
(
[a] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[e] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[f] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[g] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[h] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[i] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[j] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[k] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[m] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[p] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[q] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[r] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[s] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[t] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[u] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[v] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[w] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[x] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[y] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[z] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[aa] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bb] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceTollFree] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeStamp] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourcePhoneNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DurationoftheCall] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dd] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
