CREATE TABLE [dbo].[PageAllocation]
(
[PA_Adcode] [float] NULL,
[PA_CourseID] [float] NULL,
[PA_SetFlag] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SetID] [float] NULL,
[PA_Section] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SubCategory] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CourseName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Parts] [float] NULL,
[PA_Lectures] [float] NULL,
[PA_MinPerLctr] [float] NULL,
[PA_PageSize] [float] NULL,
[PA_PageStart] [float] NULL,
[PA_PriceMatrix] [float] NULL,
[PA_Currency] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDFull] [float] NULL,
[PA_DVD] [float] NULL,
[PA_DVFull] [float] NULL,
[PA_DV] [float] NULL,
[PA_CDFull] [float] NULL,
[PC_CD] [float] NULL,
[PA_DAFull] [float] NULL,
[PA_DA] [float] NULL,
[PA_PTFull] [float] NULL,
[PA_PT] [float] NULL,
[PA_DTFull] [float] NULL,
[PA_DT] [float] NULL,
[PA_DVDOmni] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDOmni] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SoundTrack] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
