CREATE TABLE [dbo].[Tracker_ResponseData_Oct2014_KeySurvey]
(
[Survey_Year_Month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurveyDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F1_F2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENSAT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENSAT_BIN_LABEL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENSAT_VB] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPLIKELI_VALUE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPLIKELI_BIN_LABEL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPLIKELI_VB] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORRECOMM_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIKELIRECOMM_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIKELIRECOMM_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIKELIRECOMM_VB] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTEFFORT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTEFFORT_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTEFFORT_VB] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATSAT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATSAT_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATSATVB] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Freq_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Freq_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAT_Freq_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAT_Freq_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSESELECTSAT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSESELECTSAT_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSEID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSENAME] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIATYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreamCourse] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DLExperience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Streaming Experience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSESAT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSESAT_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSESATVB] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEARN_New_or_Valuable_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEARN_New_or_ValuableBIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Course_Price_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Course_Price_Value_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROFPRESENTSAT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROFPRESENTSAT_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VISUALSAT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VISUALSAT_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUIDEBOOKSAT_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUIDEBOOKSAT_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE_EASENAV_Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE_EASENAV_BIN_Label] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE_LAYOUT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE_LAYOUT_BIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE_ACCURACY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE_ACCURACY_BIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACSI_Ideal_Course] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACSI_Ideal_Course_BIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACSI_Expectations] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACSI_Expectations_BIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Backlog] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Backlog_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MajorProblems] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contacted_CSR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Problem_Detail] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Problem_Resolved] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Android _App_SAT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[iPadAppSAT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppleSmartphoneappSAT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheTorchSAT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
