CREATE TABLE [dbo].[TempCBA1_812]
(
[SubmitDate] [date] NULL,
[AsOfDate] [date] NULL,
[Qtr] [float] NULL,
[YEAR] [float] NULL,
[Month] [int] NULL,
[EmailAddress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [float] NULL,
[Frequency_Trckr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastFormatWatched] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Backlog] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BacklogNumber] [float] NULL,
[BirthYear_Trckr] [float] NULL,
[Gender_Trckr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education_Trckr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mf] [int] NULL,
[PreferredCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MediaFormatPreference] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSourcePreference] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[AgeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseHoldIncomeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TenureMonths_LTD] [int] NULL,
[TenureMonths_Bin_LTD] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTDSales] [money] NULL,
[LTDOrders] [int] NULL,
[LTDUnits] [int] NULL,
[LTDParts] [dbo].[udtCourseParts] NULL
) ON [PRIMARY]
GO
