CREATE TABLE [dbo].[stripecharges_20170807]
(
[amount] [bigint] NULL,
[amount_refunded] [bigint] NULL,
[balance_transaction] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[blendo_imported_at] [bigint] NULL,
[captured] [bit] NULL,
[created] [datetime] NULL,
[currency] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[failure_code] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[failure_message] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fraud_details_stripe_report] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[livemode] [bit] NULL,
[metadata_capturereferenceid] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_pretaxamount] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_siteid] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_sitename] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_subscriptionplanid] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_subscriptionplanidentifier] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_taxamount] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_useremail] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[metadata_userid] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[object] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_network_status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_risk_level] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_rule_action] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_rule_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_rule_predicate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_seller_message] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[outcome_type] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paid] [bit] NULL,
[receipt_number] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[refunded] [bit] NULL,
[review] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_city] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_country] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_line1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_line1_check] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_state] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_zip] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_address_zip_check] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_brand] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_country] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_customer] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_cvc_check] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_exp_month] [bigint] NULL,
[source_exp_year] [bigint] NULL,
[source_fingerprint] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_funding] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_last4] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[source_object] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statement_descriptor] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_product_description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_livemode] [bit] NULL,
[dispute_balance_transactions_sourced_transfers_url] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_created] [bigint] NULL,
[dispute_evidence_customer_email_address] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_net] [bigint] NULL,
[dispute_evidence_customer_purchase_ip] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_object] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_fee_details_type] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_refund_refusal_explanation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_fee_details_currency] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_source] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_uncategorized_text] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_details_past_due] [bit] NULL,
[dispute_evidence_details_has_evidence] [bit] NULL,
[dispute_balance_transactions_fee_details_description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_fee] [bigint] NULL,
[dispute_balance_transactions_type] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_details_due_by] [bigint] NULL,
[dispute_created] [bigint] NULL,
[dispute_currency] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_billing_address] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_amount] [bigint] NULL,
[dispute_status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_sourced_transfers_has_more] [bit] NULL,
[dispute_evidence_customer_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_reason] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_amount] [bigint] NULL,
[dispute_balance_transactions_sourced_transfers_total_count] [bigint] NULL,
[dispute_balance_transaction] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_fee_details_amount] [bigint] NULL,
[dispute_evidence_uncategorized_file] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_available_on] [bigint] NULL,
[dispute_charge] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_details_submission_count] [bigint] NULL,
[dispute_is_charge_refundable] [bit] NULL,
[dispute_balance_transactions_sourced_transfers_object] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_currency] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_balance_transactions_object] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_duplicate_charge_documentation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_duplicate_charge_explanation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_access_activity_log] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_customer_communication] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_customer_signature] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dispute_evidence_cancellation_policy_disclosure] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
