CREATE TABLE [dbo].[AllDAX_NotInMagentoByEmail20130312]
(
[Customerid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerSince] [datetime] NOT NULL,
[EmailAddress] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagValidEmail] [int] NOT NULL,
[FlagEmailPref] [int] NOT NULL,
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orders] [int] NULL,
[Sales] [money] NULL,
[DigitalOrders] [int] NULL,
[DigitalSales] [money] NULL,
[MinOrderDate] [datetime] NULL,
[MaxOrderDate] [datetime] NULL,
[FlagDigital] [int] NOT NULL,
[FlagOmni] [int] NOT NULL,
[FlagCustMatch] [int] NOT NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagEmailPrefAsof312] [int] NULL,
[CustIsRoot] [int] NOT NULL,
[ChainedToRoot] [int] NOT NULL,
[InFirstMagentoFile] [int] NOT NULL,
[LTDSales] [money] NOT NULL,
[LTDOrders] [int] NOT NULL,
[LTD_EmailSales] [money] NOT NULL,
[LTD_EmailOrders] [int] NOT NULL,
[L12MSales] [money] NOT NULL,
[L12MOrders] [int] NOT NULL,
[L12M_EmailSales] [money] NOT NULL,
[L12M_EmailOrders] [int] NOT NULL
) ON [PRIMARY]
GO
