CREATE TABLE [dbo].[NCOA_CHNGS_Mar2014_SampleFile1]
(
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Addr1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Addr2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwellType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubList] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[List] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KeyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MultiBuyer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierRoute] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NCOAType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zapcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VulgarName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VulgarAddr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OldZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deliveability] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LacsFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AACAPTAppend] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NCOAMoveDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip4RecordType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessTitle] [int] NULL,
[InputCustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputPrefix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputMiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputSuffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputCompany] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputAddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputAddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputPostalCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputPreferredCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputCustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputCustomerType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InputDateAndTime] [datetime] NOT NULL
) ON [PRIMARY]
GO
