CREATE TABLE [dbo].[ARR_20090101_20121231_2349850]
(
[Review ID] [float] NULL,
[Submission Date] [datetime] NULL,
[Initial Publish Date] [datetime] NULL,
[Moderation Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryHierarchy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Merit Rank] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Is a Ratings-Only Review] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Review Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Nickname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Overall Rating] [float] NULL,
[Course ContentCourse Content] [float] NULL,
[Professor PresentationProfessor Presentation] [float] NULL,
[Course ValueCourse Value] [float] NULL,
[Recommend to a Friend] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Review Text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[# of Comments] [float] NULL,
[# of CommentsApproved] [float] NULL,
[# of CommentsRejected] [float] NULL,
[# of Commentsin Moderation] [float] NULL,
[# of Commentswith Photo] [float] NULL,
[# of Commentswith Video] [float] NULL,
[# of HelpfulVotes] [float] NULL,
[# of Not HelpfulVotes] [float] NULL,
[# of InappropriateVotes] [float] NULL,
[Format] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment Text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment Moderation Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment Submission Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment Initial Publish Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commenter Id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commenter Nickname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commenter Location] [datetime] NULL,
[Commenter Merit Rank] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
