CREATE TABLE [dbo].[DeclineLoyalty_Analysis]
(
[AsOfDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AsOfYear] [int] NOT NULL,
[AsOfMonth] [int] NOT NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagEmailable] [int] NULL,
[FlagMail] [int] NULL,
[Region] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseHoldIncomeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectCategoryPref2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R3OrderSourcePref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R3FormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eWGroup] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTB_Bin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTDAvgOrderBin] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSLPurchBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TenureBin] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagPrEmailOrder] [tinyint] NULL,
[FlagEngagedCust] [tinyint] NULL,
[FlagBoughtDigitlBfr] [tinyint] NULL,
[SalesBinPriorYr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagPhysicalDigital] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagMailOrderOnly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagContentPref] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagPurchYTD] [tinyint] NULL,
[FlagPurchNwCrsYTD] [tinyint] NULL,
[PurchAmountYTD] [money] NULL,
[PurchasesYTD] [int] NULL,
[CourseSalesYTD] [money] NULL,
[UnitsPurchYTD] [int] NULL,
[PartsPurchYTD] [money] NULL,
[EmailContactsYTD] [money] NULL,
[MailContactsYTD] [int] NULL,
[CustCount] [int] NULL
) ON [PRIMARY]
GO
