CREATE TABLE [Legacy].[Orders]
(
[OrderID] [int] NOT NULL,
[CustomerID] [int] NOT NULL,
[DateOrdered] [datetime] NULL,
[AdCode] [int] NULL,
[ShipFullName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddress] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddress2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipCity] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipRegion] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipPostalCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipCountryCode] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PmtMethodID] [smallint] NULL,
[PmtStatus] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardType] [int] NULL,
[CardNum] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardExpire] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipMethodID] [int] NULL,
[GiftFlag] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GiftMessage] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusCode] [int] NULL,
[TotalReadyCost] [money] NULL,
[TotalReadyTaxCost] [money] NULL,
[ShipUpgradeCost] [money] NULL,
[PaymentToDate] [money] NULL,
[DMGTPendingFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSRID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckNumber] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxExemptFlag] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogOrder] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReleaseDate] [datetime] NULL,
[OrderSource] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Instructions] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipCouponFlag] [nchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorPaid] [money] NULL,
[NetOrderAmount] [money] NULL,
[WebOrder_Id] [nchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[msrepl_tran_version] [uniqueidentifier] NULL,
[ShipFirstName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipLastName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipPhoneNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegShipCost] [money] NULL,
[Discount] [money] NULL,
[ReturnAmt] [money] NULL,
[DateModified] [datetime] NULL,
[DateReturned] [datetime] NULL,
[DiscountReason] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZeroCostReason] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress2] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCountryCode] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingRegion] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingPostalCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgentLastModified] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartialShip] [int] NULL,
[escstatus] [int] NULL,
[institution_key] [int] NULL,
[OrdersAgent_key] [int] NULL,
[OverrideShipping] [int] NULL,
[IncludeShipInTax] [int] NULL,
[ItemsReturned] [int] NULL,
[GenerateCheck] [int] NULL,
[OrderType] [int] NULL,
[TaxRate] [float] NULL,
[Notes] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxPaidToDate] [money] NULL,
[DiscountAppliedToDate] [money] NULL,
[RetShipAmt] [money] NULL,
[RetMerchAmt] [money] NULL,
[RetTaxAmt] [money] NULL,
[ShipEmail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipAddressTypeID] [int] NULL,
[retCouponAmt] [money] NULL,
[GST_HSTAmt] [money] NULL,
[PST_QSTAmt] [money] NULL,
[RetGST_HSTAmt] [money] NULL,
[RetPST_QSTAmt] [money] NULL,
[ShippingCharge] [money] NULL,
[MinShipDate] [datetime] NULL,
[MaxShipDate] [datetime] NULL,
[FlagCouponRedm] [bit] NULL,
[DiscountAmount] [money] NULL,
[Tax] [money] NULL,
[CurrencyCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idxOrders_AdCode_NetOrderAmount] ON [Legacy].[Orders] ([AdCode], [NetOrderAmount]) INCLUDE ([CardType], [CurrencyCode], [CustomerID], [OrderID], [OrderSource], [PmtMethodID], [ShipMethodID], [StatusCode]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idxOrders_NetOrderAmount_DateOrdered] ON [Legacy].[Orders] ([NetOrderAmount], [DateOrdered]) INCLUDE ([AdCode], [CardType], [CatalogOrder], [CurrencyCode], [CustomerID], [OrderID], [OrderSource], [PmtMethodID], [ShipMethodID], [StatusCode]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idxOrders_OrderID] ON [Legacy].[Orders] ([OrderID]) INCLUDE ([DateOrdered]) ON [PRIMARY]
GO
