CREATE TABLE [Mapping].[CustomerOverlay_WD2_20161215_del]
(
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MatchResult] [int] NULL,
[MatchResultDesc] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeDescription] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EducationID] [int] NULL,
[Education] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BirthDate_CCYYMM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthYear] [int] NULL,
[BirthMonth] [int] NULL,
[DateOfBirth] [datetime] NULL,
[Gender] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PresenceOfChildren] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NetWorth] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MailOrderBuyer] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RCM_Score] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateFromWD] [datetime] NULL,
[DateUpdated] [datetime] NOT NULL,
[UpdateFromWD] [int] NULL,
[WDScore] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WDRAwScore] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADD1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADD2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADD3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
