CREATE TABLE [Mapping].[SQ_PageAllocationRnd1]
(
[PA_Adcode] [int] NULL,
[PA_CourseID] [int] NULL,
[PA_SetFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Section] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SubCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Parts] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Lectures] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_MinPerLctr] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PageSize] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PageStart] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PriceMatrix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Currency] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DV] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DAFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PTFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DTFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDOmni] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDOmni] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SoundTrack] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
