CREATE TABLE [Mapping].[Prospect_OSWCoursePA_CustDS_BKP]
(
[OSWYear] [int] NOT NULL,
[OSWType] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [int] NULL,
[AdCodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StartDate] [datetime] NULL,
[StopDate] [datetime] NULL,
[IntlDVDBuyer] [int] NULL,
[IntlCDBuyer] [int] NULL,
[IntlVDLBuyer] [int] NULL,
[IntlADLBuyer] [int] NULL,
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSales] [money] NULL,
[IntlOrders] [int] NULL,
[IntlUnits] [int] NULL,
[DS3Mo_RepeatBuyer] [int] NOT NULL,
[DS3Mo_Sales] [money] NULL,
[DS3Mo_Orders] [int] NULL,
[DS3Mo_Units] [int] NULL,
[PA_Adcode] [int] NULL,
[PA_CourseID] [int] NULL,
[PA_SetFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SetID] [int] NULL,
[PA_Section] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SubCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Parts] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Lectures] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_MinPerLctr] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PageSize] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PageStart] [money] NULL,
[PA_PriceMatrix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Currency] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DV] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DAFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PTFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DTFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDOmni] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDOmni] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SoundTrack] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OSWName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgeBin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrsReleaseDate] [date] NULL,
[CrsFlagAudioVideo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrsSubjCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrsBazaarRating] [float] NULL,
[FlagControl] [int] NULL,
[FlagPriceTest] [int] NULL,
[FlagPATest] [int] NULL,
[PA_ID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
