CREATE TABLE [Mapping].[CustomerOverLay]
(
[CustomerID] [dbo].[udtCustomerID] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDate_CCYYMM] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthYear] [int] NULL,
[BirthMonth] [int] NULL,
[DateOfBirth] [datetime] NULL,
[CombinedAge] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAgeExctEst] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExperianAge] [int] NULL,
[EstHouseholdIncomeV4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseHoldIncomeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HouseHoldIncomeRange] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Education_Individual1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EducationConfidence] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC0to3Confirm] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC0to3Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC4to6Confirm] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC4to6Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC7to9Confirm] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC7to9Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC10to12Confirm] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC10to12Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC13to18Confirm] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POC13to18Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POCAge0_3V3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POCAge4_6V3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POCAge7_9V3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POCAge10_12V3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POCAge13_15V3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POCAge16_18V3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalEnhancementMatchType] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateFromExperian] [datetime] NULL,
[DateUpdated] [datetime] NOT NULL,
[IntlPurchaseDate] [datetime] NULL,
[IntlPurchaseYear] [int] NULL,
[IntlPurchaseMonth] [int] NULL,
[IntlPurchaseAge] [int] NULL,
[IntlPurchaseAgeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagIntlHSByr] [tinyint] NULL,
[IntlPurchaseOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdateDate] [datetime] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [idxCustomerOverLay_CustomerID] ON [Mapping].[CustomerOverLay] ([CustomerID]) ON [PRIMARY]
GO
