CREATE TABLE [Marketing].[DMSOUPByFormat]
(
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dateordered] [datetime] NULL,
[NetOrderAmount] [money] NULL,
[ShippingCharge] [money] NULL,
[DiscountAmount] [money] NULL,
[Tax] [money] NULL,
[CDSales] [money] NULL,
[CDUnits] [int] NULL,
[CDParts] [money] NULL,
[DVDSales] [money] NULL,
[DVDUnits] [int] NULL,
[DVDParts] [money] NULL,
[AudioTapeSales] [money] NULL,
[AudioTapeUnits] [int] NULL,
[AudioTapeParts] [money] NULL,
[VHSSales] [money] NULL,
[VHSUnits] [int] NULL,
[VHSParts] [money] NULL,
[AudioDLSales] [money] NULL,
[AudioDLUnits] [int] NULL,
[AudioDLParts] [money] NULL,
[VideoDLSales] [money] NULL,
[VideoDLUnits] [int] NULL,
[VideoDLParts] [money] NULL,
[TranscriptSales] [money] NULL,
[TranscriptUnits] [int] NULL,
[TranscriptParts] [money] NULL,
[DigitalTranscriptSales] [money] NULL,
[DigitalTranscriptUnits] [int] NULL,
[DigitalTranscriptParts] [money] NULL,
[DigitalSales] [money] NULL,
[DigitalUnits] [int] NULL,
[DigitalParts] [money] NULL,
[PhysicalSales] [money] NULL,
[PhysicalUnits] [int] NULL,
[PhysicalParts] [money] NULL,
[TotalMerchandizeSales] [money] NULL,
[TotalMerchandizeUnits] [int] NULL,
[TotalMerchandizeParts] [money] NULL,
[Adj_CDSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_C__14E877FA] DEFAULT ((0)),
[Adj_DVDSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_D__15DC9C33] DEFAULT ((0)),
[Adj_AudioTapeSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_A__16D0C06C] DEFAULT ((0)),
[Adj_VHSSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_V__17C4E4A5] DEFAULT ((0)),
[Adj_AudioDLSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_A__18B908DE] DEFAULT ((0)),
[Adj_VideoDLSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_V__19AD2D17] DEFAULT ((0)),
[Adj_TranscriptSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_T__1AA15150] DEFAULT ((0)),
[Adj_DigitalTranscriptSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_D__1B957589] DEFAULT ((0)),
[Adj_DigitalSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_D__1C8999C2] DEFAULT ((0)),
[Adj_PhysicalSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_P__1D7DBDFB] DEFAULT ((0)),
[Adj_TotalMerchandizeSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_T__1E71E234] DEFAULT ((0))
) ON [PRIMARY]
GO
