CREATE TABLE [Marketing].[DMCustomerReActivationDownStreamMonthlyNew]
(
[Customerkey] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS1moSales] [money] NULL,
[DS2moSales] [money] NULL,
[DS3moSales] [money] NULL,
[DS4moSales] [money] NULL,
[DS5moSales] [money] NULL,
[DS6moSales] [money] NULL,
[DS7moSales] [money] NULL,
[DS8moSales] [money] NULL,
[DS9moSales] [money] NULL,
[DS10moSales] [money] NULL,
[DS11moSales] [money] NULL,
[DS12moSales] [money] NULL,
[DS24moSales] [money] NULL,
[DS36moSales] [money] NULL,
[DS48moSales] [money] NULL,
[DS60moSales] [money] NULL,
[DS72moSales] [money] NULL,
[DS84moSales] [money] NULL,
[DS96moSales] [money] NULL,
[DS108moSales] [money] NULL,
[DS120moSales] [money] NULL,
[DS132moSales] [money] NULL,
[DS144moSales] [money] NULL,
[DS156moSales] [money] NULL,
[DS168moSales] [money] NULL,
[DS180moSales] [money] NULL,
[DS1moOrders] [int] NULL,
[DS2moOrders] [int] NULL,
[DS3moOrders] [int] NULL,
[DS4moOrders] [int] NULL,
[DS5moOrders] [int] NULL,
[DS6moOrders] [int] NULL,
[DS7moOrders] [int] NULL,
[DS8moOrders] [int] NULL,
[DS9moOrders] [int] NULL,
[DS10moOrders] [int] NULL,
[DS11moOrders] [int] NULL,
[DS12moOrders] [int] NULL,
[DS24moOrders] [int] NULL,
[DS36moOrders] [int] NULL,
[DS48moOrders] [int] NULL,
[DS60moOrders] [int] NULL,
[DS72moOrders] [int] NULL,
[DS84moOrders] [int] NULL,
[DS96moOrders] [int] NULL,
[DS108moOrders] [int] NULL,
[DS120moOrders] [int] NULL,
[DS132moOrders] [int] NULL,
[DS144moOrders] [int] NULL,
[DS156moOrders] [int] NULL,
[DS168moOrders] [int] NULL,
[DS180moOrders] [int] NULL,
[DS1moFlagRepeatByr] [int] NULL,
[DS2moFlagRepeatByr] [int] NULL,
[DS3moFlagRepeatByr] [int] NULL,
[DS4moFlagRepeatByr] [int] NULL,
[DS5moFlagRepeatByr] [int] NULL,
[DS6moFlagRepeatByr] [int] NULL,
[DS7moFlagRepeatByr] [int] NULL,
[DS8moFlagRepeatByr] [int] NULL,
[DS9moFlagRepeatByr] [int] NULL,
[DS10moFlagRepeatByr] [int] NULL,
[DS11moFlagRepeatByr] [int] NULL,
[DS12moFlagRepeatByr] [int] NULL,
[DS24moFlagRepeatByr] [int] NULL,
[DS36moFlagRepeatByr] [int] NULL,
[DS48moFlagRepeatByr] [int] NULL,
[DS60moFlagRepeatByr] [int] NULL,
[DS72moFlagRepeatByr] [int] NULL,
[DS84moFlagRepeatByr] [int] NULL,
[DS96moFlagRepeatByr] [int] NULL,
[DS108moFlagRepeatByr] [int] NULL,
[DS120moFlagRepeatByr] [int] NULL,
[DS132moFlagRepeatByr] [int] NULL,
[DS144moFlagRepeatByr] [int] NULL,
[DS156moFlagRepeatByr] [int] NULL,
[DS168moFlagRepeatByr] [int] NULL,
[DS180moFlagRepeatByr] [int] NULL,
[DS1moOrderUnits] [int] NULL,
[DS2moOrderUnits] [int] NULL,
[DS3moOrderUnits] [int] NULL,
[DS4moOrderUnits] [int] NULL,
[DS5moOrderUnits] [int] NULL,
[DS6moOrderUnits] [int] NULL,
[DS7moOrderUnits] [int] NULL,
[DS8moOrderUnits] [int] NULL,
[DS9moOrderUnits] [int] NULL,
[DS10moOrderUnits] [int] NULL,
[DS11moOrderUnits] [int] NULL,
[DS12moOrderUnits] [int] NULL,
[DS24moOrderUnits] [int] NULL,
[DS36moOrderUnits] [int] NULL,
[DS48moOrderUnits] [int] NULL,
[DS60moOrderUnits] [int] NULL,
[DS72moOrderUnits] [int] NULL,
[DS84moOrderUnits] [int] NULL,
[DS96moOrderUnits] [int] NULL,
[DS108moOrderUnits] [int] NULL,
[DS120moOrderUnits] [int] NULL,
[DS132moOrderUnits] [int] NULL,
[DS144moOrderUnits] [int] NULL,
[DS156moOrderUnits] [int] NULL,
[DS168moOrderUnits] [int] NULL,
[DS180moOrderUnits] [int] NULL,
[DS1moEmailContacts] [int] NOT NULL,
[DS2moEmailContacts] [int] NOT NULL,
[DS3moEmailContacts] [int] NOT NULL,
[DS6moEmailContacts] [int] NOT NULL,
[DS12moEmailContacts] [int] NOT NULL,
[DS18moEmailContacts] [int] NOT NULL,
[DS24moEmailContacts] [int] NOT NULL,
[DS1momailContacts] [int] NOT NULL,
[DS2momailContacts] [int] NOT NULL,
[DS3momailContacts] [int] NOT NULL,
[DS6momailContacts] [int] NOT NULL,
[DS12momailContacts] [int] NOT NULL,
[DS18momailContacts] [int] NOT NULL,
[DS24momailContacts] [int] NOT NULL
) ON [PRIMARY]
GO
