CREATE TABLE [Marketing].[DMCustomerReActivation2]
(
[CustomerKey] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOrdered] [datetime] NULL,
[SequenceNum] [int] NULL,
[DownStreamDays] [int] NULL,
[DaysSinceLastPurchase] [int] NULL,
[CSRID] [int] NULL,
[CSRID_actual] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode] [int] NULL,
[AdCode] [int] NULL,
[PromotionType] [smallint] NULL,
[FlagCouponRedm] [tinyint] NULL,
[DiscountAmount] [money] NULL,
[NetOrderAmount] [money] NULL,
[FlagSplitShipment] [tinyint] NULL,
[FinalSales] [money] NULL,
[TotalCourseQuantity] [int] NULL,
[TotalCourseParts] [dbo].[udtCourseParts] NULL,
[TotalCourseSales] [money] NULL,
[TotalTranscriptQuantity] [int] NULL,
[TotalTranscriptParts] [dbo].[udtCourseParts] NULL,
[TotalTranscriptSales] [money] NULL,
[PriorPurchaseOrderAmount] [money] NULL,
[PriorPurchaseOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorPurchaseAdcode] [int] NULL,
[BillingCountryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDVDatCDProspect] [tinyint] NULL,
[FlagEmailOrder] [tinyint] NULL,
[CustomerSegmentPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrequencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewsegPrior] [int] NULL,
[NamePrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12mfPrior] [int] NULL,
[PriorSales] [money] NULL,
[PriorOrders] [int] NULL,
[PriorAOS] [money] NULL,
[ConcatenatedPrior] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonetaryValuePrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[AgeBin] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegment2Prior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnlPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GiftFlag] [bit] NULL,
[ShipRegion] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipCountryCode] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingRegion] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coupon] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponDesc] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
