CREATE TABLE [Marketing].[FBA_CustOrder]
(
[ReportDate] [date] NULL,
[buyer_email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyer_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12mf] [int] NULL,
[ComboID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFrcst] [varchar] (57) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addresscombo] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGCCust] [int] NOT NULL,
[ItemPrice] [money] NULL,
[ItemTax] [money] NULL,
[ItemDiscount] [money] NULL,
[ShippingPirce] [money] NULL,
[ShippingTax] [money] NULL,
[ShippingDiscount] [money] NULL,
[Units] [int] NULL,
[Orders] [int] NULL,
[NetOrderAmount] [money] NULL,
[TotalTax] [money] NULL
) ON [PRIMARY]
GO
