CREATE TABLE [Marketing].[EmailTracker_WPDLR]
(
[YearOfMailing] [int] NULL,
[MonthOfMailing] [int] NULL,
[DLREMailDate] [date] NULL,
[AdCode] [int] NULL,
[AdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode] [int] NULL,
[CatalogName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Year] [int] NULL,
[MD_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelID] [int] NULL,
[MD_ChannelName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PromotionTypeID] [int] NULL,
[MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CampaignID] [int] NULL,
[MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PriceType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StopDate] [datetime] NULL,
[CouponCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expiration] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Circ] [int] NULL,
[Orders] [int] NULL,
[Sales] [money] NULL,
[parts] [int] NULL,
[units] [int] NULL,
[ReportDate] [datetime] NOT NULL,
[Coupon_expired_flg] [int] NOT NULL
) ON [PRIMARY]
GO
