CREATE TABLE [Marketing].[DMCustomerStatic_UNITS_Smry]
(
[IntlSubjectPref] [dbo].[udtSubjectPreference] NOT NULL,
[IntlFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlPromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_MD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_MD_Year] [int] NULL,
[Intl_MD_PriceType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_MD_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlAvgOrderBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlPartsBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagEmailable] [tinyint] NULL,
[FlagMailable] [tinyint] NOT NULL,
[Gender] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOfHits] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_CourseCategory] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year] [int] NOT NULL,
[MonthID] [int] NOT NULL,
[QuarterID] [int] NOT NULL,
[SPFlag] [tinyint] NOT NULL,
[SPPromotionTypeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPSubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPSalesAmountCatID] [int] NOT NULL,
[SPFlag3Mth] [tinyint] NOT NULL,
[SPFlag6Mth] [tinyint] NOT NULL,
[SPFlag12Mth] [tinyint] NOT NULL,
[CountryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AgeBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EducationBin] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseHoldIncomeBin] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlAvgOrderBin_2] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS1moSales] [money] NULL,
[DS2moSales] [money] NULL,
[DS3moSales] [money] NULL,
[DS4moSales] [money] NULL,
[DS6moSales] [money] NULL,
[DS12moSales] [money] NULL,
[DS18moSales] [money] NULL,
[DS24moSales] [money] NULL,
[DS1moOrders] [int] NULL,
[DS2moOrders] [int] NULL,
[DS3moOrders] [int] NULL,
[DS4moOrders] [int] NULL,
[DS6moOrders] [int] NULL,
[DS12moOrders] [int] NULL,
[DS18moOrders] [int] NULL,
[DS24moOrders] [int] NULL,
[DS1moFlagRepeatByr] [int] NULL,
[DS2moFlagRepeatByr] [int] NULL,
[DS3moFlagRepeatByr] [int] NULL,
[DS4moFlagRepeatByr] [int] NULL,
[DS6moFlagRepeatByr] [int] NULL,
[DS12moFlagRepeatByr] [int] NULL,
[DS18moFlagRepeatByr] [int] NULL,
[DS24moFlagRepeatByr] [int] NULL,
[DS1moUnits] [int] NULL,
[DS2moUnits] [int] NULL,
[DS3moUnits] [int] NULL,
[DS4moUnits] [int] NULL,
[DS6moUnits] [int] NULL,
[DS12moUnits] [int] NULL,
[DS18moUnits] [int] NULL,
[DS24moUnits] [int] NULL,
[DS1moParts] [float] NULL,
[DS2moParts] [float] NULL,
[DS3moParts] [float] NULL,
[DS4moParts] [float] NULL,
[DS6moParts] [float] NULL,
[DS12moParts] [float] NULL,
[DS18moParts] [float] NULL,
[DS24moParts] [float] NULL,
[DS1moCourseSales] [money] NULL,
[DS2moCourseSales] [money] NULL,
[DS3moCourseSales] [money] NULL,
[DS4moCourseSales] [money] NULL,
[DS6moCourseSales] [money] NULL,
[DS12moCourseSales] [money] NULL,
[DS18moCourseSales] [money] NULL,
[DS24moCourseSales] [money] NULL,
[CustCount] [int] NULL,
[IntlPurchAmount] [money] NULL,
[IntlParts] [dbo].[udtCourseParts] NULL,
[IntlNumOfCOurses] [int] NULL,
[DS1moMailContacts] [int] NULL,
[DS2moMailContacts] [int] NULL,
[DS3moMailContacts] [int] NULL,
[DS6moMailContacts] [int] NULL,
[DS12moMailContacts] [int] NULL,
[DS18moMailContacts] [int] NULL,
[DS24moMailContacts] [int] NULL,
[DS1moEmailContacts] [int] NULL,
[DS2moEmailContacts] [int] NULL,
[DS3moEmailContacts] [int] NULL,
[DS6moEmailContacts] [int] NULL,
[DS12moEmailContacts] [int] NULL,
[DS18moEmailContacts] [int] NULL,
[DS24moEmailContacts] [int] NULL
) ON [PRIMARY]
GO
