CREATE TABLE [Marketing].[TempMidwayTrackerYTD_Smry]
(
[AsOfDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AsOfYear] [int] NOT NULL,
[AsOfMonth] [int] NOT NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12mf] [int] NULL,
[FlagEmailable] [int] NULL,
[FlagMail] [int] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectCategoryPref2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R3OrderSourcePref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTDAvgOrderBin] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSLPurchBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTB_Bin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Agebin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TenureBin] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[eWGroup] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagBoughtDigitlBfr] [tinyint] NULL,
[SalesBinPriorYr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseCntBinPriorYr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagEngagedCust] [tinyint] NULL,
[FlagPrEmailOrder] [tinyint] NULL,
[NwCrsBinYTD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalCustomers] [int] NULL,
[PurchAmountYTD] [money] NULL,
[PurchasesYTD] [int] NULL,
[UnitsPurchYTD] [int] NULL,
[PartsPurchYTD] [money] NULL,
[EmailSalesYTD] [int] NULL,
[EmailOrdersYTD] [int] NULL,
[WebSalesYTD] [int] NULL,
[WebOrdersYTD] [int] NULL,
[MailContactsYTD] [int] NULL,
[EmailContactsYTD] [money] NULL,
[BuyersYTD] [int] NULL,
[PurchAmountMTD] [money] NULL,
[PurchasesMTD] [int] NULL,
[UnitsPurchMTD] [int] NULL,
[PartsPurchMTD] [money] NULL,
[EmailSalesMTD] [int] NULL,
[EmailOrdersMTD] [int] NULL,
[WebSalesMTD] [int] NULL,
[WebOrdersMTD] [int] NULL,
[MailContactsMTD] [int] NULL,
[EmailContactsMTD] [money] NULL,
[PurchAmountFY] [money] NULL,
[PurchasesFY] [int] NULL,
[UnitsPurchFY] [int] NULL,
[PartsPurchFY] [money] NULL,
[EmailSalesFY] [int] NULL,
[EmailOrdersFY] [int] NULL,
[WebSalesFY] [int] NULL,
[WebOrdersFY] [int] NULL,
[MailContactsFY] [int] NULL,
[EmailContactsFY] [money] NULL,
[BuyersFY] [int] NULL,
[PurchAmountJAN] [money] NULL,
[PurchasesJAN] [int] NULL,
[UnitsPurchJAN] [int] NULL,
[PartsPurchJAN] [money] NULL,
[PurchAmountFEB] [money] NULL,
[PurchasesFEB] [int] NULL,
[UnitsPurchFEB] [int] NULL,
[PartsPurchFEB] [money] NULL,
[PurchAmountMAR] [money] NULL,
[PurchasesMAR] [int] NULL,
[UnitsPurchMAR] [int] NULL,
[PartsPurchMAR] [money] NULL,
[PurchAmountAPR] [money] NULL,
[PurchasesAPR] [int] NULL,
[UnitsPurchAPR] [int] NULL,
[PartsPurchAPR] [money] NULL,
[PurchAmountMAY] [money] NULL,
[PurchasesMAY] [int] NULL,
[UnitsPurchMAY] [int] NULL,
[PartsPurchMAY] [money] NULL,
[PurchAmountJUN] [money] NULL,
[PurchasesJUN] [int] NULL,
[UnitsPurchJUN] [int] NULL,
[PartsPurchJUN] [money] NULL,
[PurchAmountJUL] [money] NULL,
[PurchasesJUL] [int] NULL,
[UnitsPurchJUL] [int] NULL,
[PartsPurchJUL] [money] NULL,
[PurchAmountAUG] [money] NULL,
[PurchasesAUG] [int] NULL,
[UnitsPurchAUG] [int] NULL,
[PartsPurchAUG] [money] NULL,
[PurchAmountSEP] [money] NULL,
[PurchasesSEP] [int] NULL,
[UnitsPurchSEP] [int] NULL,
[PartsPurchSEP] [money] NULL,
[PurchAmountOCT] [money] NULL,
[PurchasesOCT] [int] NULL,
[UnitsPurchOCT] [int] NULL,
[PartsPurchOCT] [money] NULL,
[PurchAmountNOV] [money] NULL,
[PurchasesNOV] [int] NULL,
[UnitsPurchNOV] [int] NULL,
[PartsPurchNOV] [money] NULL,
[PurchAmountDEC] [money] NULL,
[PurchasesDEC] [int] NULL,
[UnitsPurchDEC] [int] NULL,
[PartsPurchDEC] [money] NULL,
[CatalogSalesYTD] [money] NULL,
[CatalogOrdersYTD] [int] NULL,
[MagalogSalesYTD] [money] NULL,
[MagalogOrdersYTD] [int] NULL,
[Mag7SalesYTD] [money] NULL,
[Mag7OrdersYTD] [int] NULL,
[MagazineSalesYTD] [money] NULL,
[MagazineOrdersYTD] [int] NULL,
[LetterSalesYTD] [money] NULL,
[LetterOrdersYTD] [int] NULL,
[MagbackSalesYTD] [money] NULL,
[MagbackOrdersYTD] [int] NULL,
[ReactivationSalesYTD] [money] NULL,
[ReactivationOrdersYTD] [int] NULL,
[EmailDLRSalesYTD] [money] NULL,
[EmailDLROrdersYTD] [int] NULL,
[EmailRevGenSalesYTD] [money] NULL,
[EmailRevGenOrdersYTD] [int] NULL,
[OtherSalesYTD] [money] NULL,
[OtherOrdersYTD] [int] NULL,
[CDSalesYTD] [money] NULL,
[CDOrdersYTD] [int] NULL,
[DVDSalesYTD] [money] NULL,
[DVDOrdersYTD] [int] NULL,
[VDLSalesYTD] [money] NULL,
[VDLOrdersYTD] [int] NULL,
[ADLSalesYTD] [money] NULL,
[ADLOrdersYTD] [int] NULL,
[TranscriptSalesYTD] [money] NULL,
[TranscriptOrdersYTD] [int] NULL
) ON [PRIMARY]
GO
