CREATE TABLE [Marketing].[DMSOUPByFormatIgnoreReturns]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dateordered] [datetime] NULL,
[NetOrderAmount] [money] NULL,
[ShippingCharge] [money] NULL,
[DiscountAmount] [money] NULL,
[Tax] [money] NULL,
[OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdCode] [int] NULL,
[CDSales] [money] NULL,
[CDUnits] [int] NULL,
[CDParts] [money] NULL,
[DVDSales] [money] NULL,
[DVDUnits] [int] NULL,
[DVDParts] [money] NULL,
[AudioTapeSales] [money] NULL,
[AudioTapeUnits] [int] NULL,
[AudioTapeParts] [money] NULL,
[VHSSales] [money] NULL,
[VHSUnits] [int] NULL,
[VHSParts] [money] NULL,
[AudioDLSales] [money] NULL,
[AudioDLUnits] [int] NULL,
[AudioDLParts] [money] NULL,
[VideoDLSales] [money] NULL,
[VideoDLUnits] [int] NULL,
[VideoDLParts] [money] NULL,
[TranscriptSales] [money] NULL,
[TranscriptUnits] [int] NULL,
[TranscriptParts] [money] NULL,
[DigitalTranscriptSales] [money] NULL,
[DigitalTranscriptUnits] [int] NULL,
[DigitalTranscriptParts] [money] NULL,
[DigitalSales] [money] NULL,
[DigitalUnits] [int] NULL,
[DigitalParts] [money] NULL,
[PhysicalSales] [money] NULL,
[PhysicalUnits] [int] NULL,
[PhysicalParts] [money] NULL,
[TotalMerchandizeSales] [money] NULL,
[TotalMerchandizeUnits] [int] NULL,
[TotalMerchandizeParts] [money] NULL,
[FlagCD] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagC__1753DC0C] DEFAULT ((0)),
[FlagDVD] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagD__18480045] DEFAULT ((0)),
[FlagAudioTape] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagA__193C247E] DEFAULT ((0)),
[FlagVHS] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagV__1A3048B7] DEFAULT ((0)),
[FlagAudioDL] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagA__1B246CF0] DEFAULT ((0)),
[FlagVideoDL] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagV__1C189129] DEFAULT ((0)),
[FlagTranscript] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagT__1D0CB562] DEFAULT ((0)),
[FlagDigitalTranscript] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagD__1E00D99B] DEFAULT ((0)),
[FlagDigital] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagD__1EF4FDD4] DEFAULT ((0)),
[FlagPhysical] [bit] NULL CONSTRAINT [DF__DMSOUPByF__FlagP__1FE9220D] DEFAULT ((0)),
[OrderSourceRU] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelID] [int] NULL,
[MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelRU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adj_CDSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_C__20DD4646] DEFAULT ((0)),
[Adj_DVDSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_D__21D16A7F] DEFAULT ((0)),
[Adj_AudioTapeSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_A__22C58EB8] DEFAULT ((0)),
[Adj_VHSSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_V__23B9B2F1] DEFAULT ((0)),
[Adj_AudioDLSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_A__24ADD72A] DEFAULT ((0)),
[Adj_VideoDLSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_V__25A1FB63] DEFAULT ((0)),
[Adj_TranscriptSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_T__26961F9C] DEFAULT ((0)),
[Adj_DigitalTranscriptSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_D__278A43D5] DEFAULT ((0)),
[Adj_DigitalSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_D__287E680E] DEFAULT ((0)),
[Adj_PhysicalSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_P__29728C47] DEFAULT ((0)),
[Adj_TotalMerchandizeSales] [money] NULL CONSTRAINT [DF__DMSOUPByF__Adj_T__2A66B080] DEFAULT ((0))
) ON [PRIMARY]
GO
