CREATE TABLE [Marketing].[Step1_NCP_NewCourses]
(
[CourseID] [int] NULL,
[CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbbrvCourseName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseParts] [int] NULL,
[SubjectCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubjectCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDSubjectCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReleaseDate] [datetime] NULL,
[ReleaseYear] [int] NULL,
[CoursePrefScore] [float] NULL,
[SubjMultiplier_PreRel] [float] NULL,
[AdjPrefScore_PreRel] [float] NULL,
[AdjPrefPoints_PreRel] [float] NULL,
[SubjMultiplier_Current] [float] NULL,
[AdjPrefScore_Current] [float] NULL,
[AdjPrefPoints_Current] [float] NULL,
[TotalPaidImages] [int] NULL,
[TotalFreeImages] [int] NULL,
[TotalImages] [int] NULL,
[TotalImagesPerPart] [float] NULL,
[PostReleaseCourseSat] [float] NULL,
[CatalogCode] [int] NOT NULL,
[CatalogName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cat_StartDate] [datetime] NULL,
[Cat_StopDate] [datetime] NULL,
[MailConsolidateID] [int] NULL,
[MailConsolidateName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalActivesMailed] [int] NULL,
[OverallSales_ActRecips_03Mo] [money] NULL,
[OverallOrders_ActRecips_03Mo] [int] NULL,
[CourseSales_ActRecips_03Mo] [money] NULL,
[CourseOrders_ActRecips_03Mo] [int] NULL,
[CourseDrvnSales_ActRecips_03Mo] [money] NULL,
[CourseDrvnOrders_ActRecips_03Mo] [int] NULL,
[OverallSales_ActRecips_CatLf] [money] NULL,
[OverallOrders_ActRecips_CatLf] [int] NULL,
[CourseSales_ActRecips_CatLf] [money] NULL,
[CourseOrders_ActRecips_CatLf] [int] NULL,
[CourseDrvnSales_ActRecips_CatLf] [money] NULL,
[CourseDrvnOrders_ActRecips_CatLf] [int] NULL,
[OverallSales_ActRecips_Coded] [money] NULL,
[OverallOrders_ActRecips_Coded] [int] NULL,
[CourseSales_ActRecips_Coded] [money] NULL,
[CourseOrders_ActRecips_Coded] [int] NULL,
[CourseDrvnSales_ActRecips_Coded] [money] NULL,
[CourseDrvnOrders_ActRecips_Coded] [int] NULL,
[OverallSales_ActRecips_01Mo] [money] NULL,
[OverallOrders_ActRecips_01Mo] [money] NULL,
[CourseSales_ActRecips_01Mo] [money] NULL,
[CourseOrders_ActRecips_01Mo] [money] NULL,
[CourseDrvnSales_ActRecips_01Mo] [money] NULL,
[CourseDrvnOrders_ActRecips_01Mo] [money] NULL
) ON [PRIMARY]
GO
