CREATE TABLE [Marketing].[DownloadReportCust]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrequencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewsegPrior] [int] NULL,
[NamePrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12mfPrior] [int] NULL,
[Age] [int] NULL,
[AgeBin] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderChan_Web] [int] NULL,
[OrderChan_Phone] [int] NULL,
[OrderChan_Mail] [int] NULL,
[OrderChan_Other] [int] NULL,
[OrderChan_Pref] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FormatPur_Audio] [int] NULL,
[FormatPur_Video] [int] NULL,
[FormatPur_Both] [int] NULL,
[FirstJanOrder] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstJanDate] [datetime] NULL,
[LastJanOrder] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastJanDate] [datetime] NULL,
[CoursePurJan] [int] NULL,
[LecturePurJan] [int] NULL,
[OrdersPurJan] [int] NULL,
[Subject_AH] [int] NULL,
[Subject_EC] [int] NULL,
[Subject_FA] [int] NULL,
[Subject_BL] [int] NULL,
[Subject_LIT] [int] NULL,
[Subject_MH] [int] NULL,
[Subject_PH] [int] NULL,
[Subject_PR] [int] NULL,
[Subject_RL] [int] NULL,
[Subject_SC] [int] NULL,
[Subject_MTH] [int] NULL,
[Gender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomeBin] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS1Mo_TotalCrsDL] [decimal] (38, 2) NULL,
[DS1Mo_TotalLecDL] [decimal] (38, 2) NULL,
[DS1Mo_PercentLecDL] [decimal] (7, 4) NULL,
[DS1Mo_TotalDLBin_DLvsLD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS1Mo_TotalDLBin_DLvsLP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS2Mo_TotalCrsDL] [decimal] (38, 2) NULL,
[DS2Mo_TotalLecDL] [decimal] (38, 2) NULL,
[DS2Mo_PercentLecDL] [decimal] (7, 4) NULL,
[DS2Mo_TotalDLBin_DLvsLD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS2Mo_TotalDLBin_DLvsLP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS3Mo_TotalCrsDL] [decimal] (38, 2) NULL,
[DS3Mo_TotalLecDL] [decimal] (38, 2) NULL,
[DS3Mo_PercentLecDL] [decimal] (7, 4) NULL,
[DS3Mo_TotalDLBin_DLvsLD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS3Mo_TotalDLBin_DLvsLP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalMinutesPurchased] [int] NULL,
[DS1Mo_TotalStreamMinutes] [decimal] (38, 2) NULL,
[DS1Mo_PercentStreamMinutes] [decimal] (7, 4) NULL,
[DS1Mo_TotalStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS2Mo_TotalStreamMinutes] [decimal] (38, 2) NULL,
[DS2Mo_PercentStreamMinutes] [decimal] (7, 4) NULL,
[DS2Mo_TotalStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS3Mo_TotalStreamMinutes] [decimal] (38, 2) NULL,
[DS3Mo_PercentStreamMinutes] [decimal] (7, 4) NULL,
[DS3Mo_TotalStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS1Mo_PurchaseFlag] [int] NULL,
[DS1Mo_Sales] [decimal] (8, 2) NULL,
[DS1Mo_Orders] [int] NULL,
[DS2Mo_PurchaseFlag] [int] NULL,
[DS2Mo_Sales] [decimal] (8, 2) NULL,
[DS2Mo_Orders] [int] NULL,
[DS3Mo_PurchaseFlag] [int] NULL,
[DS3Mo_Sales] [decimal] (8, 2) NULL,
[DS3Mo_Orders] [int] NULL,
[ActionTaken] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
