CREATE TABLE [Marketing].[B2BSales]
(
[ReportDate] [datetime] NOT NULL,
[YearOrdered] [int] NULL,
[MonthOrdered] [int] NULL,
[WeekOrdered] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOrdered] [date] NULL,
[orderid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CURRENCYCODE] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TotalMerchandise] [money] NULL,
[TotalCoupons] [money] NULL,
[TotalShipping] [money] NULL,
[TotalTaxes] [money] NULL,
[OtherCharges] [money] NULL,
[NetOrderAmount] [money] NULL,
[Adcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Ordersource] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Customerid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Firstname] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Lastname] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CatalogCode] [int] NOT NULL,
[CatalogName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Year] [int] NULL,
[MD_ChannelID] [int] NULL,
[MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PromotionTypeID] [int] NULL,
[MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CampaignID] [int] NULL,
[MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DVD_Units] [int] NULL,
[CD_Units] [int] NULL,
[VideoDownload_Units] [int] NULL,
[AudioDownload_Units] [int] NULL,
[Transcript_Units] [int] NULL,
[DVD_Parts] [int] NULL,
[CD_Parts] [int] NULL,
[VideoDownload_Parts] [int] NULL,
[AudioDownload_Parts] [int] NULL,
[Transcript_Parts] [int] NULL,
[DVD_Sales] [int] NULL,
[CD_Sales] [int] NULL,
[VideoDownload_Sales] [int] NULL,
[AudioDownload_Sales] [int] NULL,
[Transcript_Sales] [int] NULL
) ON [PRIMARY]
GO
