CREATE TABLE [Marketing].[TGCPlus_UserSummary]
(
[RegisteredYear] [int] NULL,
[RegisteredMonth] [int] NULL,
[RegisteredWeek] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegisteredDate] [date] NULL,
[IntlSubscribedYear] [int] NULL,
[IntlSubscribedMonth] [int] NULL,
[IntlSubscribedWeek] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSubscribedDate] [date] NULL,
[VLCampaign] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlCampaign] [int] NULL,
[IntlCampaignName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlCamapaignOfferCode] [int] NULL,
[IntlCamapaignOfferName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlMD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlMD_Year] [int] NULL,
[IntlMD_ChannelID] [int] NULL,
[IntlMD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlMD_PromotionTypeID] [int] NULL,
[IntlMD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlMD_CampaignID] [int] NULL,
[IntlMD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_Cmpn_StartDate] [datetime] NULL,
[Intl_Cmpn_StopDate] [datetime] NULL,
[FlagRegisteredOnly] [int] NOT NULL,
[FlagSubscribed] [int] NOT NULL,
[subscription_plan_id] [bigint] NULL,
[Subscription_Plan] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscription_Desc] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriptionType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReccrPaymentAmt] [real] NULL,
[OfferCodeUsed] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfferName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfferAppliedMthd] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[visible] [bit] NULL,
[FlagTGCCust] [int] NOT NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustCount] [int] NULL,
[MaxSubscriptionDate] [datetime] NULL,
[ReportDate] [datetime] NOT NULL
) ON [PRIMARY]
GO
