CREATE TABLE [Marketing].[DiscountTracker_OrdersSummary]
(
[AA01_IntlPromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AA02_IntlAcqsnYear] [int] NULL,
[AA03_IntlAcqsnMonth] [int] NULL,
[AA05_IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AA06_IntlPurchAmount] [money] NULL,
[AA07_IntlAOSBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AA08_IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AA09_IntlSubjectPref] [dbo].[udtSubjectPreference] NULL,
[AA10_IntlFlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AB01_AgeBin] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AB02_Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AB03_HouseHoldIncomeBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AB04_Education] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AC01_CustomerSegmentPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AC02_FrequencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AC03_NewsegPrior] [int] NULL,
[AC04_NamePrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AC05_A12mfPrior] [int] NOT NULL,
[AC06_MonetaryValuePrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AC08_PriorOrdersBin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AC10_PriorAOSBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AC12_DSLBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BA01_FlagHasCLRCourse] [bit] NULL,
[BA02_TotalCLRCourseSales] [money] NULL,
[BA03_TotalCLRCourseUnits] [int] NULL,
[BA04_TotalCLRCourseParts] [money] NULL,
[BA05_StdSalePriceCLRCourse] [money] NULL,
[BA06_PriceDiscount_CLRCrsLvl] [money] NULL,
[BA07_FlagPriceDiscount_CLRCrsLvl] [int] NOT NULL,
[BA08_FlagCLRCourseWthSets] [int] NOT NULL,
[BA09_TotalCLRCourseSalesWthSets] [money] NULL,
[BA10_TotalCLRCourseUnitsWthSets] [int] NULL,
[BA11_TotalCLRCoursePartsWthSets] [dbo].[udtCourseParts] NULL,
[BA12_StdSalePriceCLRCourseWthSets] [money] NULL,
[BA13_PriceDiscount_CLRCrsLvlWthSets] [money] NULL,
[BA14_FlagPriceDiscount_CLRCrsLvlWthSets] [int] NOT NULL,
[BA15_FlagCLRCourseNoSets] [int] NULL,
[BA16_TotalCLRCourseSalesNoSets] [money] NULL,
[BA17_TotalCLRCourseUnitsNoSets] [int] NULL,
[BA18_TotalCLRCoursePartsNoSets] [money] NULL,
[BA19_StdSalePriceCLRCourseNoSets] [money] NULL,
[BA20_PriceDiscount_CLRCrsLvlNoSets] [money] NULL,
[BA21_FlagPriceDiscount_CLRCrsLvlNoSets] [int] NULL,
[BB01_FlagHasOtherCourse] [bit] NULL,
[BB02_TotalOtherCourseSales] [money] NULL,
[BB03_TotalOtherCourseUnits] [int] NULL,
[BB04_TotalOtherCourseParts] [money] NULL,
[BB05_StdSalePriceOtherCourse] [money] NULL,
[BB06_PriceDiscount_OtherCrsLvl] [money] NULL,
[BB07_FlagPriceDiscount_OtherCrsLvl] [int] NOT NULL,
[BB08_FlagOtherCourseWthSets] [int] NOT NULL,
[BB09_TotalOtherCourseSalesWthSets] [money] NULL,
[BB10_TotalOtherCourseUnitsWthSets] [int] NULL,
[BB11_TotalOtherCoursePartsWthSets] [dbo].[udtCourseParts] NULL,
[BB12_StdSalePriceOtherCourseWthSets] [money] NULL,
[BB13_PriceDiscount_OtherCrsLvlWthSets] [money] NULL,
[BB14_FlagPriceDiscount_OtherCrsLvlWthSets] [int] NOT NULL,
[BB15_FlagOtherCourseNoSets] [int] NULL,
[BB16_TotalOtherCourseSalesNoSets] [money] NULL,
[BB17_TotalOtherCourseUnitsNoSets] [int] NULL,
[BB18_TotalOtherCoursePartsNoSets] [money] NULL,
[BB19_StdSalePriceOtherCourseNoSets] [money] NULL,
[BB20_PriceDiscount_OtherCrsLvlNoSets] [money] NULL,
[BB21_FlagPriceDiscount_OtherCrsLvlNoSets] [int] NULL,
[BC01_TotalCourseSales] [money] NULL,
[BC02_TotalCourseQuantity] [int] NULL,
[BC03_TotalCourseParts] [dbo].[udtCourseParts] NULL,
[BC04_StdSalePrice] [money] NULL,
[BC05_PriceDiscount_CrsLvl] [money] NULL,
[BC06_FlagPriceDiscount_CrsLvl] [int] NOT NULL,
[BB08_FlagCourseWthSets] [int] NOT NULL,
[BC09_TotalCourseSalesWthSets] [money] NULL,
[BC10_TotalCourseUnitsWthSets] [int] NULL,
[BC11_TotalCoursePartsWthSets] [dbo].[udtCourseParts] NULL,
[BC12_StdSalePriceCourseWthSets] [money] NULL,
[BC13_PriceDiscount_CrsLvlWthSets] [money] NULL,
[BC14_FlagPriceDiscount_CrsLvlWthSets] [int] NULL,
[BB15_FlagCourseNoSets] [int] NULL,
[BC16_TotalCourseSalesNoSets] [money] NULL,
[BC17_TotalCourseUnitsNoSets] [int] NULL,
[BC18_TotalCoursePartsNoSets] [money] NULL,
[BC19_StdSalePriceCourseNoSets] [money] NULL,
[BC20_PriceDiscount_CrsLvlNoSets] [money] NULL,
[BC21_FlagPriceDiscount_CrsLvlNoSets] [int] NULL,
[CA01_Orders] [int] NULL,
[CA02_NetOrderAmount] [money] NULL,
[CA03_ShippingCharge] [money] NULL,
[CA04_DiscountAmount] [money] NULL,
[CA05_Tax] [money] NULL,
[CA06_TranscriptSales] [money] NULL,
[CB00_FlagHasCoupon] [int] NOT NULL,
[CB01_Cpn_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB02_Cpn_Desc] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB03_Cpn_Code] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB04_Cpn_Campaign] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB05_Cpn_Measure1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB06_Cpn_Amount1] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB07_Cpn_Threshold1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB08_Cpn_ThresholdMeasure1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB09_Cpn_Measure2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CB10_Cpn_Amount2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CC01_TotalDigitalSales] [money] NULL,
[CC02_TotalPhysicalSales] [money] NULL,
[CC03_TotalPhysicalShippingDerived] [money] NULL,
[CC04_TotalShippingDiscount] [money] NULL,
[CC05_FlagShipDiscount_CatCodeDrvn] [tinyint] NULL,
[CD01_YearOrdered] [int] NULL,
[CD02_MonthOrdered] [int] NULL,
[CD03_QuarterOrdered] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD04_WeekOfOrder] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD05_WeekOrderedNum] [int] NULL,
[CD11_PromotionTypeID] [smallint] NULL,
[CD12_PromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD13_MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD14_MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD15_MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD16_MD_PriceType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD17_OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD20_FlagEmailOrder] [tinyint] NULL,
[CD21_SequenceNum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD23_FlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CD24_FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
