CREATE TABLE [Marketing].[MC_TGC_Consumption_MonthlySmry]
(
[CustomerID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDate] [date] NULL,
[TotalPlays] [int] NOT NULL,
[StreamedMins] [numeric] (38, 2) NOT NULL,
[CoursesStreamed] [int] NOT NULL,
[LecturesStreamed] [int] NOT NULL,
[FlagStreamed] [int] NOT NULL,
[TotalPlays_DVD] [int] NOT NULL,
[StreamedMins_DVD] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DVD] [int] NOT NULL,
[LecturesStreamed_DVD] [int] NOT NULL,
[FlagStreamed_DVD] [int] NOT NULL,
[TotalPlays_CD] [int] NOT NULL,
[StreamedMins_CD] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_CD] [int] NOT NULL,
[LecturesStreamed_CD] [int] NOT NULL,
[FlagStreamed_CD] [int] NOT NULL,
[TotalPlays_DownloadV] [int] NOT NULL,
[StreamedMins_DownloadV] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DownloadV] [int] NOT NULL,
[LecturesStreamed_DownloadV] [int] NOT NULL,
[FlagStreamed_DownloadV] [int] NOT NULL,
[TotalPlays_DownloadA] [int] NOT NULL,
[StreamedMins_DownloadA] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DownloadA] [int] NOT NULL,
[LecturesStreamed_DownloadA] [int] NOT NULL,
[FlagStreamed_DownloadA] [int] NOT NULL,
[TotalDnlds] [int] NOT NULL,
[CoursesDnld] [int] NOT NULL,
[LecturesDnld] [int] NOT NULL,
[FlagDnld] [int] NOT NULL,
[TotalDnlds_DownloadV] [int] NOT NULL,
[CoursesDnld_DownloadV] [int] NOT NULL,
[LecturesDnld_DownloadV] [int] NOT NULL,
[FlagDnld_DownloadV] [int] NOT NULL,
[TotalDnlds_DownloadA] [int] NOT NULL,
[CoursesDnld_DownloadA] [int] NOT NULL,
[LecturesDnld_DownloadA] [int] NOT NULL,
[FlagDnld_DownloadA] [int] NOT NULL,
[LecturesStreamed_Bins] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoursesStreamed_Bins] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalPLaysBins] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalMinBins] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
