CREATE TABLE [Marketing].[DMCustomerReActivationStaticNew]
(
[CustomerKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrganizationID] [int] NULL,
[CustomerSinceDateID] [int] NULL,
[CustomerSinceDate] [datetime] NOT NULL,
[ReActivationDateID] [int] NULL,
[ReActivationDate] [datetime] NULL,
[ReActivationOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReActivationAdCode] [int] NULL,
[IntlPurchAmount] [money] NULL,
[IntlSubjectCat] [dbo].[udtSubjectPreference] NULL,
[IntlSubjectPref] [dbo].[udtSubjectPreference] NULL,
[FlagIntlSubjectPrefTied] [tinyint] NULL,
[IntlFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagMediaPrefTied] [tinyint] NULL,
[IntlFormatAVCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlFormatAVPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagFormatAVPrefTied] [tinyint] NULL,
[IntlFormatADCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlFormatADPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagFormatADPrefTied] [tinyint] NULL,
[IntlPromotionTypeID] [smallint] NULL,
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagIntlBackOrder] [tinyint] NULL,
[FirstCouponRedmDate] [datetime] NULL,
[FirstReturnDate] [datetime] NULL,
[FirstEMResponseDate] [datetime] NULL,
[FlagFirstInquirer] [tinyint] NULL,
[FirstInquirerDate] [datetime] NULL,
[FirstBackOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstEMailAddress] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstRegion] [tinyint] NULL,
[FlagEmailable] [tinyint] NULL,
[FlagFirstEMailPref] [tinyint] NULL,
[FlagFirstMailPref] [tinyint] NULL,
[FlagMailable] [tinyint] NULL,
[FirstBuyerType] [tinyint] NULL,
[FlagMailableCollegeBuyer] [tinyint] NULL,
[FlagIntlCouponRedm] [tinyint] NULL,
[FirstCreateDate] [datetime] NULL,
[DMIntlCustomerType] [tinyint] NULL,
[SSCustomerType] [tinyint] NULL,
[RFMFlag] [tinyint] NULL,
[IntlAvgOrderBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlParts] [dbo].[udtCourseParts] NULL,
[IntlPartsBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlNumOfCOurses] [smallint] NULL,
[IntlCoursesBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOfHits] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReliabilityCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFlag] [tinyint] NULL,
[SPPromotionType] [smallint] NULL,
[SPOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPDate] [datetime] NULL,
[SPDateID] [int] NULL,
[SPAdcode] [int] NULL,
[SPFlagCoupon] [tinyint] NULL,
[SPFormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFormatAV] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFormatAD] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSDays] [int] NULL,
[SPAmount] [money] NULL,
[FlagIntlPurchTran] [tinyint] NULL,
[SPFlagTran] [tinyint] NULL,
[SPFlag3Mth] [tinyint] NULL,
[SPFlag6Mth] [tinyint] NULL,
[SPFlag12Mth] [tinyint] NULL,
[SPSubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialPurchaseSubjectPreference2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryPurchaseSubjectPreference2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDRTV] [bit] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DMCustomerReActivationStaticNew] ON [Marketing].[DMCustomerReActivationStaticNew] ([CustomerKey], [CustomerID]) ON [PRIMARY]
GO
