CREATE TABLE [Marketing].[DMDownStreamMonthlyUNITS]
(
[CustomerID] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_CustomerID] DEFAULT ((0)),
[DS1moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS1moSales] DEFAULT ((0)),
[DS2moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS2moSales] DEFAULT ((0)),
[DS3moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS3moSales] DEFAULT ((0)),
[DS4moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS4moSales] DEFAULT ((0)),
[DS5moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS5moSales] DEFAULT ((0)),
[DS6moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS6moSales] DEFAULT ((0)),
[DS7moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS7moSales] DEFAULT ((0)),
[DS8moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS8moSales] DEFAULT ((0)),
[DS9moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS9moSales] DEFAULT ((0)),
[DS10moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS10moSales] DEFAULT ((0)),
[DS11moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS11moSales] DEFAULT ((0)),
[DS12moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS12moSales] DEFAULT ((0)),
[DS24moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS24moSales] DEFAULT ((0)),
[DS36moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS36moSales] DEFAULT ((0)),
[DS48moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS48moSales] DEFAULT ((0)),
[DS60moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS60moSales] DEFAULT ((0)),
[DS72moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS72moSales] DEFAULT ((0)),
[DS84moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS84moSales] DEFAULT ((0)),
[DS96moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS96moSales] DEFAULT ((0)),
[DS108moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS108moSales] DEFAULT ((0)),
[DS120moSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS120moSales] DEFAULT ((0)),
[DS132moSales] [money] NULL,
[DS144moSales] [money] NULL,
[DS156moSales] [money] NULL,
[DS168moSales] [money] NULL,
[DS180moSales] [money] NULL,
[DS1moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS1moOrders] DEFAULT ((0)),
[DS2moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS2moOrders] DEFAULT ((0)),
[DS3moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS3moOrders] DEFAULT ((0)),
[DS4moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS4moOrders] DEFAULT ((0)),
[DS5moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS5moOrders] DEFAULT ((0)),
[DS6moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS6moOrders] DEFAULT ((0)),
[DS7moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS7moOrders] DEFAULT ((0)),
[DS8moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS8moOrders] DEFAULT ((0)),
[DS9moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS9moOrders] DEFAULT ((0)),
[DS10moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS10moOrders] DEFAULT ((0)),
[DS11moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS11moOrders] DEFAULT ((0)),
[DS12moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS12moOrders] DEFAULT ((0)),
[DS24moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS24moOrders] DEFAULT ((0)),
[DS36moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS36moOrders] DEFAULT ((0)),
[DS48moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS48moOrders] DEFAULT ((0)),
[DS60moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS60moOrders] DEFAULT ((0)),
[DS72moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS72moOrders] DEFAULT ((0)),
[DS84moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS84moOrders] DEFAULT ((0)),
[DS96moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS96moOrders] DEFAULT ((0)),
[DS108moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS108moOrders] DEFAULT ((0)),
[DS120moOrders] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS120moOrders] DEFAULT ((0)),
[DS132moOrders] [int] NULL,
[DS144moOrders] [int] NULL,
[DS156moOrders] [int] NULL,
[DS168moOrders] [int] NULL,
[DS180moOrders] [int] NULL,
[DS1moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS1moFlagRepeatByr] DEFAULT ((0)),
[DS2moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS2moFlagRepeatByr] DEFAULT ((0)),
[DS3moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS3moFlagRepeatByr] DEFAULT ((0)),
[DS4moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS4moFlagRepeatByr] DEFAULT ((0)),
[DS5moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS5moFlagRepeatByr] DEFAULT ((0)),
[DS6moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS6moFlagRepeatByr] DEFAULT ((0)),
[DS7moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS7moFlagRepeatByr] DEFAULT ((0)),
[DS8moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS8moFlagRepeatByr] DEFAULT ((0)),
[DS9moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS9moFlagRepeatByr] DEFAULT ((0)),
[DS10moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS10moFlagRepeatByr] DEFAULT ((0)),
[DS11moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS11moFlagRepeatByr] DEFAULT ((0)),
[DS12moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS12moFlagRepeatByr] DEFAULT ((0)),
[DS24moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS24moFlagRepeatByr] DEFAULT ((0)),
[DS36moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS36moFlagRepeatByr] DEFAULT ((0)),
[DS48moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS48moFlagRepeatByr] DEFAULT ((0)),
[DS60moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS60moFlagRepeatByr] DEFAULT ((0)),
[DS72moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS72moFlagRepeatByr] DEFAULT ((0)),
[DS84moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS84moFlagRepeatByr] DEFAULT ((0)),
[DS96moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS96moFlagRepeatByr] DEFAULT ((0)),
[DS108moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS108moFlagRepeatByr] DEFAULT ((0)),
[DS120moFlagRepeatByr] [tinyint] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS120moFlagRepeatByr] DEFAULT ((0)),
[DS132moFlagRepeatByr] [tinyint] NULL,
[DS144moFlagRepeatByr] [tinyint] NULL,
[DS156moFlagRepeatByr] [tinyint] NULL,
[DS168moFlagRepeatByr] [tinyint] NULL,
[DS180moFlagRepeatByr] [tinyint] NULL,
[DS1moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS1moUnits] DEFAULT ((0)),
[DS2moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS2moUnits] DEFAULT ((0)),
[DS3moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS3moUnits] DEFAULT ((0)),
[DS4moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS4moUnits] DEFAULT ((0)),
[DS5moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS5moUnits] DEFAULT ((0)),
[DS6moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS6moUnits] DEFAULT ((0)),
[DS7moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS7moUnits] DEFAULT ((0)),
[DS8moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS8moUnits] DEFAULT ((0)),
[DS9moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS9moUnits] DEFAULT ((0)),
[DS10moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS10moUnits] DEFAULT ((0)),
[DS11moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS11moUnits] DEFAULT ((0)),
[DS12moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS12moUnits] DEFAULT ((0)),
[DS24moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS24moUnits] DEFAULT ((0)),
[DS36moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS36moUnits] DEFAULT ((0)),
[DS48moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS48moUnits] DEFAULT ((0)),
[DS60moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS60moUnits] DEFAULT ((0)),
[DS72moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS72moUnits] DEFAULT ((0)),
[DS84moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS84moUnits] DEFAULT ((0)),
[DS96moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS96moUnits] DEFAULT ((0)),
[DS108moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS108moUnits] DEFAULT ((0)),
[DS120moUnits] [int] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS120moUnits] DEFAULT ((0)),
[DS132moUnits] [int] NOT NULL,
[DS144moUnits] [int] NOT NULL,
[DS156moUnits] [int] NOT NULL,
[DS168moUnits] [int] NOT NULL,
[DS180moUnits] [int] NOT NULL,
[DS1moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS1moParts] DEFAULT ((0)),
[DS2moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS2moParts] DEFAULT ((0)),
[DS3moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS3moParts] DEFAULT ((0)),
[DS4moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS4moParts] DEFAULT ((0)),
[DS5moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS5moParts] DEFAULT ((0)),
[DS6moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS6moParts] DEFAULT ((0)),
[DS7moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS7moParts] DEFAULT ((0)),
[DS8moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS8moParts] DEFAULT ((0)),
[DS9moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS9moParts] DEFAULT ((0)),
[DS10moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS10moParts] DEFAULT ((0)),
[DS11moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS11moParts] DEFAULT ((0)),
[DS12moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS12moParts] DEFAULT ((0)),
[DS24moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS24moParts] DEFAULT ((0)),
[DS36moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS36moParts] DEFAULT ((0)),
[DS48moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS48moParts] DEFAULT ((0)),
[DS60moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS60moParts] DEFAULT ((0)),
[DS72moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS72moParts] DEFAULT ((0)),
[DS84moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS84moParts] DEFAULT ((0)),
[DS96moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS96moParts] DEFAULT ((0)),
[DS108moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS108moParts] DEFAULT ((0)),
[DS120moParts] [float] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS120moParts] DEFAULT ((0)),
[DS132moParts] [float] NOT NULL,
[DS144moParts] [float] NOT NULL,
[DS156moParts] [float] NOT NULL,
[DS168moParts] [float] NOT NULL,
[DS180moParts] [float] NOT NULL,
[DS1moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS1moCourseSales] DEFAULT ((0)),
[DS2moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS2moCourseSales] DEFAULT ((0)),
[DS3moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS3moCourseSales] DEFAULT ((0)),
[DS4moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS4moCourseSales] DEFAULT ((0)),
[DS5moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS5moCourseSales] DEFAULT ((0)),
[DS6moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS6moCourseSales] DEFAULT ((0)),
[DS7moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS7moCourseSales] DEFAULT ((0)),
[DS8moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS8moCourseSales] DEFAULT ((0)),
[DS9moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS9moCourseSales] DEFAULT ((0)),
[DS10moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS10moCourseSales] DEFAULT ((0)),
[DS11moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS11moCourseSales] DEFAULT ((0)),
[DS12moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS12moCourseSales] DEFAULT ((0)),
[DS24moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS24moCourseSales] DEFAULT ((0)),
[DS36moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS36moCourseSales] DEFAULT ((0)),
[DS48moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS48moCourseSales] DEFAULT ((0)),
[DS60moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS60moCourseSales] DEFAULT ((0)),
[DS72moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS72moCourseSales] DEFAULT ((0)),
[DS84moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS84moCourseSales] DEFAULT ((0)),
[DS96moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS96moCourseSales] DEFAULT ((0)),
[DS108moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS108moCourseSales] DEFAULT ((0)),
[DS120moCourseSales] [money] NOT NULL CONSTRAINT [DF_DMDownStreamMonthlyUNITS_DS120moCourseSales] DEFAULT ((0)),
[DS132moCourseSales] [money] NOT NULL,
[DS144moCourseSales] [money] NOT NULL,
[DS156moCourseSales] [money] NOT NULL,
[DS168moCourseSales] [money] NOT NULL,
[DS180moCourseSales] [money] NOT NULL,
[DS18moSales] [money] NOT NULL,
[DS18moOrders] [int] NOT NULL,
[DS18moFlagRepeatByr] [tinyint] NOT NULL,
[DS18moUnits] [int] NOT NULL,
[DS18moParts] [float] NOT NULL,
[DS18moCourseSales] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [Marketing].[DMDownStreamMonthlyUNITS] ADD CONSTRAINT [PK_DMDownStreamMonthlyUNITS] PRIMARY KEY CLUSTERED  ([CustomerID]) ON [PRIMARY]
GO
