CREATE TABLE [Marketing].[StreamingReport]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOrdered] [datetime] NULL,
[OrderYear] [int] NULL,
[OrderMonth] [int] NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mf] [int] NULL,
[Age] [int] NULL,
[Gender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetOrderAmount] [money] NULL,
[OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format_DVD] [int] NULL,
[Format_CD] [int] NULL,
[Format_VDL] [int] NULL,
[Format_ADL] [int] NULL,
[Subject_AH] [int] NULL,
[Subject_EC] [int] NULL,
[Subject_FA] [int] NULL,
[Subject_BL] [int] NULL,
[Subject_LIT] [int] NULL,
[Subject_MH] [int] NULL,
[Subject_PH] [int] NULL,
[Subject_PR] [int] NULL,
[Subject_RL] [int] NULL,
[Subject_SCI] [int] NULL,
[Subject_MTH] [int] NULL,
[TotalUnitsPurchased] [int] NULL,
[VideoMinutesPurchased] [int] NULL,
[AudioMinutesPurchased] [int] NULL,
[TotalMinutesPurchased] [int] NULL,
[NextPurchaseOrderDate] [smalldatetime] NULL,
[NextPurchaseYear] [int] NULL,
[NextPurchaseMonth] [int] NULL,
[NextPurchaseOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextPurchaseOrderAmount] [money] NULL,
[NextPurchaseOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysBetweenOrders] [int] NULL,
[DaysBetweenOrdersBin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next_AH] [int] NULL,
[Next_EC] [int] NULL,
[Next_FA] [int] NULL,
[Next_BL] [int] NULL,
[Next_LIT] [int] NULL,
[Next_MH] [int] NULL,
[Next_PH] [int] NULL,
[Next_PR] [int] NULL,
[Next_RL] [int] NULL,
[Next_SCI] [int] NULL,
[Next_MTH] [int] NULL,
[NextOrderDigitalPhysical] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextOrderAudioVideo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastPlatform_Web] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastPlatform_iOS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastPlatform_Android] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastDevice_Desktop] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastDevice_Mobile] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastDevice_Tablet] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastDevice_Others] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredPlatform] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredDevice] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysSinceLastVStreamed] [int] NULL,
[DaysSinceLastAStreamed] [int] NULL,
[DaysSinceLastStreamed] [int] NULL,
[DS01Mo_VStreamMinutes] [int] NULL,
[DS01Mo_AStreamMinutes] [int] NULL,
[DS01Mo_TotStreamMinutes] [int] NULL,
[DS03Mo_VStreamMinutes] [int] NULL,
[DS03Mo_AStreamMinutes] [int] NULL,
[DS03Mo_TotStreamMinutes] [int] NULL,
[DS06Mo_VStreamMinutes] [int] NULL,
[DS06Mo_AStreamMinutes] [int] NULL,
[DS06Mo_TotStreamMinutes] [int] NULL,
[DS09Mo_VStreamMinutes] [int] NULL,
[DS09Mo_AStreamMinutes] [int] NULL,
[DS09Mo_TotStreamMinutes] [int] NULL,
[DS12Mo_VStreamMinutes] [int] NULL,
[DS12Mo_AStreamMinutes] [int] NULL,
[DS12Mo_TotStreamMinutes] [int] NULL,
[DS01Mo_VStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_AStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_TotStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_VStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_AStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_TotStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_VStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_AStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_TotStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_VStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_AStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_TotStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_VStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_AStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_TotStreamBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_PurchaseFlag] [int] NULL,
[DS03Mo_PurchaseFlag] [int] NULL,
[DS06Mo_PurchaseFlag] [int] NULL,
[DS09Mo_PurchaseFlag] [int] NULL,
[DS12Mo_PurchaseFlag] [int] NULL,
[TotalUnitsPurchasedBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OmniCustFlag] [int] NULL,
[DS1Mo_Sales] [money] NULL,
[DS1Mo_Orders] [int] NULL,
[DS3Mo_Sales] [money] NULL,
[DS3Mo_Orders] [int] NULL,
[DS6Mo_Sales] [money] NULL,
[DS6Mo_Orders] [int] NULL,
[DS9Mo_Sales] [money] NULL,
[DS9Mo_Orders] [int] NULL,
[DS12Mo_Sales] [money] NULL,
[DS12Mo_Orders] [int] NULL
) ON [PRIMARY]
GO
