CREATE TABLE [Marketing].[QuarterlyTrackerResults]
(
[QTID] [int] NOT NULL IDENTITY(1, 1),
[SubmitDateTime] [datetime] NOT NULL,
[SubmitDate] [date] NOT NULL,
[EmailAddress] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerID] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSource] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENSAT_VALUE] [int] NULL,
[RPLIKELI_VALUE] [int] NULL,
[LIKELIRECOMM_VALUE] [int] NULL,
[CUSTEFFORT_VALUE] [int] NULL,
[COURSENAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIATYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREAMCOURSE] [int] NULL,
[DLEXPERIENCE] [int] NULL,
[Streamingexperience] [int] NULL,
[COURSESAT] [int] NULL,
[Learn_New_or_Valuable_Value] [int] NULL,
[VISUALSAT_VALUE] [int] NULL,
[PROFPRESENTSAT_VALUE] [int] NULL,
[COURSE_PRICE_VALUE] [int] NULL,
[ACSI_IDEAL_COURSE] [int] NULL,
[COURSESELECTSAT_VALUE] [int] NULL,
[ACSI_EXPECTATIONS] [int] NULL,
[BACKLOG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BACKLOG_NUMBER] [int] NULL,
[MAJORPROBLEMS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTED_CSR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROBLEM_RESOLVED] [int] NULL,
[CATSAT_VALUE] [int] NULL,
[EMAIL_FREQ_VALUE] [int] NULL,
[CAT_FREQ_VALUE] [int] NULL,
[GUIDEBOOKSAT_VALUE] [int] NULL,
[WEBSITE_EASENAV_VALUE] [int] NULL,
[WEBSITE_LAYOUT] [int] NULL,
[WEBSITE_ACCURACY] [int] NULL,
[ANDROIDSAT] [int] NULL,
[IPADSAT] [int] NULL,
[IPHONESAT] [int] NULL,
[TORCHSAT] [int] NULL,
[ROKUSAT] [int] NULL,
[Employment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackerYear] [int] NULL,
[TrackerQrtr] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackerQrtrYr] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Updated_Date] [datetime] NOT NULL CONSTRAINT [DF_TGCTracker_UpdateDate] DEFAULT (getdate()),
[CourseID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [Marketing].[QuarterlyTrackerResults] ADD CONSTRAINT [PK_QTID] PRIMARY KEY CLUSTERED  ([QTID]) ON [PRIMARY]
GO
ALTER TABLE [Marketing].[QuarterlyTrackerResults] ADD CONSTRAINT [UC_tgc_QTrackerPollRslt] UNIQUE NONCLUSTERED  ([SubmitDate], [EmailAddress]) ON [PRIMARY]
GO
