CREATE TABLE [Marketing].[OrdAllctn_WeeklySummary]
(
[FromDate] [datetime] NULL,
[ToDate] [datetime] NULL,
[ForecastWeek] [datetime] NULL,
[YearOrdered] [int] NULL,
[MonthOrdered] [int] NULL,
[WeekOfOrder] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagCountry] [int] NOT NULL,
[FlagUnsourcedOrder] [int] NOT NULL,
[AdCode] [int] NULL,
[AdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode] [int] NULL,
[CatalogName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CountryID] [int] NULL,
[MD_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_AudienceID] [int] NULL,
[MD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelID] [int] NULL,
[MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PromotionTypeID] [int] NULL,
[MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CampaignID] [int] NULL,
[MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Year] [int] NULL,
[MD_PriceTypeID] [int] NULL,
[MD_PriceType] [varchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_CountryID] [int] NULL,
[Asn_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_AudienceID] [int] NULL,
[Asn_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_ChannelID] [int] NULL,
[Asn_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_PromotionTypeID] [int] NULL,
[Asn_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_CampaignID] [int] NULL,
[Asn_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_Year] [int] NULL,
[Asn_PriceTypeID] [int] NULL,
[Asn_PriceType] [varchar] (81) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asn_CatalogCode] [int] NULL,
[Asn_CatalogName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssignedCode] [int] NULL,
[AssignedName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssignReason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagNewCustomer] [int] NOT NULL,
[BillingCountryCode] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyCode] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExchangeRate] [numeric] (5, 4) NOT NULL,
[Orders] [int] NULL,
[Sales] [money] NULL,
[CD_Sales] [money] NULL,
[CD_Parts] [money] NULL,
[DVD_Sales] [money] NULL,
[DVD_Parts] [money] NULL,
[DownloadA_Sales] [money] NULL,
[DownloadA_Parts] [money] NULL,
[DownloadV_Sales] [money] NULL,
[DownloadV_Parts] [money] NULL,
[Transcript_Sales] [money] NULL,
[Transcript_Parts] [money] NULL,
[SalesDollars] [money] NULL,
[Tax] [money] NULL,
[TaxDollars] [money] NULL,
[CD_SalesDollars] [money] NULL,
[DVD_SalesDollars] [money] NULL,
[DownloadA_SalesDollars] [money] NULL,
[DownloadV_SalesDollars] [money] NULL,
[Transcript_SalesDollars] [money] NULL
) ON [PRIMARY]
GO
