CREATE TABLE [Marketing].[CustCohort_MonthlySpending_Smry]
(
[AsOfDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AsOfYear] [int] NOT NULL,
[AsOfMonth] [int] NOT NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12mf] [int] NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFrcst] [varchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagPurchThisYr] [tinyint] NULL,
[PurchAmountThisYr] [money] NULL,
[PurchasesThisYr] [int] NULL,
[FlagPurchJAN] [tinyint] NULL,
[PurchAmountJAN] [money] NULL,
[PurchasesJAN] [int] NULL,
[FlagPurchFEB] [tinyint] NULL,
[PurchAmountFEB] [money] NULL,
[PurchasesFEB] [int] NULL,
[FlagPurchMAR] [tinyint] NULL,
[PurchAmountMAR] [money] NULL,
[PurchasesMAR] [int] NULL,
[FlagPurchAPR] [tinyint] NULL,
[PurchAmountAPR] [money] NULL,
[PurchasesAPR] [int] NULL,
[FlagPurchMAY] [tinyint] NULL,
[PurchAmountMAY] [money] NULL,
[PurchasesMAY] [int] NULL,
[FlagPurchJUN] [tinyint] NULL,
[PurchAmountJUN] [money] NULL,
[PurchasesJUN] [int] NULL,
[FlagPurchJUL] [tinyint] NULL,
[PurchAmountJUL] [money] NULL,
[PurchasesJUL] [int] NULL,
[FlagPurchAUG] [tinyint] NULL,
[PurchAmountAUG] [money] NULL,
[PurchasesAUG] [int] NULL,
[FlagPurchSEP] [tinyint] NULL,
[PurchAmountSEP] [money] NULL,
[PurchasesSEP] [int] NULL,
[FlagPurchOCT] [tinyint] NULL,
[PurchAmountOCT] [money] NULL,
[PurchasesOCT] [int] NULL,
[FlagPurchNOV] [tinyint] NULL,
[PurchAmountNOV] [money] NULL,
[PurchasesNOV] [int] NULL,
[FlagPurchDEC] [tinyint] NULL,
[PurchAmountDEC] [money] NULL,
[PurchasesDEC] [int] NULL,
[FlagPurchPrYr] [tinyint] NULL,
[PurchAmountPrYr] [money] NULL,
[PurchasesPrYr] [int] NULL,
[FlagPurchPrYrJAN] [tinyint] NULL,
[PurchAmountPrYrJAN] [money] NULL,
[PurchasesPrYrJAN] [int] NULL,
[FlagPurchPrYrFEB] [tinyint] NULL,
[PurchAmountPrYrFEB] [money] NULL,
[PurchasesPrYrFEB] [int] NULL,
[FlagPurchPrYrMAR] [tinyint] NULL,
[PurchAmountPrYrMAR] [money] NULL,
[PurchasesPrYrMAR] [int] NULL,
[FlagPurchPrYrAPR] [tinyint] NULL,
[PurchAmountPrYrAPR] [money] NULL,
[PurchasesPrYrAPR] [int] NULL,
[FlagPurchPrYrMAY] [tinyint] NULL,
[PurchAmountPrYrMAY] [money] NULL,
[PurchasesPrYrMAY] [int] NULL,
[FlagPurchPrYrJUN] [tinyint] NULL,
[PurchAmountPrYrJUN] [money] NULL,
[PurchasesPrYrJUN] [int] NULL,
[FlagPurchPrYrJUL] [tinyint] NULL,
[PurchAmountPrYrJUL] [money] NULL,
[PurchasesPrYrJUL] [int] NULL,
[FlagPurchPrYrAUG] [tinyint] NULL,
[PurchAmountPrYrAUG] [money] NULL,
[PurchasesPrYrAUG] [int] NULL,
[FlagPurchPrYrSEP] [tinyint] NULL,
[PurchAmountPrYrSEP] [money] NULL,
[PurchasesPrYrSEP] [int] NULL,
[FlagPurchPrYrOCT] [tinyint] NULL,
[PurchAmountPrYrOCT] [money] NULL,
[PurchasesPrYrOCT] [int] NULL,
[FlagPurchPrYrNOV] [tinyint] NULL,
[PurchAmountPrYrNOV] [money] NULL,
[PurchasesPrYrNOV] [int] NULL,
[FlagPurchPrYrDEC] [tinyint] NULL,
[PurchAmountPrYrDEC] [money] NULL,
[PurchasesPrYrDEC] [int] NULL,
[CustCount] [int] NULL
) ON [PRIMARY]
GO
