CREATE TABLE [Marketing].[DownloadReport_20150101to20151231]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDateOrdered] [date] NULL,
[FirstOrderYear] [int] NULL,
[FirstOrderMonth] [int] NULL,
[CustomerSegmentFnlPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrequencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewsegPrior] [int] NULL,
[NamePrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mfPrior] [int] NULL,
[AgeBin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Gender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format_VDLOnly] [int] NOT NULL,
[Format_ADLOnly] [int] NOT NULL,
[Format_Both] [int] NOT NULL,
[Subject_AH] [int] NOT NULL,
[Subject_EC] [int] NOT NULL,
[Subject_FA] [int] NOT NULL,
[Subject_BL] [int] NOT NULL,
[Subject_LIT] [int] NOT NULL,
[Subject_MH] [int] NOT NULL,
[Subject_PH] [int] NOT NULL,
[Subject_PR] [int] NOT NULL,
[Subject_RL] [int] NOT NULL,
[Subject_SCI] [int] NOT NULL,
[Subject_MTH] [int] NOT NULL,
[TotalAmtPurchased] [money] NULL,
[TotalUnitsPurchased] [int] NULL,
[TotalLecturePurchased] [int] NULL,
[TotalMinutesPurchased] [int] NULL,
[TotalDLUnitsPurchasedBin] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_PurchaseFlag] [int] NULL,
[DS02Mo_PurchaseFlag] [int] NULL,
[DS03Mo_PurchaseFlag] [int] NULL,
[DS01Mo_Sales] [money] NULL,
[DS02Mo_Sales] [money] NULL,
[DS03Mo_Sales] [money] NULL,
[DS01Mo_Orders] [int] NULL,
[DS02Mo_Orders] [int] NULL,
[DS03Mo_Orders] [int] NULL,
[DS01Mo_Units] [int] NULL,
[DS02Mo_Units] [int] NULL,
[DS03Mo_Units] [int] NULL,
[DS01Mo_Parts] [int] NULL,
[DS02Mo_Parts] [int] NULL,
[DS03Mo_Parts] [int] NULL,
[DS01Mo_StreamMinutes] [int] NULL,
[DS02Mo_StreamMinutes] [int] NULL,
[DS03Mo_StreamMinutes] [int] NULL,
[DS01Mo_StreamLectures] [int] NULL,
[DS02Mo_StreamLectures] [int] NULL,
[DS03Mo_StreamLectures] [int] NULL,
[DS01Mo_DLLectures] [int] NULL,
[DS02Mo_DLLectures] [int] NULL,
[DS03Mo_DLLectures] [int] NULL,
[DS01Mo_StreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS02Mo_StreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_StreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_StreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS02Mo_StreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_StreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_DLLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS02Mo_DLLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_DLLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_Action] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS02Mo_Action] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_Action] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Platform_Web] [int] NULL,
[Platform_iOSApp] [int] NULL,
[Platform_AndroidApp] [int] NULL,
[Platform_Others] [int] NULL,
[Device_Desktop] [int] NULL,
[Device_Mobile] [int] NULL,
[Device_Tablet] [int] NULL,
[Device_Others] [int] NULL,
[PreferredPlatform] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredDevice] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
