CREATE TABLE [Marketing].[SQ_FinalSquinchedSummary]
(
[PA_Adcode] [int] NULL,
[PA_CourseID] [int] NULL,
[PA_SetFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SetID] [int] NULL,
[PA_Section] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SubCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Parts] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Lectures] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_MinPerLctr] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PageSize] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PageStart] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PriceMatrix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_Currency] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DV] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DAFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PTFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_PT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DTFull] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_DVDOmni] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_CDOmni] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PA_SoundTrack] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_AdCode] [int] NULL,
[SQ_Year] [int] NULL,
[SQ_Season] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_Catalog] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_Spread] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_Page] [float] NULL,
[SQ_SKU] [int] NULL,
[SQ_NSSqIn] [float] NULL,
[SQ_ZoneSqIn] [float] NULL,
[SQ_AddonSqIn] [float] NULL,
[SQ_PageNSSqIn] [float] NULL,
[SQ_TotalSqIn] [float] NULL,
[SQ_TotalNSPerSKU] [float] NULL,
[SQ_TotalSellPerSKU] [float] NULL,
[SQ_FreeStreaming] [bit] NULL,
[SQ_NewRelease] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_PageLocation] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_LectureTitles] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_NumImagesShown] [float] NULL,
[SQ_ImageSqIn] [float] NULL,
[SQ_ImageLoc] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_RedCircleMessage] [bit] NULL,
[SQ_PartnerLogo_Msg] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQ_HolidayMessage] [bit] NULL,
[SQ_Set_Flag] [bit] NULL,
[SQ_Set_SKU] [int] NULL,
[SQ_Set_SqIn] [float] NULL,
[CRS_CourseID] [int] NULL,
[CRS_CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_AbbrvCourseName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_CourseParts] [money] NULL,
[CRS_CourseHours] [money] NULL,
[CRS_ReleaseDate] [datetime] NULL,
[CRS_SubjectCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_SubjectCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_SubjectCategoryID] [int] NULL,
[CRS_PCASubjectCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_BundleFlag] [tinyint] NULL,
[CRS_PreReleaseCoursePref] [float] NULL,
[CRS_PostReleaseCourseSat] [float] NULL,
[CRS_CSATAsOfDate] [datetime] NULL,
[CRS_FlagActive] [tinyint] NULL,
[CRS_TerminationDate] [smalldatetime] NULL,
[CRS_PreReleaseSubjectMultiplier] [float] NULL,
[CRS_PrefPoint] [float] NULL,
[CRS_PDSubjectCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_TotalPaidImages] [int] NULL,
[CRS_CostPaidImages] [money] NULL,
[CRS_TotalFreeImages] [int] NULL,
[CRS_Topic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_SubTopic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_FlagAudioDL] [tinyint] NULL,
[CRS_FlagVideoDL] [tinyint] NULL,
[CRS_VideoDL_ReleaseDate] [datetime] NULL,
[CRS_FlagCD] [tinyint] NULL,
[CRS_FlagDVD] [tinyint] NULL,
[CRS_FlagAudioDLOnly] [tinyint] NULL,
[CRS_FlagBuffetSet] [bit] NULL,
[CRS_FlagCLRCourse] [tinyint] NULL,
[CRS_DateCLRCourseAdded] [date] NULL,
[CRS_DateCLRCourseRemoved] [date] NULL,
[CRS_HowToFlag] [tinyint] NULL,
[CRS_NonCoreFlag] [tinyint] NULL,
[CMP_AdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_MD_AudienceID] [int] NULL,
[CMP_MD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_MD_Year] [int] NULL,
[CMP_MD_PriceType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_MD_ChannelID] [int] NULL,
[CMP_MD_ChannelName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_MD_PromotionTypeID] [int] NULL,
[CMP_MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_MD_CampaignID] [int] NULL,
[CMP_MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_MD_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMP_StartDate] [datetime] NULL,
[CMP_StopDate] [datetime] NULL,
[CMP_PromotionTypeID] [smallint] NULL,
[CMP_PromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total_Course_Sales] [money] NOT NULL,
[Total_Course_Units] [int] NOT NULL,
[Overall_TotalMailed] [int] NOT NULL,
[Overall_Orders] [int] NOT NULL,
[Overall_Sales] [money] NOT NULL
) ON [PRIMARY]
GO
