CREATE TABLE [Marketing].[FBToplineReport]
(
[ReportingStarts] [date] NULL,
[ReportingEnds] [date] NULL,
[WeekReportingStarts] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonthReportingStarts] [int] NULL,
[YearReportingStarts] [int] NULL,
[Campaign] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adset] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ad] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adcode] [float] NULL,
[DateOrdered] [date] NULL,
[IPR_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Audience] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CampaignID] [int] NULL,
[MD_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Year] [int] NULL,
[MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CampaignName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PriceType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PromotionType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PromotionTypeID] [int] NULL,
[MD_ChannelID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode] [int] NULL,
[CatalogName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdcodeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WeekOrdered] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonthOrdered] [int] NULL,
[YearOrdered] [int] NULL,
[Impressions] [float] NOT NULL,
[Reach] [int] NOT NULL,
[Clicks] [float] NOT NULL,
[UniqueClicks] [float] NOT NULL,
[Actions] [float] NOT NULL,
[AmountSpent] [float] NOT NULL,
[Revenue_FB] [float] NOT NULL,
[Revenue_FB_1d] [float] NOT NULL,
[Orders_FB] [float] NOT NULL,
[Order_FB_1d] [float] NOT NULL,
[TotalSales] [money] NOT NULL,
[TotalOrders] [int] NOT NULL,
[TotalUnits] [int] NOT NULL,
[TotalSalesNew] [money] NOT NULL,
[TotalOrdersNew] [int] NOT NULL,
[TotalUnitsNew] [int] NOT NULL,
[PhysicalUnits] [int] NOT NULL,
[PhysicalSales] [money] NOT NULL,
[DigitalUnits] [int] NOT NULL,
[DigitalSales] [money] NOT NULL,
[DigitalSalesNew] [money] NOT NULL,
[DigitalUnitsNew] [int] NOT NULL,
[DVDUnits] [int] NOT NULL,
[DVDSales] [money] NOT NULL,
[CDUnits] [int] NOT NULL,
[CDSales] [money] NOT NULL,
[VideoDLUnits] [int] NOT NULL,
[VideoDLSales] [money] NOT NULL,
[AudioDLUnits] [int] NOT NULL,
[AudioDLSales] [money] NOT NULL,
[TranscriptUnits] [int] NOT NULL,
[TranscriptSales] [money] NOT NULL,
[DigitalTranscriptUnits] [int] NOT NULL,
[DigitalTranscriptSales] [money] NOT NULL,
[ShippingCharge] [money] NOT NULL,
[TotalTaxes] [money] NOT NULL,
[DiscountAmount] [money] NOT NULL,
[TotalMerchandizeSales] [money] NOT NULL,
[TotalMerchandizeUnits] [int] NOT NULL,
[TotalMerchandizeParts] [money] NOT NULL,
[Adj_CDSales] [money] NOT NULL,
[Adj_DVDSales] [money] NOT NULL,
[Adj_AudioTapeSales] [money] NOT NULL,
[Adj_VHSSales] [money] NOT NULL,
[Adj_AudioDLSales] [money] NOT NULL,
[Adj_VideoDLSales] [money] NOT NULL,
[Adj_TranscriptSales] [money] NOT NULL,
[Adj_DigitalTranscriptSales] [money] NOT NULL,
[Adj_DigitalSales] [money] NOT NULL,
[Adj_PhysicalSales] [money] NOT NULL,
[Adj_TotalMerchandizeSales] [money] NOT NULL,
[ReportDate] [datetime] NOT NULL
) ON [PRIMARY]
GO
