CREATE TABLE [Marketing].[TTCStats_TN_DigitalAnalysis_20180405]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AsOfDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearOfLastPurchase] [int] NULL,
[YearOfLastPurchBin_TN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearOfLastPurchID_TN] [int] NOT NULL,
[OrigPurchDate] [datetime] NULL,
[YearOfOrigPurchase] [int] NULL,
[YearOfOrigPurchBin_TN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearOfOrigPurchID_TN] [int] NOT NULL,
[FirstFlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryOfFirstPurch] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryOfFirstPurchID_TN] [int] NULL,
[FirstOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderID_TN] [int] NOT NULL,
[Agebin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[AgeBin_TN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AgeBinID_TN] [int] NOT NULL,
[PhysicalSales_LTD] [money] NULL,
[DigitalSales_LTD] [money] NULL,
[PhysicalUnits_LTD] [int] NULL,
[DigitalUnits_LTD] [int] NULL,
[PhysicalSales_LTD_USD] [money] NULL,
[DigitalSales_LTD_USD] [money] NULL,
[PhysicalSales_LTD_AUD] [money] NULL,
[DigitalSales_LTD_AUD] [money] NULL,
[PhysicalSales_LTD_GBP] [money] NULL,
[DigitalSales_LTD_GBP] [money] NULL,
[PhysicalUnits_LTD_USD] [int] NULL,
[DigitalUnits_LTD_USD] [int] NULL,
[PhysicalUnits_LTD_AUD] [int] NULL,
[DigitalUnits_LTD_AUD] [int] NULL,
[PhysicalUnits_LTD_GBP] [int] NULL,
[DigitalUnits_LTD_GBP] [int] NULL,
[PhysicalSales_2017] [money] NULL,
[DigitalSales_2017] [money] NULL,
[PhysicalUnits_2017] [int] NULL,
[DigitalUnits_2017] [int] NULL,
[PhysicalSales_2017_USD] [money] NULL,
[DigitalSales_2017_USD] [money] NULL,
[PhysicalUnits_2017_USD] [int] NULL,
[DigitalUnits_2017_USD] [int] NULL,
[PhysicalSales_2017_AUD] [money] NULL,
[DigitalSales_2017_AUD] [money] NULL,
[PhysicalUnits_2017_AUD] [int] NULL,
[DigitalUnits_2017_AUD] [int] NULL,
[PhysicalSales_2017_GBP] [money] NULL,
[DigitalSales_2017_GBP] [money] NULL,
[PhysicalUnits_2017_GBP] [int] NULL,
[DigitalUnits_2017_GBP] [int] NULL,
[PhysicalSales_Last12M] [money] NULL,
[DigitalSales_Last12M] [money] NULL,
[PhysicalUnits_Last12M] [int] NULL,
[DigitalUnits_Last12M] [int] NULL,
[PhysicalSales_Last12M_USD] [money] NULL,
[DigitalSales_Last12M_USD] [money] NULL,
[PhysicalUnits_Last12M_USD] [int] NULL,
[DigitalUnits_Last12M_USD] [int] NULL,
[PhysicalSales_Last12M_AUD] [money] NULL,
[DigitalSales_Last12M_AUD] [money] NULL,
[PhysicalUnits_Last12M_AUD] [int] NULL,
[DigitalUnits_Last12M_AUD] [int] NULL,
[PhysicalSales_Last12M_GBP] [money] NULL,
[DigitalSales_Last12M_GBP] [money] NULL,
[PhysicalUnits_Last12M_GBP] [int] NULL,
[DigitalUnits_Last12M_GBP] [int] NULL,
[FlagDigital_LTD] [int] NOT NULL,
[FlagPhysical_LTD] [int] NOT NULL,
[FlagDigital_2017] [int] NOT NULL,
[FlagPhysical_2017] [int] NOT NULL,
[FlagDigital_Last12M] [int] NOT NULL,
[FlagPhysical_Last12M] [int] NOT NULL,
[DigitalFreqOfPurch_LTD] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DigitalFreqOfPurchID_LTD] [int] NULL,
[PhysicalFreqOfPurch_LTD] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhysicalFreqOfPurchID_LTD] [int] NULL,
[NumDigitalOrders_LTD] [int] NULL,
[NumPhysicalOrders_LTD] [int] NULL,
[NumDigitalOrders_LTD_USD] [int] NULL,
[NumPhysicalOrders_LTD_USD] [int] NULL,
[NumDigitalOrders_LTD_AUD] [int] NULL,
[NumPhysicalOrders_LTD_AUD] [int] NULL,
[NumDigitalOrders_LTD_GBP] [int] NULL,
[NumPhysicalOrders_LTD_GBP] [int] NULL,
[FlagPlusCustomer] [int] NOT NULL,
[Plus_CustomerID] [bigint] NULL,
[Plus_CustStatusFlag] [float] NULL,
[Plus_TransactionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus_SubType_TN] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Plus_SubTypeID_TN] [int] NOT NULL,
[Plus_PaidFlag] [int] NULL,
[Plus_IntlSubDate] [date] NULL,
[Plus_IntlSubPaymentHandler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus_IntlSubType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus_SubDate] [date] NULL,
[Plus_SubPaymentHandler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus_SubType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plus_SubDllrs_LTD] [money] NULL,
[Plus_SubPaidDllrs_LTD] [money] NULL,
[Plus_EntitledMonths_LTD] [int] NULL,
[Plus_PaidMonths_LTD] [int] NULL,
[Plus_SubPaidDllrs_Rem] [money] NULL,
[Plus_EntitledMonths_Rem] [int] NULL,
[Plus_EntitledMonths_2017] [int] NULL,
[Plus_PaidMonths_2017] [int] NULL,
[Plus_SubDllrs_2017] [money] NULL,
[Plus_SubPaidDllrs_2017] [money] NULL
) ON [PRIMARY]
GO
