CREATE TABLE [Marketing].[StreamingReport_Q12015toQ12016]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateOrdered] [date] NULL,
[OrderYear] [int] NULL,
[OrderMonth] [int] NULL,
[CustomerSegmentFnlPrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrequencyPrior] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewsegPrior] [int] NULL,
[NamePrior] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mfPrior] [int] NULL,
[Age] [int] NULL,
[Gender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetOrderAmount] [money] NULL,
[OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format_DVD] [int] NULL,
[Format_CD] [int] NULL,
[Format_VDL] [int] NULL,
[Format_ADL] [int] NULL,
[Subject_AH] [int] NULL,
[Subject_EC] [int] NULL,
[Subject_FA] [int] NULL,
[Subject_BL] [int] NULL,
[Subject_LIT] [int] NULL,
[Subject_MH] [int] NULL,
[Subject_PH] [int] NULL,
[Subject_PR] [int] NULL,
[Subject_RL] [int] NULL,
[Subject_SCI] [int] NULL,
[Subject_MTH] [int] NULL,
[TotalUnitsPurchased] [int] NULL,
[TotalLecturePurchased] [int] NULL,
[VideoMinutesPurchased] [int] NULL,
[AudioMinutesPurchased] [int] NULL,
[TotalMinutesPurchased] [int] NULL,
[TotalUnitsPurchasedBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_PurchaseFlag] [int] NULL,
[DS03Mo_PurchaseFlag] [int] NULL,
[DS06Mo_PurchaseFlag] [int] NULL,
[DS09Mo_PurchaseFlag] [int] NULL,
[DS12Mo_PurchaseFlag] [int] NULL,
[DS01Mo_Sales] [money] NULL,
[DS03Mo_Sales] [money] NULL,
[DS06Mo_Sales] [money] NULL,
[DS09Mo_Sales] [money] NULL,
[DS12Mo_Sales] [money] NULL,
[DS01Mo_Orders] [int] NULL,
[DS03Mo_Orders] [int] NULL,
[DS06Mo_Orders] [int] NULL,
[DS09Mo_Orders] [int] NULL,
[DS12Mo_Orders] [int] NULL,
[DS01Mo_VStreamMinutes] [int] NULL,
[DS01Mo_AStreamMinutes] [int] NULL,
[DS01Mo_TotStreamMinutes] [int] NULL,
[DS03Mo_VStreamMinutes] [int] NULL,
[DS03Mo_AStreamMinutes] [int] NULL,
[DS03Mo_TotStreamMinutes] [int] NULL,
[DS06Mo_VStreamMinutes] [int] NULL,
[DS06Mo_AStreamMinutes] [int] NULL,
[DS06Mo_TotStreamMinutes] [int] NULL,
[DS09Mo_VStreamMinutes] [int] NULL,
[DS09Mo_AStreamMinutes] [int] NULL,
[DS09Mo_TotStreamMinutes] [int] NULL,
[DS12Mo_VStreamMinutes] [int] NULL,
[DS12Mo_AStreamMinutes] [int] NULL,
[DS12Mo_TotStreamMinutes] [int] NULL,
[DS01Mo_VStreamLectures] [int] NULL,
[DS01Mo_AStreamLectures] [int] NULL,
[DS01Mo_TotStreamLectures] [int] NULL,
[DS03Mo_VStreamLectures] [int] NULL,
[DS03Mo_AStreamLectures] [int] NULL,
[DS03Mo_TotStreamLectures] [int] NULL,
[DS06Mo_VStreamLectures] [int] NULL,
[DS06Mo_AStreamLectures] [int] NULL,
[DS06Mo_TotStreamLectures] [int] NULL,
[DS09Mo_VStreamLectures] [int] NULL,
[DS09Mo_AStreamLectures] [int] NULL,
[DS09Mo_TotStreamLectures] [int] NULL,
[DS12Mo_VStreamLectures] [int] NULL,
[DS12Mo_AStreamLectures] [int] NULL,
[DS12Mo_TotStreamLectures] [int] NULL,
[DS01Mo_VStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_AStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_TotStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_VStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_AStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_TotStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_VStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_AStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_TotStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_VStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_AStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_TotStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_VStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_AStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_TotStreamMinuteBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_VStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_AStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS01Mo_TotStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_VStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_AStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS03Mo_TotStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_VStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_AStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS06Mo_TotStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_VStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_AStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS09Mo_TotStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_VStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_AStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS12Mo_TotStreamLectBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Platform_Web] [int] NULL,
[Platform_iOSApp] [int] NULL,
[Platform_AndroidApp] [int] NULL,
[Platform_Others] [int] NULL,
[Device_Desktop] [int] NULL,
[Device_Mobile] [int] NULL,
[Device_Tablet] [int] NULL,
[Device_Others] [int] NULL,
[PreferredPlatform] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredDevice] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
