CREATE TABLE [Marketing].[DMCustomerStatic_DS5moITEMS]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlPurchaseOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlSubjectCat] [dbo].[udtSubjectPreference] NOT NULL,
[IntlSubjectPref] [dbo].[udtSubjectPreference] NOT NULL,
[IntlFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlFormatAVCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlFormatAVPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlFormatADCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlFormatADPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlPromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlAvgOrderBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlPurchAmount] [money] NOT NULL,
[IntlParts] [dbo].[udtCourseParts] NOT NULL,
[IntlPartsBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagIntlBackOrder] [tinyint] NOT NULL,
[IntlNumOfCOurses] [smallint] NOT NULL,
[FlagEmailable] [tinyint] NULL,
[FlagMailable] [tinyint] NOT NULL,
[FlagMailableCollegeBuyer] [tinyint] NOT NULL,
[FlagIntlCouponRedm] [tinyint] NOT NULL,
[FlagIntlPurchTran] [tinyint] NOT NULL,
[FirstRegion] [tinyint] NULL,
[Gender] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOfHits] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReliabilityCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlPurchaseDate] [datetime] NOT NULL,
[MonthID] [int] NOT NULL,
[Year] [int] NOT NULL,
[QuarterID] [int] NOT NULL,
[SPFlag] [tinyint] NOT NULL,
[SPFlagCoupon] [tinyint] NOT NULL,
[SPPromotionType] [smallint] NOT NULL,
[SPFormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPSubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPFormatAV] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPFormatAD] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPFlagTran] [tinyint] NOT NULL,
[SPSalesAmountCatID] [int] NOT NULL,
[SPFlag3Mth] [tinyint] NOT NULL,
[SPFlag6Mth] [tinyint] NOT NULL,
[SPFlag12Mth] [tinyint] NOT NULL,
[DS1moSales] [money] NOT NULL,
[DS2moSales] [money] NOT NULL,
[DS3moSales] [money] NOT NULL,
[DS4moSales] [money] NOT NULL,
[DS5moSales] [money] NOT NULL,
[DS6moSales] [money] NOT NULL,
[DS12moSales] [money] NOT NULL,
[DS18moSales] [money] NOT NULL,
[DS24moSales] [money] NOT NULL,
[DS36moSales] [money] NOT NULL,
[DS48moSales] [money] NOT NULL,
[DS60moSales] [money] NOT NULL,
[DS72moSales] [money] NOT NULL,
[DS84moSales] [money] NOT NULL,
[DS96moSales] [money] NOT NULL,
[DS108moSales] [money] NOT NULL,
[DS120moSales] [money] NOT NULL,
[DS1moOrders] [int] NOT NULL,
[DS2moOrders] [int] NOT NULL,
[DS3moOrders] [int] NOT NULL,
[DS4moOrders] [int] NOT NULL,
[DS5moOrders] [int] NOT NULL,
[DS6moOrders] [int] NOT NULL,
[DS12moOrders] [int] NOT NULL,
[DS18moOrders] [int] NOT NULL,
[DS24moOrders] [int] NOT NULL,
[DS36moOrders] [int] NOT NULL,
[DS48moOrders] [int] NOT NULL,
[DS60moOrders] [int] NOT NULL,
[DS72moOrders] [int] NOT NULL,
[DS84moOrders] [int] NOT NULL,
[DS96moOrders] [int] NOT NULL,
[DS108moOrders] [int] NOT NULL,
[DS120moOrders] [int] NOT NULL,
[DS1moFlagRepeatByr] [tinyint] NOT NULL,
[DS2moFlagRepeatByr] [tinyint] NOT NULL,
[DS3moFlagRepeatByr] [tinyint] NOT NULL,
[DS4moFlagRepeatByr] [tinyint] NOT NULL,
[DS5moFlagRepeatByr] [tinyint] NOT NULL,
[DS6moFlagRepeatByr] [tinyint] NOT NULL,
[DS12moFlagRepeatByr] [tinyint] NOT NULL,
[DS18moFlagRepeatByr] [tinyint] NOT NULL,
[DS24moFlagRepeatByr] [tinyint] NOT NULL,
[DS36moFlagRepeatByr] [tinyint] NOT NULL,
[DS48moFlagRepeatByr] [tinyint] NOT NULL,
[DS60moFlagRepeatByr] [tinyint] NOT NULL,
[DS72moFlagRepeatByr] [tinyint] NOT NULL,
[DS84moFlagRepeatByr] [tinyint] NOT NULL,
[DS96moFlagRepeatByr] [tinyint] NOT NULL,
[DS108moFlagRepeatByr] [tinyint] NOT NULL,
[DS120moFlagRepeatByr] [tinyint] NOT NULL,
[DS1moUnits] [int] NOT NULL,
[DS2moUnits] [int] NOT NULL,
[DS3moUnits] [int] NOT NULL,
[DS4moUnits] [int] NOT NULL,
[DS5moUnits] [int] NOT NULL,
[DS6moUnits] [int] NOT NULL,
[DS12moUnits] [int] NOT NULL,
[DS18moUnits] [int] NOT NULL,
[DS24moUnits] [int] NOT NULL,
[DS36moUnits] [int] NOT NULL,
[DS48moUnits] [int] NOT NULL,
[DS60moUnits] [int] NOT NULL,
[DS72moUnits] [int] NOT NULL,
[DS84moUnits] [int] NOT NULL,
[DS96moUnits] [int] NOT NULL,
[DS108moUnits] [int] NOT NULL,
[DS120moUnits] [int] NOT NULL,
[DS1moParts] [float] NOT NULL,
[DS2moParts] [float] NOT NULL,
[DS3moParts] [float] NOT NULL,
[DS4moParts] [float] NOT NULL,
[DS5moParts] [float] NOT NULL,
[DS6moParts] [float] NOT NULL,
[DS12moParts] [float] NOT NULL,
[DS18moParts] [float] NOT NULL,
[DS24moParts] [float] NOT NULL,
[DS36moParts] [float] NOT NULL,
[DS48moParts] [float] NOT NULL,
[DS60moParts] [float] NOT NULL,
[DS72moParts] [float] NOT NULL,
[DS84moParts] [float] NOT NULL,
[DS96moParts] [float] NOT NULL,
[DS108moParts] [float] NOT NULL,
[DS120moParts] [float] NOT NULL,
[DS1moCourseSales] [money] NOT NULL,
[DS2moCourseSales] [money] NOT NULL,
[DS3moCourseSales] [money] NOT NULL,
[DS4moCourseSales] [money] NOT NULL,
[DS5moCourseSales] [money] NOT NULL,
[DS6moCourseSales] [money] NOT NULL,
[DS12moCourseSales] [money] NOT NULL,
[DS18moCourseSales] [money] NOT NULL,
[DS24moCourseSales] [money] NOT NULL,
[DS36moCourseSales] [money] NOT NULL,
[DS48moCourseSales] [money] NOT NULL,
[DS60moCourseSales] [money] NOT NULL,
[DS72moCourseSales] [money] NOT NULL,
[DS84moCourseSales] [money] NOT NULL,
[DS96moCourseSales] [money] NOT NULL,
[DS108moCourseSales] [money] NOT NULL,
[DS120moCourseSales] [money] NOT NULL,
[DS1moMailContacts] [int] NULL,
[DS2moMailContacts] [int] NULL,
[DS3moMailContacts] [int] NULL,
[DS6moMailContacts] [int] NULL,
[DS12moMailContacts] [int] NULL,
[DS18moMailContacts] [int] NULL,
[DS24moMailContacts] [int] NULL,
[DS1moEmailContacts] [int] NULL,
[DS2moEmailContacts] [int] NULL,
[DS3moEmailContacts] [int] NULL,
[DS6moEmailContacts] [int] NULL,
[DS12moEmailContacts] [int] NULL,
[DS18moEmailContacts] [int] NULL,
[DS24moEmailContacts] [int] NULL,
[DSDays] [int] NOT NULL,
[CountryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HouseHoldIncomeBin] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EducationBin] [varchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AgeBin] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlAvgOrderBin_2] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Intl_CourseCategory] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPPromotionTypeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SequenceNum] [int] NULL,
[CourseID] [int] NULL,
[DateOrdered] [smalldatetime] NULL,
[FormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BundleID] [int] NULL,
[CourseReleaseDate] [smalldatetime] NULL,
[DaysSinceRelease] [int] NULL,
[FlagNewCourse] [bit] NULL,
[SubjectCategory] [dbo].[udtSubjectPreference] NULL,
[CourseParts] [dbo].[udtCourseParts] NULL,
[SubjectCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AbbrvCourseName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalSales] [money] NULL,
[TotalParts] [dbo].[udtCourseParts] NULL,
[TotalQuantity] [int] NULL,
[SalesPrice] [money] NULL,
[PM4_Price] [money] NULL
) ON [PRIMARY]
GO
