CREATE TABLE [Marketing].[CustomerSubjectMatrix]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AH] [tinyint] NULL,
[EC] [tinyint] NULL,
[FA] [tinyint] NULL,
[LIT] [tinyint] NULL,
[MH] [tinyint] NULL,
[PH] [tinyint] NULL,
[RL] [tinyint] NULL,
[SC] [tinyint] NULL,
[HS] [tinyint] NULL,
[Audio] [tinyint] NULL,
[Video] [tinyint] NULL,
[CD] [tinyint] NULL,
[DVD] [tinyint] NULL,
[Downloads] [tinyint] NULL,
[HSFormat] [tinyint] NULL,
[Transcript] [tinyint] NULL,
[TranscriptOnly] [tinyint] NULL,
[RFMStatus] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [tinyint] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12MF] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active] [tinyint] NULL,
[HSOnly] [bit] NULL,
[HSandCollege] [tinyint] NULL,
[CollegeOnly] [tinyint] NULL,
[FW] [tinyint] NULL,
[PR] [tinyint] NULL,
[VideoDownloads] [tinyint] NULL,
[SCI] [bit] NULL,
[MTH] [bit] NULL,
[VA] [bit] NULL,
[MSC] [bit] NULL,
[PreferredCategory] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
