CREATE TABLE [Staging].[TGCplus_DS_Working]
(
[Coalesce_DSDate] [datetime] NULL,
[CustomerID] [bigint] NULL,
[DS_User_id] [bigint] NULL,
[EntitlementDays] [int] NULL,
[DS_Service_period_from] [datetime] NULL,
[DS_Service_period_to] [datetime] NULL,
[DS_MonthDiff] [int] NULL,
[DS_Month] [int] NULL,
[DSDate] [datetime] NULL,
[DS_ValidDS] [int] NULL,
[DS_Entitled] [int] NULL,
[User_id] [bigint] NULL,
[completed_at] [datetime] NULL,
[billing_cycle_period_type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pre_tax_amount] [money] NULL,
[service_period_from] [datetime] NULL,
[service_period_to] [datetime] NULL,
[actual_service_period_to] [datetime] NULL,
[subscription_plan_id] [bigint] NULL,
[payment_handler] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingRank] [bigint] NULL,
[Refunded] [bit] NULL,
[RefundedAmount] [money] NULL,
[Refunded_Completed_at] [datetime] NULL,
[Changed_RefundedService_period_to] [bit] NULL,
[Changed_Service_period_to] [bit] NULL,
[Changed_Billing_cycle_period_type] [bit] NULL,
[Changed_Subscription_plan_id] [bit] NULL,
[Changed_Payment_handler] [bit] NULL,
[PAS_Cancelled_date] [datetime] NULL,
[PAS_Cancelled] [bit] NULL,
[PAS_DeferredSuspension_date] [datetime] NULL,
[PAS_DeferredSuspension] [bit] NULL,
[PAS_Suspended_date] [datetime] NULL,
[PAS_Suspended] [bit] NULL,
[BillingDupes] [int] NULL,
[UBIssue] [bit] NULL,
[Final_Status] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [money] NULL,
[NetAmount] [money] NULL,
[DS] [int] NULL,
[DSSplits] [int] NULL,
[PaidFlag] [int] NULL
) ON [PRIMARY]
GO
