CREATE TABLE [Staging].[influencer_ssis_master_20170606]
(
[UniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date] [datetime] NULL,
[OfferID] [float] NULL,
[Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceCode1 (advertised URL)] [float] NULL,
[SourceCode2 (short URL)] [float] NULL,
[SourceCode3 (TGC Redirect)] [float] NULL,
[StartWeek] [datetime] NULL,
[StartMonth] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartYear] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnScreenLink] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VideoDescriptionLink] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RedirectHTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DescriptionLinkShortURLRedirectsto] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheGreatCoursesURL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheGreatCoursesRedirectHTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateURLsSetUp] [datetime] NULL,
[DateIOSigned] [datetime] NULL,
[Invoice] [float] NULL,
[DateInvoicePassedtoAccounting] [datetime] NULL,
[SpotCost] [money] NULL,
[Sessions] [money] NULL,
[Registrations] [money] NULL,
[Signups] [money] NULL,
[ExpectedViews] [float] NULL,
[SubsifRRis24] [float] NULL,
[SubsifCPAis80] [float] NULL,
[SubsifCPAis150] [float] NULL,
[MonthforBudget] [float] NULL,
[DMLastupdated] [datetime] NULL
) ON [PRIMARY]
GO
