CREATE TABLE [Staging].[tempQuarterlyTrackerResults]
(
[RESPONDENTNUMBER] [float] NULL,
[SubmitDate] [datetime] NULL,
[Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FREQUENCY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSOURCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENSAT_VALUE] [float] NULL,
[RPLIKELI_VALUE] [float] NULL,
[LIKELIRECOMM_VALUE] [float] NULL,
[CUSTEFFORT_VALUE] [float] NULL,
[COURSENAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIATYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREAMCOURSE] [float] NULL,
[DLEXPERIENCE] [float] NULL,
[Streamingexperience] [float] NULL,
[COURSESAT] [float] NULL,
[Learn_New_or_Valuable_Value] [float] NULL,
[VISUALSAT_VALUE] [float] NULL,
[PROFPRESENTSAT_VALUE] [float] NULL,
[COURSE_PRICE_VALUE] [float] NULL,
[ACSI_IDEAL_COURSE] [float] NULL,
[COURSESELECTSAT_VALUE] [float] NULL,
[ACSI_EXPECTATIONS] [float] NULL,
[BACKLOG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BACKLOG_NUMBER] [float] NULL,
[MAJORPROBLEMS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTED_CSR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROBLEM_RESOLVED] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATSAT_VALUE] [float] NULL,
[EMAIL_FREQ_VALUE] [float] NULL,
[CAT_FREQ_VALUE] [float] NULL,
[GUIDEBOOKSAT_VALUE] [float] NULL,
[WEBSITE_EASENAV_VALUE] [float] NULL,
[WEBSITE_LAYOUT] [float] NULL,
[WEBSITE_ACCURACY] [float] NULL,
[ANDROIDSAT] [float] NULL,
[IPADSAT] [float] NULL,
[IPHONESAT] [float] NULL,
[TORCHSAT] [float] NULL,
[ROKUSAT] [float] NULL,
[Employment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
