CREATE TABLE [Staging].[TempCustomerVariablesL12M]
(
[CustomerID] [dbo].[udtCustomerID] NULL,
[Orderid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOrdered] [smalldatetime] NULL,
[OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSourceRU] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDigitalPhysical] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetOrderAmount] [money] NULL,
[TotalCourseSales] [money] NULL,
[TotalCourseQuantity] [int] NOT NULL,
[TotalTranscriptSales] [money] NULL,
[TotalTranscriptQuantity] [int] NULL,
[ShippingCharge] [money] NULL,
[DiscountAmount] [money] NULL,
[tax] [money] NULL,
[NetMinusShip] [money] NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[CustSegmentAsOfDate] [date] NULL,
[CustomerSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegmentFnl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg] [int] NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[a12mf] [int] NULL,
[TGCPlusCustID] [bigint] NULL,
[TGCPlusCustStatusFlag] [float] NULL,
[TGCPlusSubDate] [date] NULL,
[TGCPlusSubPlanID] [int] NULL,
[TGCPlusSubPlanName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGCPlusSubType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelID] [int] NULL,
[MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelRU] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelRU_DigitalMktL12M] [int] NOT NULL,
[MD_ChannelRU_EmailL12M] [int] NOT NULL,
[MD_ChannelRU_PhysicalMailL12M] [int] NOT NULL,
[MD_ChannelRU_SpaceAdsL12M] [int] NOT NULL,
[MD_ChannelRU_WebDefaultL12M] [int] NOT NULL,
[MD_ChannelRU_OtherL12M] [int] NOT NULL,
[Sales_MD_ChannelRU_DigitalMktL12M] [money] NULL,
[Sales_MD_ChannelRU_EmailL12M] [money] NULL,
[Sales_MD_ChannelRU_PhysicalMailL12M] [money] NULL,
[Sales_MD_ChannelRU_SpaceAdsL12M] [money] NULL,
[Sales_MD_ChannelRU_WebDefaultL12M] [money] NULL,
[Sales_MD_ChannelRU_OtherL12M] [money] NULL,
[Units_MD_ChannelRU_DigitalMktL12M] [int] NULL,
[Units_MD_ChannelRU_EmailL12M] [int] NULL,
[Units_MD_ChannelRU_PhysicalMailL12M] [int] NULL,
[Units_MD_ChannelRU_SpaceAdsL12M] [int] NULL,
[Units_MD_ChannelRU_WebDefaultL12M] [int] NULL,
[Units_MD_ChannelRU_OtherL12M] [int] NULL,
[OrderSourceRU_WebL12M] [int] NOT NULL,
[OrderSourceRU_PhoneL12M] [int] NOT NULL,
[OrderSourceRU_MailL12M] [int] NOT NULL,
[OrderSourceRU_EmailL12M] [int] NOT NULL,
[OrderSourceRU_OtherL12M] [int] NOT NULL,
[Sales_OrderSourceRU_WebL12M] [money] NULL,
[Sales_OrderSourceRU_PhoneL12M] [money] NULL,
[Sales_OrderSourceRU_MailL12M] [money] NULL,
[Sales_OrderSourceRU_EmailL12M] [money] NULL,
[Sales_OrderSourceRU_OtherL12M] [money] NULL,
[Units_OrderSourceRU_WebL12M] [int] NULL,
[Units_OrderSourceRU_PhoneL12M] [int] NULL,
[Units_OrderSourceRU_MailL12M] [int] NULL,
[Units_OrderSourceRU_EmailL12M] [int] NULL,
[Units_OrderSourceRU_OtherL12M] [int] NULL,
[FlagStreamedTGCL12M] [int] NOT NULL,
[FlagStreamedTGCL12M_DgAudio] [int] NOT NULL,
[FlagStreamedTGCL12M_DgVideo] [int] NOT NULL,
[FlagStreamedTGCL12M_PhyAudio] [int] NOT NULL,
[FlagStreamedTGCL12M_PhyVideo] [int] NOT NULL,
[MediaFormatPreference] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MediaFormatPreferenceL12M] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderSourceRUPreferenceL12M] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDChannelRUPreferenceL12M] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MediaFormatCategoryL12M] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FMT_DigitalAudioL12M] [int] NULL,
[FMT_DVDL12M] [int] NULL,
[FMT_CDL12M] [int] NULL,
[FMT_DigitalVideoL12M] [int] NULL,
[FMT_TranscriptL12M] [int] NULL,
[FMT_DigitalTranscriptL12M] [int] NULL,
[FMT_AudioCsstL12M] [int] NULL,
[FMT_VHSL12M] [int] NULL,
[Sales_DigitalAudioL12M] [money] NULL,
[Sales_DVDL12M] [money] NULL,
[Sales_CDL12M] [money] NULL,
[Sales_DigitalVideoL12M] [money] NULL,
[Sales_TranscriptL12M] [money] NULL,
[Sales_DigitalTranscriptL12M] [money] NULL,
[Sales_AudioCsstL12M] [money] NULL,
[Sales_VHSL12M] [money] NULL,
[Units_DigitalAudioL12M] [int] NULL,
[Units_DVDL12M] [int] NULL,
[Units_CDL12M] [int] NULL,
[Units_DigitalVideoL12M] [int] NULL,
[Units_TranscriptL12M] [int] NULL,
[Units_DigitalTranscriptL12M] [int] NULL,
[Units_AudioCsstL12M] [int] NULL,
[Units_VHSL12M] [int] NULL
) ON [PRIMARY]
GO
