CREATE TABLE [Staging].[TempDMSOUPByFormatIgnoreReturns]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dateordered] [datetime] NULL,
[NetOrderAmount] [money] NULL,
[ShippingCharge] [money] NULL,
[DiscountAmount] [money] NULL,
[Tax] [money] NULL,
[OrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdCode] [int] NULL,
[CDSales] [money] NULL,
[CDUnits] [int] NULL,
[CDParts] [money] NULL,
[DVDSales] [money] NULL,
[DVDUnits] [int] NULL,
[DVDParts] [money] NULL,
[AudioTapeSales] [money] NULL,
[AudioTapeUnits] [int] NULL,
[AudioTapeParts] [money] NULL,
[VHSSales] [money] NULL,
[VHSUnits] [int] NULL,
[VHSParts] [money] NULL,
[AudioDLSales] [money] NULL,
[AudioDLUnits] [int] NULL,
[AudioDLParts] [money] NULL,
[VideoDLSales] [money] NULL,
[VideoDLUnits] [int] NULL,
[VideoDLParts] [money] NULL,
[TranscriptSales] [money] NULL,
[TranscriptUnits] [int] NULL,
[TranscriptParts] [money] NULL,
[DigitalTranscriptSales] [money] NULL,
[DigitalTranscriptUnits] [int] NULL,
[DigitalTranscriptParts] [money] NULL,
[DigitalSales] [money] NULL,
[DigitalUnits] [int] NULL,
[DigitalParts] [money] NULL,
[PhysicalSales] [money] NULL,
[PhysicalUnits] [int] NULL,
[PhysicalParts] [money] NULL,
[TotalMerchandizeSales] [money] NULL,
[TotalMerchandizeUnits] [int] NULL,
[TotalMerchandizeParts] [money] NULL,
[FlagCD] [bit] NULL,
[FlagDVD] [bit] NULL,
[FlagAudioTape] [bit] NULL,
[FlagVHS] [bit] NULL,
[FlagAudioDL] [bit] NULL,
[FlagVideoDL] [bit] NULL,
[FlagTranscript] [bit] NULL,
[FlagDigitalTranscript] [bit] NULL,
[FlagDigital] [bit] NULL,
[FlagPhysical] [bit] NULL,
[OrderSourceRU] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelID] [int] NULL,
[MD_Channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_ChannelRU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adj_CDSales] [money] NULL,
[Adj_DVDSales] [money] NULL,
[Adj_AudioTapeSales] [money] NULL,
[Adj_VHSSales] [money] NULL,
[Adj_AudioDLSales] [money] NULL,
[Adj_VideoDLSales] [money] NULL,
[Adj_TranscriptSales] [money] NULL,
[Adj_DigitalTranscriptSales] [money] NULL,
[Adj_DigitalSales] [money] NULL,
[Adj_PhysicalSales] [money] NULL,
[Adj_TotalMerchandizeSales] [money] NULL
) ON [PRIMARY]
GO
