CREATE TABLE [Staging].[TempTGCPlus_RadioMasterTrnsfrm]
(
[OfferIDUnq] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfferID] [float] NULL,
[OfferCodeDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Offer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Course] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Creative] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LandingPageTemplate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfSpots] [float] NULL,
[SpotNumber] [int] NOT NULL,
[TotalPaidSpots] [int] NULL,
[RunStartDate] [date] NULL,
[RunStopDate] [date] NULL,
[SourceCodeMain] [float] NULL,
[SourceCodeTGCRedirect] [float] NULL,
[FlagTest] [int] NULL,
[StartWeek] [date] NULL,
[StartYear] [int] NULL,
[StartMonth] [int] NULL,
[ExpirationDate] [date] NULL,
[FlagComplete] [float] NULL,
[AgencyOrDirectBuy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramAbbreviation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URLAdvertised] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvertisementType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TestOrRenewal] [float] NULL,
[SpotType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpotLength] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpotsPerEpisode] [float] NULL,
[ProgramCategoryOrFormat] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostPerEpisodeOrSOV] [money] NULL,
[AvgEpisodeImpressions] [float] NULL,
[TotalImpressionsForOfferID] [float] NULL,
[TotalCostForOfferID] [money] NULL,
[GA_PageView_SrcMain] [int] NULL,
[GA_Sessions_SrcMain] [int] NULL,
[MinIntlSubDate_SrcMain] [date] NULL,
[MaxIntlSubDate_SrcMain] [date] NULL,
[IntlRegistrations_SrcMain] [int] NULL,
[IntlSubscribers_SrcMain] [int] NULL,
[IntlMonthlySubs_SrcMain] [int] NULL,
[IntlYearlySubs_SrcMain] [int] NULL,
[IntlMonthlyActvs_SrcMain] [int] NULL,
[IntlYearlyActvs_SrcMain] [int] NULL,
[IntlMonthlyCancls_SrcMain] [int] NULL,
[IntlYearlyCancls_SrcMain] [int] NULL,
[IntlMonthlyPaid_SrcMain] [int] NULL,
[IntlYearlyPaid_SrcMain] [int] NULL,
[GA_PageView_SrcTGCRdrct] [int] NULL,
[GA_Sessions_SrcTGCRdrct] [int] NULL,
[MinIntlSubDate_SrcTGCRdrct] [date] NULL,
[MaxIntlSubDate_SrcTGCRdrct] [date] NULL,
[IntlRegistrations_SrcTGCRdrct] [int] NULL,
[IntlSubscribers_SrcTGCRdrct] [int] NULL,
[IntlMonthlySubs_SrcTGCRdrct] [int] NULL,
[IntlYearlySubs_SrcTGCRdrct] [int] NULL,
[IntlMonthlyActvs_SrcTGCRdrct] [int] NULL,
[IntlYearlyActvs_SrcTGCRdrct] [int] NULL,
[IntlMonthlyCancls_SrcTGCRdrct] [int] NULL,
[IntlYearlyCancls_SrcTGCRdrct] [int] NULL,
[IntlMonthlyPaid_SrcTGCRdrct] [int] NULL,
[IntlYearlyPaid_SrcTGCRdrct] [int] NULL
) ON [PRIMARY]
GO
