CREATE TABLE [Staging].[WPLetterSend_Archive]
(
[Customerid] [int] NULL,
[PackageType] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middleinit] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponExpire] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adcode] [int] NULL,
[CourseID1] [int] NULL,
[coursename1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfName1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WPDesc1] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Fmt1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Price1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Fmt2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Price2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Fmt3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Price3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Fmt4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Price4] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Fmt5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo1Price5] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseID2] [int] NULL,
[coursename2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfName2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WPDesc2] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2] [varchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Fmt1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Price1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Fmt2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Price2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Fmt3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Price3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Fmt4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Price4] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Fmt5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo2Price5] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseID3] [int] NULL,
[coursename3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfName3] [varchar] (361) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WPDesc3] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3] [varchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Fmt1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Price1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Fmt2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Price2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Fmt3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Price3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Fmt4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Price4] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Fmt5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseNo3Price5] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartDate] [datetime] NULL,
[ArchiveDate] [datetime] NULL
) ON [PRIMARY]
GO
