CREATE TABLE [Staging].[Orders]
(
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrderDate] [datetime] NULL,
[OrderSource] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdCode] [int] NULL,
[ShippingCharge] [money] NULL,
[Tax] [money] NULL,
[DiscountAmount] [money] NULL,
[BillingCountryCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinShipDate] [date] NULL,
[MaxShipDate] [date] NULL,
[PaymentToDate] [money] NULL,
[OrderStatus] [int] NULL,
[InvoiceAccount] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryMode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesType] [int] NULL,
[CurrencyCode] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToName] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShiptoAddress] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToCity] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToZip] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipToCountryCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSRID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedDate] [datetime] NULL,
[BillingAddress1] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingZip] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedBy] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderChannel] [int] NULL,
[CUSTGROUP] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MultipleDeliveries] [int] NULL,
[TotalMerchandise] [money] NULL,
[TotalTaxes] [money] NULL,
[TotalShipping] [money] NULL,
[TotalCoupons] [money] NULL,
[OtherCharges] [money] NULL,
[BillingName] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress3] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WebOrderID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jsGiftFlag] [int] NULL,
[jsGiftMessage] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxGroup] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jsDeliveryPhone] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentStatus] [int] NULL,
[OrderDateGMT] [datetime] NULL,
[ModifiedDateGMT] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_Orders_OrderDate_OrderStatus] ON [Staging].[Orders] ([OrderDate], [OrderStatus]) INCLUDE ([OrderID]) ON [PRIMARY]
GO
