CREATE TABLE [Staging].[ST_ssis_Subscriberlist]
(
[Profile Id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Domain] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Engagement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lists] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Profile Created Date] [datetime] NULL,
[Signup] [datetime] NULL,
[Opens] [int] NULL,
[Clicks] [int] NULL,
[Pageviews] [int] NULL,
[Last Open] [datetime] NULL,
[Last Click] [datetime] NULL,
[Last Pageview] [datetime] NULL,
[Optout Time] [datetime] NULL,
[List Signup] [datetime] NULL,
[Geolocation City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Geolocation State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Geolocation Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Geolocation Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lifetime Message] [int] NULL,
[First Purchase Time] [datetime] NULL,
[Purchase Count] [int] NULL,
[Purchase Price] [real] NULL,
[Purchase Incomplete] [int] NULL,
[Last Purchase Time] [datetime] NULL,
[Largest Purchase Item Price] [real] NULL,
[Top Device] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[andoirdUser] [bit] NULL,
[people_following] [int] NULL,
[googletvUser] [bit] NULL,
[collections_created] [bit] NULL,
[location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rokuUser] [bit] NULL,
[join_date] [datetime] NULL,
[samsungUser] [bit] NULL,
[films_queued] [int] NULL,
[lgUser] [bit] NULL,
[first_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[verified] [bit] NULL,
[gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postal_city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[movies_watched] [int] NULL,
[weekly] [int] NULL,
[panasonicUser] [bit] NULL,
[windows8User] [bit] NULL,
[films_favorited] [int] NULL,
[xboxUser] [bit] NULL,
[last_login] [datetime] NULL,
[display_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wdUser] [bit] NULL,
[source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[notifications] [bit] NULL,
[last_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postal_state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[iOSUser] [bit] NULL,
[subscribed_at_time ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
