CREATE TABLE [Staging].[WPMailCustomers]
(
[CustomerID] [dbo].[udtCustomerID] NOT NULL,
[Prefix] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (240) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSinceDate] [datetime] NULL,
[MinOrderIDinPeriod] [dbo].[udtOrderID] NULL,
[MinPurchDateInPeriod] [datetime] NULL,
[CardNumber] [char] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MatchCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BuyerType] [tinyint] NOT NULL,
[PullDate] [smalldatetime] NULL,
[StartDate] [smalldatetime] NULL,
[EndDate] [smalldatetime] NULL,
[Newseg] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSegName] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12MF] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagNoMail] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WPAdCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCExpireDate] [smalldatetime] NULL,
[PrintPendingFlag] [bit] NOT NULL,
[PrintFlag] [bit] NOT NULL,
[LastPrintDate] [datetime] NULL,
[ReviewedFlag] [bit] NOT NULL
) ON [PRIMARY]
GO
