CREATE TABLE [Staging].[Quad_ssis_postmerge]
(
[FILLER1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KEYLINE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q_SEED_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRST_NAME1] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME1] [varchar] (34) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PADDRESS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG_CITY] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG_STATE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG_ZIP] [smallint] NULL,
[ORG_ZIP4] [smallint] NULL,
[FILLER4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIA_ER1] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIA_ID1] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIA_SQ1] [int] NULL,
[NDC_ORG] [smallint] NULL,
[REQUEST_NO] [int] NULL,
[TITLECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q_SEED_KEY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID99] [smallint] NULL,
[QUAD_ACCTID] [smallint] NULL,
[MEDIA_OUTPUT_LIST_NAME] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSS_IND] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STD_PADDRESS] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STD_REMAINDER] [datetime] NULL,
[EXTRA3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA4] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URB] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [smallint] NULL,
[ZIP4] [smallint] NULL,
[DPBC] [smallint] NULL,
[CHKDGT] [smallint] NULL,
[CART] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOT] [smallint] NULL,
[LOT_ORDER] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STAT_CODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ERRORCODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPV_CMRA] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPV_STATUS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPV_VACANT] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASS_MATCH] [smallint] NULL,
[DPV_FTNOTE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DPV_NOSTAT] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPMATCH] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LACSL_IND] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LACSL_RET] [smallint] NULL,
[STELINK_RC] [smallint] NULL,
[RECTYPE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QDS_MAIL_SCORE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_CODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HYGIENE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NDC_STATUS] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NDC] [smallint] NULL,
[HYG_LINE1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HYG_LINE2] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HYG_LINE3] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HYG_CSZ] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HYG_LCODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUST_NO] [int] NULL,
[PRE_NAME1] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MID_NAME1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POST_NAME1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINE2] [varchar] (84) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINE1] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID2] [smallint] NULL,
[KEYCODE] [int] NULL,
[ID1] [int] NULL,
[QDS_PAD] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER6] [smallint] NULL,
[FILLER7] [int] NULL,
[FILLER8] [int] NULL,
[SRVC_TYPE] [smallint] NULL,
[IMB_MID] [int] NULL,
[IMB_SERIAL] [int] NULL,
[VERSION_ID] [smallint] NULL,
[FILLER11] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
