CREATE TABLE [Staging].[MC_TGC_Consumption_L12MnthSmryTEMP_TEST]
(
[CustomerID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalPlays_L12Mnth] [int] NOT NULL,
[StreamedMins_L12Mnth] [numeric] (18, 2) NOT NULL,
[CoursesStreamed_L12Mnth] [int] NOT NULL,
[LecturesStreamed_L12Mnth] [int] NOT NULL,
[FlagStreamed_L12Mnth] [int] NOT NULL,
[TotalPlays_DVD_L12Mnth] [int] NOT NULL,
[StreamedMins_DVD_L12Mnth] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DVD_L12Mnth] [int] NOT NULL,
[LecturesStreamed_DVD_L12Mnth] [int] NOT NULL,
[FlagStreamed_DVD_L12Mnth] [int] NOT NULL,
[TotalPlays_CD_L12Mnth] [int] NOT NULL,
[StreamedMins_CD_L12Mnth] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_CD_L12Mnth] [int] NOT NULL,
[LecturesStreamed_CD_L12Mnth] [int] NOT NULL,
[FlagStreamed_CD_L12Mnth] [int] NOT NULL,
[TotalPlays_DownloadV_L12Mnth] [int] NOT NULL,
[StreamedMins_DownloadV_L12Mnth] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DownloadV_L12Mnth] [int] NOT NULL,
[LecturesStreamed_DownloadV_L12Mnth] [int] NOT NULL,
[FlagStreamed_DownloadV_L12Mnth] [int] NOT NULL,
[TotalPlays_DownloadA_L12Mnth] [int] NOT NULL,
[StreamedMins_DownloadA_L12Mnth] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DownloadA_L12Mnth] [int] NOT NULL,
[LecturesStreamed_DownloadA_L12Mnth] [int] NOT NULL,
[FlagStreamed_DownloadA_L12Mnth] [int] NOT NULL,
[TotalDnlds_L12Mnth] [int] NOT NULL,
[CoursesDnld_L12Mnth] [int] NOT NULL,
[LecturesDnld_L12Mnth] [int] NOT NULL,
[FlagDnld_L12Mnth] [int] NOT NULL,
[TotalDnlds_DownloadV_L12Mnth] [int] NOT NULL,
[CoursesDnld_DownloadV_L12Mnth] [int] NOT NULL,
[LecturesDnld_DownloadV_L12Mnth] [int] NOT NULL,
[FlagDnld_DownloadV_L12Mnth] [int] NOT NULL,
[TotalDnlds_DownloadA_L12Mnth] [int] NOT NULL,
[CoursesDnld_DownloadA_L12Mnth] [int] NOT NULL,
[LecturesDnld_DownloadA_L12Mnth] [int] NOT NULL,
[FlagDnld_DownloadA_L12Mnth] [int] NOT NULL
) ON [PRIMARY]
GO
