CREATE TABLE [Staging].[TempCourse_Downstream_SOUP]
(
[ReportDate] [datetime] NOT NULL,
[ordersource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SequenceNum] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PromotionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseID] [int] NULL,
[AbbrvCourseName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseParts] [dbo].[udtCourseParts] NULL,
[CourseHours] [money] NULL,
[SubjectCategory2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Topic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubTopic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagAudioVideo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagCD] [tinyint] NULL,
[FlagDVD] [tinyint] NULL,
[FlagAudioDL] [tinyint] NULL,
[FlagVideoDL] [tinyint] NULL,
[VDL_RLS_Flag] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ReleaseYear] [int] NULL,
[ReleaseMonth] [int] NULL,
[ReleaseDate] [datetime] NULL,
[CatalogYear] [int] NULL,
[CatalogMonth] [int] NULL,
[DaysSinceRelease] [int] NULL,
[MonthsSinceRelease] [int] NULL,
[YearsSinceRelease] [int] NULL,
[FormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalSales_15Days] [money] NULL,
[TotalUnits_15Days] [int] NULL,
[TotalParts_15Days] [money] NULL,
[TotalOverallSales_15Days] [money] NULL,
[TotalOverallUnits_15Days] [int] NULL,
[TotalOverallParts_15Days] [money] NULL,
[TotalSales_1Mnth] [money] NULL,
[TotalUnits_1Mnth] [int] NULL,
[TotalParts_1Mnth] [money] NULL,
[TotalOverallSales_1Mnth] [money] NULL,
[TotalOverallUnits_1Mnth] [int] NULL,
[TotalOverallParts_1Mnth] [money] NULL,
[TotalSales_2Mnth] [money] NULL,
[TotalUnits_2Mnth] [int] NULL,
[TotalParts_2Mnth] [money] NULL,
[TotalOverallSales_2Mnth] [money] NULL,
[TotalOverallUnits_2Mnth] [int] NULL,
[TotalOverallParts_2Mnth] [money] NULL,
[TotalSales_12Mnth] [money] NULL,
[TotalUnits_12Mnth] [int] NULL,
[TotalParts_12Mnth] [money] NULL,
[TotalOverallSales_12Mnth] [money] NULL,
[TotalOverallUnits_12Mnth] [int] NULL,
[TotalOverallParts_12Mnth] [money] NULL,
[TotalSales_6Mnth] [money] NULL,
[TotalUnits_6Mnth] [int] NULL,
[TotalParts_6Mnth] [money] NULL,
[TotalOverallSales_6Mnth] [money] NULL,
[TotalOverallUnits_6Mnth] [int] NULL,
[TotalOverallParts_6Mnth] [money] NULL,
[TotalSales_3Mnth] [money] NULL,
[TotalUnits_3Mnth] [int] NULL,
[TotalParts_3Mnth] [money] NULL,
[TotalOverallSales_3Mnth] [money] NULL,
[TotalOverallUnits_3Mnth] [int] NULL,
[TotalOverallParts_3Mnth] [money] NULL
) ON [PRIMARY]
GO
