CREATE TABLE [Staging].[tempAudibleTrackerResults]
(
[RESPONDENTNUMBER] [float] NULL,
[SUBMITDATE] [datetime] NULL,
[EMAIL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMERID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FREQUENCY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIATYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIBLE_BRANDAWARENESS_VALUE] [float] NULL,
[AUDIBLE_SUBSCRIBER_VALUE] [float] NULL,
[AUDIBLE_TGC_PURCHASE_VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIBLE_COURSES] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIBLE_BACKLOG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIBLE_BACKLOG_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIBLE_SATISFACTION_VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENSAT_VALUE] [float] NULL,
[Comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
