CREATE TABLE [Staging].[TGCPlus_CustomerDaily_BKP20160929DEL]
(
[AsofDate] [date] NULL,
[CustomerID] [bigint] NULL,
[uuid] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailAddress] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGCCustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlCampaignID] [int] NULL,
[IntlCampaignName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntlMDChannel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSubDate] [date] NULL,
[IntlSubWeek] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSubMonth] [int] NULL,
[IntlSubYear] [int] NULL,
[IntlSubPlanID] [bigint] NULL,
[IntlSubPlanName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSubType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlSubPaymentHandler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubDate] [date] NULL,
[SubWeek] [date] NULL,
[SubMonth] [int] NULL,
[SubYear] [int] NULL,
[SubPlanID] [int] NULL,
[SubPlanName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubPaymentHandler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustStatusFlag] [float] NULL,
[PaidFlag] [int] NULL,
[LTDPaidAmt] [float] NULL,
[LastPaidDate] [date] NULL,
[LastPaidWeek] [date] NULL,
[LastPaidMonth] [int] NULL,
[LastPaidYear] [int] NULL,
[LastPaidAmt] [float] NULL,
[DSDayCancelled] [int] NULL,
[DSMonthCancelled] [int] NULL,
[DSDayDeferred] [int] NULL,
[TGCCust] [int] NULL,
[TGCCustSegmentFcst] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TGCCustSegment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaxSeqNum] [bigint] NULL
) ON [PRIMARY]
GO
