CREATE TABLE [Staging].[TempDMCustomerStatic]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_CustomerID] DEFAULT ((0)),
[OrganizationID] [int] NULL CONSTRAINT [DF_DMCustomerStatic_OrganizationID] DEFAULT ((0)),
[CustomerSinceDateID] [int] NOT NULL CONSTRAINT [DF_DMCustomerStatic_CustomerSinceDateID] DEFAULT ((0)),
[CustomerSinceDate] [datetime] NOT NULL CONSTRAINT [DF_DMCustomerStatic_CustomerSinceDate] DEFAULT (((1)/(1))/(1900)),
[IntlPurchaseDateID] [int] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlPurchaseDateID] DEFAULT ((0)),
[IntlPurchaseDate] [datetime] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlPurchaseDate] DEFAULT ((0)),
[IntlPurchaseOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlPurchaseOrderID] DEFAULT ((0)),
[IntlPurchaseAdCode] [int] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlPurchaseAdCode] DEFAULT ((0)),
[IntlPurchAmount] [money] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlPurchAmount] DEFAULT ((0)),
[IntlSubjectCat] [dbo].[udtSubjectPreference] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlSubjectCat] DEFAULT ('X'),
[IntlSubjectPref] [dbo].[udtSubjectPreference] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlSubjectPref] DEFAULT ('X'),
[FlagIntlSubjectPrefTied] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagIntlSubjectPrefTied] DEFAULT ((0)),
[IntlFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlFormatMediaCat] DEFAULT ('X'),
[IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlFormatMediaPref] DEFAULT ('X'),
[FlagMediaPrefTied] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagMediaPrefTied] DEFAULT ((0)),
[IntlFormatAVCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlFormatAVCat] DEFAULT ('X'),
[IntlFormatAVPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlFormatAVPref] DEFAULT ('X'),
[FlagFormatAVPrefTied] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagFormatAVPrefTied] DEFAULT ((0)),
[IntlFormatADCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlFormatADCat] DEFAULT ('X'),
[IntlFormatADPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlFormatADPref] DEFAULT ('X'),
[FlagFormatADPrefTied] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagFormatADPrefTied] DEFAULT ((0)),
[IntlPromotionTypeID] [smallint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlPromotionType] DEFAULT ((0)),
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlOrderSource] DEFAULT ('X'),
[FlagIntlBackOrder] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagIntlBackOrder] DEFAULT ((0)),
[FirstCouponRedmDate] [datetime] NULL,
[FirstReturnDate] [datetime] NULL,
[FirstEMResponseDate] [datetime] NULL,
[FlagFirstInquirer] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagFirstInquirer] DEFAULT ((0)),
[FirstInquirerDate] [datetime] NULL,
[FirstBackOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_FirstBackOrderID] DEFAULT ((0)),
[FirstEMailAddress] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstRegion] [tinyint] NULL,
[FlagEmailable] [tinyint] NULL,
[FlagFirstEMailPref] [tinyint] NULL,
[FlagFirstMailPref] [tinyint] NULL,
[FlagMailable] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagMailable] DEFAULT ((1)),
[FirstBuyerType] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FirstBuyerType] DEFAULT ((0)),
[FlagMailableCollegeBuyer] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagMailableCollegeBuyer] DEFAULT ((0)),
[FlagIntlCouponRedm] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagIntlCouponRedm] DEFAULT ((0)),
[FirstCreateDate] [datetime] NULL,
[DMIntlCustomerType] [tinyint] NULL,
[SSCustomerType] [tinyint] NULL,
[RFMFlag] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_RFMFlag] DEFAULT ((0)),
[IntlAvgOrderBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlParts] [dbo].[udtCourseParts] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlParts] DEFAULT ((0)),
[IntlPartsBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlNumOfCOurses] [smallint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_IntlNumOfCOurses] DEFAULT ((0)),
[IntlCoursesBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOfHits] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReliabilityCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFlag] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagSP] DEFAULT ((0)),
[SPPromotionType] [smallint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPPromotionType] DEFAULT ((0)),
[SPFlagCoupon] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagSPCoupon] DEFAULT ((0)),
[SPFormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPFormatMedia] DEFAULT ('X'),
[SPSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPSubjectCat] DEFAULT ('X'),
[SPFormatAV] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPFormatAV] DEFAULT ('X'),
[SPFormatAD] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPFormatAD] DEFAULT ('X'),
[SPOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPOrderSource] DEFAULT ('X'),
[DSDays] [int] NOT NULL CONSTRAINT [DF_DMCustomerStatic_DSDays] DEFAULT ((0)),
[SPAmount] [money] NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPAmount] DEFAULT ((0)),
[FlagIntlPurchTran] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagIntlPurchTran] DEFAULT ((0)),
[SPFlagTran] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_FlagSPTran] DEFAULT ((0)),
[SPFlag3Mth] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPFlag3Mth] DEFAULT ((0)),
[SPFlag6Mth] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPFlag6Mth] DEFAULT ((0)),
[SPFlag12Mth] [tinyint] NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPFlag12Mth] DEFAULT ((0)),
[SPSubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStatic_SPSubjectPref] DEFAULT ('X'),
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialPurchaseSubjectPreference2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryPurchaseSubjectPreference2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDRTV] [bit] NULL
) ON [PRIMARY]
GO
