CREATE TABLE [Staging].[OrdAllctn_DLR_AJ]
(
[OrderID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerID] [float] NULL,
[YearOrdered] [float] NULL,
[NetOrderAmount] [float] NULL,
[MonthOrdered] [float] NULL,
[WeekOfOrder] [datetime] NULL,
[FlagCountry] [float] NULL,
[MD_Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOrdered] [datetime] NULL,
[StartDate] [datetime] NULL,
[StopDate] [datetime] NULL,
[WeekDiff] [float] NULL,
[FlagUnsourcedOrder] [float] NULL,
[AdCode] [float] NULL,
[AdcodeName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode] [float] NULL,
[CatalogName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceTypeID] [float] NULL,
[PromotionType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_Channel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PromotionType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_CampaignName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MD_PriceType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BudsCatalogCode] [float] NULL,
[BudsCategoryName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coupon] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssignedBudCode] [float] NULL,
[AssignedBudName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NMR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryFlag] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
