CREATE TABLE [Staging].[TempDMCustomerReActivationStaticnew]
(
[CustomerKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_CustomerID] DEFAULT ((0)),
[OrganizationID] [int] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_OrganizationID] DEFAULT ((0)),
[CustomerSinceDateID] [int] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_CustomerSinceDateID] DEFAULT ((0)),
[CustomerSinceDate] [datetime] NOT NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_CustomerSinceDate] DEFAULT (((1)/(1))/(1900)),
[ReActivationDateID] [int] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_ReActivationDateID] DEFAULT ((0)),
[ReActivationDate] [datetime] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_ReActivationDate] DEFAULT ((0)),
[ReActivationOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_ReActivationOrderID] DEFAULT ((0)),
[ReActivationAdCode] [int] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_ReActivationAdCode] DEFAULT ((0)),
[IntlPurchAmount] [money] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlPurchAmount] DEFAULT ((0)),
[IntlSubjectCat] [dbo].[udtSubjectPreference] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlSubjectCat] DEFAULT ('X'),
[IntlSubjectPref] [dbo].[udtSubjectPreference] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlSubjectPref] DEFAULT ('X'),
[FlagIntlSubjectPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagIntlSubjectPrefTied] DEFAULT ((0)),
[IntlFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlFormatMediaCat] DEFAULT ('X'),
[IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlFormatMediaPref] DEFAULT ('X'),
[FlagMediaPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagMediaPrefTied] DEFAULT ((0)),
[IntlFormatAVCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlFormatAVCat] DEFAULT ('X'),
[IntlFormatAVPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlFormatAVPref] DEFAULT ('X'),
[FlagFormatAVPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagFormatAVPrefTied] DEFAULT ((0)),
[IntlFormatADCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlFormatADCat] DEFAULT ('X'),
[IntlFormatADPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlFormatADPref] DEFAULT ('X'),
[FlagFormatADPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagFormatADPrefTied] DEFAULT ((0)),
[IntlPromotionTypeID] [smallint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlPromotionType] DEFAULT ((0)),
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlOrderSource] DEFAULT ('X'),
[FlagIntlBackOrder] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagIntlBackOrder] DEFAULT ((0)),
[FirstCouponRedmDate] [datetime] NULL,
[FirstReturnDate] [datetime] NULL,
[FirstEMResponseDate] [datetime] NULL,
[FlagFirstInquirer] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagFirstInquirer] DEFAULT ((0)),
[FirstInquirerDate] [datetime] NULL,
[FirstBackOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FirstBackOrderID] DEFAULT ((0)),
[FirstEMailAddress] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstRegion] [tinyint] NULL,
[FlagEmailable] [tinyint] NULL,
[FlagFirstEMailPref] [tinyint] NULL,
[FlagFirstMailPref] [tinyint] NULL,
[FlagMailable] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagMailable] DEFAULT ((1)),
[FirstBuyerType] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FirstBuyerType] DEFAULT ((0)),
[FlagMailableCollegeBuyer] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagMailableCollegeBuyer] DEFAULT ((0)),
[FlagIntlCouponRedm] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagIntlCouponRedm] DEFAULT ((0)),
[FirstCreateDate] [datetime] NULL,
[DMIntlCustomerType] [tinyint] NULL,
[SSCustomerType] [tinyint] NULL,
[RFMFlag] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_RFMFlag] DEFAULT ((0)),
[IntlAvgOrderBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlParts] [dbo].[udtCourseParts] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlParts] DEFAULT ((0)),
[IntlPartsBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlNumOfCOurses] [smallint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_IntlNumOfCOurses] DEFAULT ((0)),
[IntlCoursesBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOfHits] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReliabilityCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFlag] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagSP] DEFAULT ((0)),
[SPPromotionType] [smallint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPPromotionType] DEFAULT ((0)),
[SPOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPDate] [datetime] NULL,
[SPDateID] [int] NULL,
[SPAdcode] [int] NULL,
[SPFlagCoupon] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagSPCoupon] DEFAULT ((0)),
[SPFormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPFormatMedia] DEFAULT ('X'),
[SPSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPSubjectCat] DEFAULT ('X'),
[SPFormatAV] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPFormatAV] DEFAULT ('X'),
[SPFormatAD] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPFormatAD] DEFAULT ('X'),
[SPOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPOrderSource] DEFAULT ('X'),
[DSDays] [int] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_DSDays] DEFAULT ((0)),
[SPAmount] [money] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPAmount] DEFAULT ((0)),
[FlagIntlPurchTran] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagIntlPurchTran] DEFAULT ((0)),
[SPFlagTran] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_FlagSPTran] DEFAULT ((0)),
[SPFlag3Mth] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPFlag3Mth] DEFAULT ((0)),
[SPFlag6Mth] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPFlag6Mth] DEFAULT ((0)),
[SPFlag12Mth] [tinyint] NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPFlag12Mth] DEFAULT ((0)),
[SPSubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerReActivationStaticNew_SPSubjectPref] DEFAULT ('X'),
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialPurchaseSubjectPreference2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryPurchaseSubjectPreference2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagDRTV] [bit] NULL
) ON [PRIMARY]
GO
