CREATE TABLE [Staging].[TempDMCustomerStaticnew]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DMCustomerStaticNew_CustomerID] DEFAULT ((0)),
[OrganizationID] [int] NULL CONSTRAINT [DF_DMCustomerStaticNew_OrganizationID] DEFAULT ((0)),
[CustomerSinceDateID] [int] NULL CONSTRAINT [DF_DMCustomerStaticNew_CustomerSinceDateID] DEFAULT ((0)),
[CustomerSinceDate] [datetime] NOT NULL CONSTRAINT [DF_DMCustomerStaticNew_CustomerSinceDate] DEFAULT (((1)/(1))/(1900)),
[IntlPurchaseDateID] [int] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlPurchaseDateID] DEFAULT ((0)),
[IntlPurchaseDate] [datetime] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlPurchaseDate] DEFAULT ((0)),
[IntlPurchaseOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlPurchaseOrderID] DEFAULT ((0)),
[IntlPurchaseAdCode] [int] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlPurchaseAdCode] DEFAULT ((0)),
[IntlPurchAmount] [money] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlPurchAmount] DEFAULT ((0)),
[IntlSubjectCat] [dbo].[udtSubjectPreference] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlSubjectCat] DEFAULT ('X'),
[IntlSubjectPref] [dbo].[udtSubjectPreference] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlSubjectPref] DEFAULT ('X'),
[FlagIntlSubjectPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagIntlSubjectPrefTied] DEFAULT ((0)),
[IntlFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatMediaCat] DEFAULT ('X'),
[IntlFormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatMediaPref] DEFAULT ('X'),
[FlagMediaPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagMediaPrefTied] DEFAULT ((0)),
[IntlFormatAVCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatAVCat] DEFAULT ('X'),
[IntlFormatAVPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatAVPref] DEFAULT ('X'),
[FlagFormatAVPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagFormatAVPrefTied] DEFAULT ((0)),
[IntlFormatPDCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatPDCat] DEFAULT ('X'),
[IntlFormatPDPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatPDPref] DEFAULT ('X'),
[FlagFormatPDPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagFormatPDPrefTied] DEFAULT ((0)),
[IntlFormatADCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatADCat] DEFAULT ('X'),
[IntlFormatADPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlFormatADPref] DEFAULT ('X'),
[FlagFormatADPrefTied] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagFormatADPrefTied] DEFAULT ((0)),
[IntlPromotionTypeID] [smallint] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlPromotionType] DEFAULT ((0)),
[IntlOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlOrderSource] DEFAULT ('X'),
[FlagIntlBackOrder] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagIntlBackOrder] DEFAULT ((0)),
[FirstCouponRedmDate] [datetime] NULL,
[FirstReturnDate] [datetime] NULL,
[FirstEMResponseDate] [datetime] NULL,
[FlagFirstInquirer] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagFirstInquirer] DEFAULT ((0)),
[FirstInquirerDate] [datetime] NULL,
[FirstBackOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_FirstBackOrderID] DEFAULT ((0)),
[FirstEMailAddress] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstRegion] [tinyint] NULL,
[FlagEmailable] [tinyint] NULL,
[FlagFirstEMailPref] [tinyint] NULL,
[FlagFirstMailPref] [tinyint] NULL,
[FlagMailable] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagMailable] DEFAULT ((1)),
[FirstBuyerType] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FirstBuyerType] DEFAULT ((0)),
[FlagMailableCollegeBuyer] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagMailableCollegeBuyer] DEFAULT ((0)),
[FlagIntlCouponRedm] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagIntlCouponRedm] DEFAULT ((0)),
[FirstCreateDate] [datetime] NULL,
[DMIntlCustomerType] [tinyint] NULL,
[SSCustomerType] [tinyint] NULL,
[RFMFlag] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_RFMFlag] DEFAULT ((0)),
[IntlAvgOrderBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlParts] [dbo].[udtCourseParts] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlParts] DEFAULT ((0)),
[IntlPartsBin] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntlNumOfCOurses] [smallint] NULL CONSTRAINT [DF_DMCustomerStaticNew_IntlNumOfCOurses] DEFAULT ((0)),
[IntlCoursesBin] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumOfHits] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReliabilityCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPFlag] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagSP] DEFAULT ((0)),
[SPPromotionType] [smallint] NULL CONSTRAINT [DF_DMCustomerStaticNew_SPPromotionType] DEFAULT ((0)),
[SPOrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPDate] [datetime] NULL,
[SPDateID] [int] NULL,
[SPAdcode] [int] NULL,
[SPFlagCoupon] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagSPCoupon] DEFAULT ((0)),
[SPFormatMedia] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SPFormatMedia] DEFAULT ('X'),
[SPSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SPSubjectCat] DEFAULT ('X'),
[SPFormatAV] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SPFormatAV] DEFAULT ('X'),
[SPFormatAD] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SPFormatAD] DEFAULT ('X'),
[SPOrderSource] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SPOrderSource] DEFAULT ('X'),
[DSDays] [int] NULL CONSTRAINT [DF_DMCustomerStaticNew_DSDays] DEFAULT ((0)),
[SPAmount] [money] NULL CONSTRAINT [DF_DMCustomerStaticNew_SPAmount] DEFAULT ((0)),
[FlagIntlPurchTran] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagIntlPurchTran] DEFAULT ((0)),
[SPFlagTran] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagSPTran] DEFAULT ((0)),
[SPFlag3Mth] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_SPFlag3Mth] DEFAULT ((0)),
[SPFlag6Mth] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_SPFlag6Mth] DEFAULT ((0)),
[SPFlag12Mth] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_SPFlag12Mth] DEFAULT ((0)),
[SPSubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SPSubjectPref] DEFAULT ('X'),
[CountryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InitialPurchaseSubjectPreference2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_InitialPurchaseSubjectPreference2] DEFAULT ('X'),
[InitialPurchaseSubjectCategory2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_InitialPurchaseSubjectCategory2] DEFAULT ('X'),
[FlagInitialPurchaseSubjectPreference2Tied] [tinyint] NULL CONSTRAINT [DF_DMCustomerStaticNew_FlagInitialPurchaseSubjectPreference2Tied] DEFAULT ((0)),
[SecondaryPurchaseSubjectPreference2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SecondaryPurchaseSubjectPreference2] DEFAULT ('X'),
[SecondaryPurchaseSubjectCategory2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_DMCustomerStaticNew_SecondaryPurchaseSubjectCategory2] DEFAULT ('X'),
[FlagDRTV] [bit] NULL
) ON [PRIMARY]
GO
