CREATE TABLE [Staging].[Omni_ssis_Customer]
(
[Date] [datetime] NULL,
[AllVisits] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PageViews] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobileDeviceType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carts] [int] NULL,
[CartViews] [int] NULL,
[Checkouts] [int] NULL,
[CartAdditions] [int] NULL,
[InternalSearchPerformed] [int] NULL,
[CartRemovals] [int] NULL,
[InternalSearch] [int] NULL,
[ReadaReview] [int] NULL,
[AccountLogin] [int] NULL,
[PriorityCodeSubmits] [int] NULL,
[FacetClicks] [int] NULL,
[CreateWishlist] [int] NULL,
[AddtoWishlist] [int] NULL,
[CheckoutLogins] [int] NULL,
[BillingContinues] [int] NULL,
[ShippingAddrContinues] [int] NULL,
[ShippingMethodContinues] [int] NULL,
[PlaceOrderSubmits] [int] NULL,
[egiftaddtocart] [int] NULL,
[egiftopencart] [int] NULL,
[egiftcheckou] [int] NULL,
[egiftpurchase] [int] NULL,
[egiftredeemview] [int] NULL,
[egiftredeem] [int] NULL,
[SocialShareSubmits] [int] NULL,
[PDPGalleryClick] [int] NULL,
[PDPShouldIBuyButton] [int] NULL,
[PDPWhatWIllYouLearnButton] [int] NULL,
[PDPYourProfessorButton] [int] NULL,
[PDPWhatsIncludedClick] [int] NULL,
[OnSaleProductView] [int] NULL,
[UpsellRightArrowClick] [int] NULL,
[UpsellLeftArrowClick] [int] NULL,
[UniqueVisitors] [int] NULL
) ON [PRIMARY]
GO
