CREATE TABLE [Staging].[TGCPlusInfluencerMaster]
(
[Unique ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date] [datetime] NULL,
[Offer ID] [float] NULL,
[Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Code 1 (advertised URL)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Code 2 (short URL)] [float] NULL,
[Source Code 3 (TGC Redirect)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Start Week] [datetime] NULL,
[StartMonth] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartYear] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[On Screen Link] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Video Description Link] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Redirect/HTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description Link (Short URL) Redirects to] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheGreatCourses#com URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheGreatCourses#com Redirect HTML] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date URLs Set Up] [datetime] NULL,
[Date IO Signed] [datetime] NULL,
[Invoice #] [float] NULL,
[Date Invoice Passed to Accounting] [datetime] NULL,
[Spot Cost] [money] NULL,
[Sessions] [money] NULL,
[Registrations] [money] NULL,
[Signups] [money] NULL,
[Expected Views] [float] NULL,
[# Subs if RR is 0#024%] [float] NULL,
[#Subs if CPA is $80] [float] NULL,
[#Subs if CPA is $150] [float] NULL,
[Month for Budget] [float] NULL,
[F31] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F32] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F33] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F35] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F36] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F37] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F38] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F39] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
