CREATE TABLE [Staging].[SailThru_ssis_Subscriberlist]
(
[Profile_Id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Domain] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Engagement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lists] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Profile_Created_Date] [datetime] NULL,
[Signup] [datetime] NULL,
[Opens] [int] NULL,
[Clicks] [int] NULL,
[Pageviews] [int] NULL,
[Last_Open] [datetime] NULL,
[Last_Click] [datetime] NULL,
[Last_Pageview] [datetime] NULL,
[Optout_Time] [datetime] NULL,
[List_Signup] [datetime] NULL,
[Geolocation_City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Geolocation_State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Geolocation_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Geolocation_Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lifetime_Message] [int] NULL,
[First_Purchase_Time] [datetime] NULL,
[Purchase_Count] [int] NULL,
[Purchase_Price] [real] NULL,
[Purchase_Incomplete] [int] NULL,
[Last_Purchase_Time] [datetime] NULL,
[Largest_Purchase_Item_Price] [real] NULL,
[Top_Device] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[andoirdUser] [bit] NULL,
[people_following] [int] NULL,
[googletvUser] [bit] NULL,
[collections_created] [bit] NULL,
[location] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rokuUser] [bit] NULL,
[join_date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[samsungUser] [bit] NULL,
[films_queued] [int] NULL,
[lgUser] [bit] NULL,
[first_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[verified] [bit] NULL,
[gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postal_city] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[movies_watched] [int] NULL,
[weekly] [int] NULL,
[panasonicUser] [bit] NULL,
[windows8User] [bit] NULL,
[films_favorited] [int] NULL,
[xboxUser] [bit] NULL,
[last_login] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[display_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wdUser] [bit] NULL,
[source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[notifications] [bit] NULL,
[last_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postal_state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[iOSUser] [bit] NULL,
[subscribed_at_time] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
