CREATE TABLE [Staging].[TempNewCustomerWelcomeSeries]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponExpire] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adcode] [int] NULL,
[CouponCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseID1] [int] NULL,
[CourseID2] [int] NULL,
[CourseID3] [int] NULL,
[CourseID4] [int] NULL,
[CourseID5] [int] NULL,
[URLVariable] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VersionCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertalogAdcode] [int] NULL,
[FlagEmailable] [bit] NULL,
[CustomerSegmentNew] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagReceivedSpclShipCat] [int] NULL,
[URL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcquisitionWeek] [datetime] NULL,
[CustGroup] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HVLVGroup] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagOther] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
