CREATE TABLE [Staging].[YearlyCohortDynamicBase4]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagMailableCollegeBuyerSS] [tinyint] NOT NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDate] [date] NOT NULL,
[AsOfMonth] [tinyint] NOT NULL,
[AsOfYear] [smallint] NOT NULL,
[NewSeg] [tinyint] NOT NULL,
[Name] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[A12MF] [tinyint] NOT NULL,
[ActiveOrSwamp] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTDPurchasesBinID] [tinyint] NOT NULL,
[Frequency] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DSLPurchaseBinID] [tinyint] NOT NULL,
[LTDAvgOrderBinID] [tinyint] NOT NULL,
[LTDFormatMediaCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[R3FormatMediaPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTDFormatAVCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[R3FormatAVPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTDFormatADCat] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[R3FormatADPref] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTDSubjectCat] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[R3SubjectPref] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LTDOrderSource] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[R3OrderSource] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TenureDaysBinID] [tinyint] NOT NULL,
[LTDCouponsRedmBinID] [tinyint] NOT NULL,
[DSLCouponRedmBinID] [tinyint] NOT NULL,
[LTDReturnsBinID] [tinyint] NOT NULL,
[LTDEMResponses] [int] NOT NULL,
[LTDEMResponsesBinID] [tinyint] NOT NULL,
[DSLEMResponseBinID] [tinyint] NOT NULL,
[LTDNewCoursePurchBinID] [tinyint] NOT NULL,
[DSLNewCoursePurchBinID] [tinyint] NOT NULL,
[FlagEmailPref] [tinyint] NULL,
[FlagEmailValid] [tinyint] NULL,
[FlagEmailable] [tinyint] NULL,
[FlagMailPref] [tinyint] NULL,
[FlagValidUSMailable] [tinyint] NULL,
[FlagMailable] [tinyint] NULL,
[CountryCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R3PurchWeb] [tinyint] NULL,
[CustomerSegment2ID] [int] NULL,
[CustomerSegmentFnlID] [int] NULL,
[AgeBin] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EducationBin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseHoldIncomeBin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewSeg_EOY] [tinyint] NULL,
[Name_EOY] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[A12MF_EOY] [tinyint] NULL,
[ActiveOrSwamp_EOY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency_EOY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSegment2ID_EOY] [int] NULL,
[CustomerSegmentFnlID_EOY] [int] NULL,
[SalesSubsqYr] [money] NULL,
[OrdersSubsqYr] [int] NULL,
[UnitsSubsqYr] [int] NULL,
[PartsSubsqYr] [dbo].[udtCourseParts] NULL,
[EMSalesSubsqYr] [money] NULL,
[EMOrdersSubsqYr] [int] NOT NULL
) ON [PRIMARY]
GO
