CREATE TABLE [Staging].[WPMail]
(
[CustomerID] [dbo].[udtCustomerID] NOT NULL,
[CustomerName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponExpire] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adcode] [int] NULL,
[CouponCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseID1] [int] NULL,
[CourseID2] [int] NULL,
[CourseID3] [int] NULL,
[CourseID4] [int] NULL,
[CourseID5] [int] NULL,
[CourseID6] [int] NULL,
[CourseID7] [int] NULL,
[CourseID8] [int] NULL,
[CourseID9] [int] NULL,
[CourseID10] [int] NULL,
[CourseID11] [int] NULL,
[URLVariable] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VersionCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertalogAdcode] [int] NULL,
[FlagEmailable] [bit] NULL
) ON [PRIMARY]
GO
