CREATE TABLE [Staging].[TGC_Consumption_MonthlySmryTEMP]
(
[CustomerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDate] [date] NULL,
[AsOfYear] [int] NULL,
[AsOfMonth] [int] NULL,
[AsOfMnthYr] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalActions] [int] NOT NULL,
[StreamedMins] [numeric] (38, 2) NOT NULL,
[CoursesStreamed] [int] NOT NULL,
[LecturesStreamed] [int] NOT NULL,
[FlagStreamed] [int] NOT NULL,
[TotalActions_DVD] [int] NOT NULL,
[StreamedMins_DVD] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DVD] [int] NOT NULL,
[LecturesStreamed_DVD] [int] NOT NULL,
[FlagStreamed_DVD] [int] NOT NULL,
[TotalActions_CD] [int] NOT NULL,
[StreamedMins_CD] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_CD] [int] NOT NULL,
[LecturesStreamed_CD] [int] NOT NULL,
[FlagStreamed_CD] [int] NOT NULL,
[TotalActions_DownloadV] [int] NOT NULL,
[StreamedMins_DownloadV] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DownloadV] [int] NOT NULL,
[LecturesStreamed_DownloadV] [int] NOT NULL,
[FlagStreamed_DownloadV] [int] NOT NULL,
[TotalActions_DownloadA] [int] NOT NULL,
[StreamedMins_DownloadA] [numeric] (38, 2) NOT NULL,
[CoursesStreamed_DownloadA] [int] NOT NULL,
[LecturesStreamed_DownloadA] [int] NOT NULL,
[FlagStreamed_DownloadA] [int] NOT NULL,
[CoursesDnld] [int] NOT NULL,
[CoursesDnld_DownloadA] [int] NOT NULL,
[FlagDnld_DownloadA] [int] NOT NULL,
[CoursesDnld_DownloadV] [int] NOT NULL,
[FlagDnld_DownloadV] [int] NOT NULL,
[FlagDnld] [int] NOT NULL
) ON [PRIMARY]
GO
