CREATE TABLE [Staging].[Temp_WD_MonthlyFile]
(
[CustomerID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagRntlExchng] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FlagNeedDemoAppnd] [int] NOT NULL,
[LTDAvgOrd] [money] NULL,
[LastOrderDate] [datetime] NULL,
[SCI] [int] NULL,
[MTH] [int] NULL,
[MSC] [int] NULL,
[VA] [int] NULL,
[RL] [int] NULL,
[AH] [int] NULL,
[MH] [int] NULL,
[EC] [int] NULL,
[LIT] [int] NULL,
[BL] [int] NULL,
[PR] [int] NULL,
[HS] [int] NULL,
[PH] [int] NULL,
[IntlOrderChannel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsOfDate] [date] NULL,
[Source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FlagPhotography] [int] NOT NULL,
[FlagCooking] [int] NOT NULL,
[FlagSpirituality] [int] NOT NULL,
[FlagAstronomy] [int] NOT NULL,
[Flagchristianity] [int] NOT NULL,
[SCI_LOD] [datetime] NULL,
[MTH_LOD] [datetime] NULL,
[MSC_LOD] [datetime] NULL,
[VA_LOD] [datetime] NULL,
[RL_LOD] [datetime] NULL,
[AH_LOD] [datetime] NULL,
[MH_LOD] [datetime] NULL,
[EC_LOD] [datetime] NULL,
[LIT_LOD] [datetime] NULL,
[BL_LOD] [datetime] NULL,
[PR_LOD] [datetime] NULL,
[HS_LOD] [datetime] NULL,
[PH_LOD] [datetime] NULL,
[FlagPhotography_LOD] [datetime] NULL,
[FlagCooking_LOD] [datetime] NULL,
[FlagSpirituality_LOD] [datetime] NULL,
[FlagAstronomy_LOD] [datetime] NULL,
[Flagchristianity_LOD] [datetime] NULL
) ON [PRIMARY]
GO
