IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TEACHCO\RSQLINT')
CREATE LOGIN [TEACHCO\RSQLINT] FROM WINDOWS
GO
CREATE USER [TEACHCO\RSQLINT] FOR LOGIN [TEACHCO\RSQLINT]
GO
