IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TEACHCO\carrt')
CREATE LOGIN [TEACHCO\carrt] FROM WINDOWS
GO
CREATE USER [TEACHCO\carrt] FOR LOGIN [TEACHCO\carrt]
GO
GRANT EXECUTE TO [TEACHCO\carrt]
