SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PROC_AUXTRACKING]
AS
BEGIN
INSERT INTO SM_AUXTRACKING_LOG(DATESTAMP, TTYPE, COUNTVALUE, IPADDR, SNO, MAILINGID, DBID, MESSAGEID, USERID, EMAIL, LINKID, EXTRA, LINK, FORWARDEMAIL, FORWARDLEVEL)
SELECT TRDATE, TTYPE, COUNTVALUE, IPADDRESS, SERIALNUMBER, MAILINGID, DATABASEID, MESSAGEID, USERID, EMAILADDRESS , LINKID , EXTRA, LINK, FORWARDEMAIL, FORWARDLEVEL
FROM TEMP_AUXTRACKING;
END;


GO
GRANT EXECUTE ON  [dbo].[PROC_AUXTRACKING] TO [TEACHCO\OLTP_DATA Group]
GO
