SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PROC_SUCCESS]
AS
BEGIN
INSERT INTO SM_SUCCESS_LOG(DATESTAMP, SNO, MAILINGID, DBID, MESSAGEID, USERID, DBROWNUM, DBNAME, MSGSNO, EMAIL, VSGNAME, OUTBOUNDIP, MXIP)
SELECT SCDATE, SERIALNUMBER, MAILINGID, DATABASEID, MESSAGEID, USERID, DATABASEROWNUMBER, DATABASENAME, MESSAGESERIALNUMBER, EMAILADDRESS, VSGNAME, OUTBOUNDIP, MXIP
FROM TEMP_SUCCESS;
END;


GO
GRANT EXECUTE ON  [dbo].[PROC_SUCCESS] TO [TEACHCO\OLTP_DATA Group]
GO
