SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PROC_RETRYFAILED]
AS
BEGIN
INSERT INTO SM_RetryFailed_Log(Datestamp,SNo,MailingID, DBID, MessageID, UserID, DBRowNum, DBName, MsgSNo, Email,Bounce,VSGName,OutboundIP,MXIP,Category,Type,Code)
SELECT TRDATE, SNo,MAILINGID, DBID, MESSAGEID, USERID, DBROWNUM, DBNAME, MSGSNO, EMAIL,BOUNCE, VSGName, OUTBOUNDIP, MXIP, CATEGORY, TYPE, CODE 
FROM TEMP_RETRYFAILED;
END;

GO
GRANT EXECUTE ON  [dbo].[PROC_RETRYFAILED] TO [TEACHCO\OLTP_DATA Group]
GO
