SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PROC_TRACKING]
AS
BEGIN
INSERT INTO SM_TRACKING_LOG(DATESTAMP, TTYPE, COUNTVALUE, IPADDR, SNO, MAILINGID, DBID, MESSAGEID, USERID, EMAIL, LINKID, EXTRA, LINK, FORWARDEMAIL)
SELECT TRDATE, TTYPE, COUNTVALUE, IPADDRESS, SERIALNUMBER, MAILINGID, DATABASEID, MESSAGEID, USERID, EMAILADDRESS , LINKID , EXTRA, LINK, FORWARDEMAIL
FROM TEMP_TRACKING;
END;


GO
GRANT EXECUTE ON  [dbo].[PROC_TRACKING] TO [TEACHCO\OLTP_DATA Group]
GO
