SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PROC_DEFERSUCCESS]
AS
BEGIN
INSERT INTO SM_SUCCESS_LOG(DATESTAMP, SNO, MAILINGID, DBID, MESSAGEID, USERID, DBROWNUM, DBNAME, MSGSNO, EMAIL, VSGNAME, OUTBOUNDIP, MXIP)
SELECT DSDATE, SERIALNUMBER, MAILINGID, DATABASEID, MESSAGEID, USERID, DATABASEROWNUMBER, DATABASENAME, MESSAGESERIALNUMBER, EMAILADDRESS, VSGNAME, OUTBOUNDIP, MXIP
FROM TEMP_DEFERSUCCESS;
END;


GO
GRANT EXECUTE ON  [dbo].[PROC_DEFERSUCCESS] TO [TEACHCO\OLTP_DATA Group]
GO
