SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[PROC_AGGREGATE]
AS
BEGIN
INSERT INTO SM_AGGREGATE_LOG(LOGTYPE, LOGNAME, LOGDATE, SNO, MAILINGID, DBID, MESSAGEID, USERID, DBROWNUM, DBNAME, MSGSNO, EMAIL, BOUNCE, CATEGORY, BOUNCETYPE, CODE, VSGNAME, OUTBOUNDIP, MXIP)
SELECT LOGTYPE, LOGNAME, AGDATE, SERIALNUMBER, MAILINGID, DATABASEID, MESSAGEID, USERID, DATABASEROWNUMBER, DATABASENAME, MESSAGESERIALNUMBER, EMAILADDRESS, BOUNCEREASON, CATEGORY, BOUNCETYPE, CODE, VSGNAME, OUTBOUNDIP, MXIP
FROM TEMP_AGGREGATE;
END;


GO
GRANT EXECUTE ON  [dbo].[PROC_AGGREGATE] TO [TEACHCO\OLTP_DATA Group]
GO
