CREATE TABLE [Amazon].[Orders]
(
[Order_ID] [int] NOT NULL IDENTITY(1, 1),
[DateKey] [date] NULL,
[SenderID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionTime] [datetime] NULL,
[DocumentType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocumentID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amazon_order_id] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[merchant_order_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipment_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchase_date] [datetimeoffset] (2) NULL,
[payments_date] [datetimeoffset] (2) NULL,
[shipment_date] [datetimeoffset] (2) NULL,
[reporting_date] [datetimeoffset] (2) NULL,
[buyer_email] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyer_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyer_phone_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_recipient_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_address_3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_city] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_state] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_postal_code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_country] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_to_phone_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_address_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_address_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_address_3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_city] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_state] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_postal_code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_to_country] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carrier] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tracking_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[estimated_arrival_date] [datetimeoffset] (2) NULL,
[fulfillment_center_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fulfillment_channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_channel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delivery_start_date] [datetime] NULL,
[delivery_end_date] [datetime] NULL,
[delivery_time_zone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delivery_instructions] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amazon_order_item_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[merchant_order_item_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sku] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[product_name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quantity_shipped] [int] NULL,
[currency] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_price] [decimal] (10, 2) NULL,
[item_tax] [decimal] (10, 2) NULL,
[shipping_price] [decimal] (10, 2) NULL,
[shipping_tax] [decimal] (10, 2) NULL,
[ship_service_level] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_wrap_price] [decimal] (10, 2) NULL,
[gift_wrap_tax] [decimal] (10, 2) NULL,
[item_promotion_discount] [decimal] (10, 2) NULL,
[gift_wrap_type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_message_text] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_promotion_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ship_promotion_discount] [decimal] (10, 2) NULL,
[ship_promotion_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_header_record] [bit] NULL,
[Import_Timestamp] [datetime] NULL CONSTRAINT [DF__Orders__Import_T__1A14E395] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [Amazon].[Orders] ADD CONSTRAINT [PK__Orders__F1E4639B67C03510] PRIMARY KEY CLUSTERED  ([Order_ID]) ON [PRIMARY]
GO
GRANT SELECT ON  [Amazon].[Orders] TO [ebridge]
GO
GRANT INSERT ON  [Amazon].[Orders] TO [ebridge]
GO
