CREATE TABLE [CallCenter].[AgentMetrics]
(
[year] [int] NULL,
[half] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quarter] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[month] [int] NULL,
[Week_num] [int] NULL,
[Week_of] [date] NULL,
[Rep] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rep_ID] [int] NULL,
[Rep_ID4] [int] NULL,
[Sup] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DAX_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACD_Calls] [int] NULL,
[ACD] [time] NULL,
[ACW] [time] NULL,
[AHT] [time] NULL,
[AUX] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adherence] [decimal] (18, 2) NULL,
[AHT_AVG] [time] NULL,
[AHT_SDEV] [time] NULL,
[AHT_UCL] [time] NULL,
[AHT_LCL] [time] NULL,
[C2C_AVG] [decimal] (18, 2) NULL,
[C2C_SDEV] [decimal] (18, 2) NULL,
[C2C_UCL] [decimal] (18, 2) NULL,
[C2C_LCL] [decimal] (18, 2) NULL,
[Cross0Sell_Orders] [int] NULL,
[Total_Orders] [int] NULL,
[Conversion_%] [decimal] (22, 8) NULL,
[Cross0Sell_USD] [money] NULL,
[Cross0Sell_GBP] [money] NULL,
[Cross0Sell_AUD] [money] NULL,
[Cross0Sell_$] [money] NULL,
[URPO] [money] NULL,
[UPC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPOM] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URPO_AVG] [money] NULL,
[UPC_AVG] [money] NULL,
[UPOM_AVG] [money] NULL,
[Errors] [int] NULL,
[Week_of_Filter] [date] NULL,
[Torch_Team] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Avg_Non0Call_ACW] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUX_%] [decimal] (22, 8) NULL,
[ACW_%] [decimal] (22, 8) NULL,
[ACD_(sec)] [int] NULL,
[ACW_(sec)] [int] NULL,
[NC0ACW_(sec)] [int] NULL,
[AHT_(sec)] [int] NULL,
[Accuracy] [decimal] (22, 8) NULL,
[ACS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OFFICE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUX_0] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUX_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUX_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUX_RONA] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACW_%_avg] [decimal] (22, 8) NULL,
[ISP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Staffed_Time] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hours] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUX_total_sec] [int] NULL,
[AUX_0_sec] [int] NULL,
[AUX_1_sec] [int] NULL,
[AUX_3_sec] [int] NULL,
[AUX_RONA_sec] [int] NULL,
[Staffed_Time_sec] [int] NULL,
[AUX1s] [decimal] (22, 8) NULL,
[ACWs] [decimal] (22, 8) NULL,
[CC_%] [decimal] (22, 8) NULL,
[CC_#] [int] NULL,
[CC_score] [int] NULL,
[CC_max] [int] NULL,
[ACS_%] [decimal] (22, 8) NULL,
[ACS_#] [int] NULL,
[ACS_score] [int] NULL,
[ACS_max] [int] NULL,
[BSC_ACS] [int] NULL,
[BSC_ACC] [int] NULL,
[BSC_C2C] [int] NULL,
[BSC_ACW] [int] NULL,
[BSC_UPOM] [int] NULL,
[BSC_CC] [int] NULL,
[BSC_AHT] [int] NULL,
[BSC] [decimal] (22, 8) NULL,
[AHT_Rep] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMLastUpdated] [datetime] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UC_AgentMetrics] ON [CallCenter].[AgentMetrics] ([Week_of], [Rep_ID], [Rep]) ON [PRIMARY]
GO
