CREATE TABLE [SailThru].[Profile_Files]
(
[email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lists_signup name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lists_signup signup_time] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars andoirdUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars people_following] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars googletvUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars collections_created] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars location] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars rokuUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars join_date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars samsungUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars films_queued] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars lgUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars first_name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars verified] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars gender] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars postal_city] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars movies_watched] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars weekly] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars panasonicUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars windows8User] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars films_favorited] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars xboxUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars last_login] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars display_name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars wdUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars notifications] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars last_name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars postal_state] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars iOSUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars last_login_time] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars join_time] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars subscribed_at_time] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars payer_name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars offer_id] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars subscription_plan_name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars offer_start_date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars offer_description] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars paymentHandler] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars subscription_plan_id] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars_First_Name_1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars appletvUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars windows10User] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars amazonUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars app_last_login_time] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars registered_via_platform] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars androidUser] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars uuid] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vars subscribed_via_platform] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[signup_time] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lists_remove null] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lists_remove TGC SignUps] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_opens] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_clicks] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_unique_opens] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_unique_clicks] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_pageviews] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_messages] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_open] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_click] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_pageview] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Import_Datetime] [datetime] NULL,
[Import_Filename] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
