CREATE TABLE [staging].[CY_SpaceMaster]
(
[SrNum] [float] NULL,
[PlanYear] [float] NULL,
[PlanMonth] [float] NULL,
[AdProgressStageID] [float] NULL,
[AdProgressStage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Publication] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DomesticOrInternational] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [float] NULL,
[PubType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost] [float] NULL,
[DesignStyle] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostForReporting] [float] NULL,
[CPM] [float] NULL,
[CourseID] [float] NULL,
[CourseName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parts] [float] NULL,
[CourseReleaseYear] [float] NULL,
[S&H] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriberSaleDate] [datetime] NULL,
[PubOnSaleDate] [datetime] NULL,
[Reservations] [float] NULL,
[ArtDue] [datetime] NULL,
[ExpireDate] [datetime] NULL,
[Cover/IssueDate] [datetime] NULL,
[BuffetFlag] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CatalogCode_Control] [float] NULL,
[CatalogCode_Test] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdCode_Control] [float] NULL,
[AdCode_Test] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URLAdCode_Control] [float] NULL,
[URLAdCode_Test] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TestURL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Placement] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditorialFeatures] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceReceived] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceNumber] [float] NULL,
[Subject] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdCode_ControlSales] [float] NULL,
[AdCode_TestSales] [float] NULL,
[URLAdCode_ControlSales] [float] NULL,
[URLAdCode_TestSales] [float] NULL,
[ControlSales] [float] NULL,
[TestSales] [float] NULL,
[AdCode_ControlOrders] [float] NULL,
[AdCode_TestOrders] [float] NULL,
[URLAdCode_ControlOrders] [float] NULL,
[URLAdCode_TestOrders] [float] NULL,
[ControlOrders] [float] NULL,
[TestOrders] [float] NULL,
[QuarterAdExpires] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysSinceSaleDate] [int] NULL,
[PubAllowable] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flag40%Comp] [float] NULL,
[%Comp] [float] NULL,
[AOS] [float] NULL,
[ActualSales] [float] NULL,
[ActualOrders] [float] NULL,
[ActualProfits] [float] NULL,
[ForecastSales] [float] NULL,
[ForecastOrders] [float] NULL,
[ForecastProfits] [float] NULL,
[BudgetSales] [float] NULL,
[BudgetOrders] [float] NULL,
[BudgetProfits] [float] NULL,
[Current/ActualSales] [float] NULL,
[Current/ActualOrders] [float] NULL,
[Current/ActualProfit] [float] NULL,
[PriorYear_AvgRev] [float] NULL,
[blank_3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PUBID] [float] NULL,
[Circulation] [float] NULL,
[TestFlag] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TestID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TestName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TestDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cut] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactPhone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contactemail] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [float] NULL,
[Trim(W)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trim(H)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrimType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositionRequested] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionInstructions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionInstructions2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherNotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateforFinance] [date] NULL,
[IOReservationNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DesignerArtDueDate] [date] NULL,
[CourseGo-LiveDate(=artavailabledate)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTROL-ORDERSAdCodeNewCustomer] [float] NULL,
[CONTROL-ORDERSAdCodeExistingCustomer] [float] NULL,
[CONTROL-ORDERSURL_AdCodeNewCustomer] [float] NULL,
[CONTROL-ORDERSURL_AdCodeExistingCustomer] [float] NULL,
[CONTROL-SALESAdCodeNewCustomer] [float] NULL,
[CONTROL-SALESAdCodeExistingCustomer] [float] NULL,
[CONTROL-SALESURL_AdCodeNewCustomer] [float] NULL,
[CONTROL-SALESURL_AdCodeExistingCustomer] [float] NULL,
[CONTROLOrdersNewCustomer] [float] NULL,
[CONTROLOrdersExistingCustomer] [float] NULL,
[CONTROLTotalOrders] [float] NULL,
[T/FCHECKTotalOrders=ActRevPivotAdjOrder] [bit] NULL,
[blank12] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTROLSalesNewCustomer] [float] NULL,
[CONTROLSalesExistingCustomer] [float] NULL,
[CONTROLTotalSales] [float] NULL,
[T/FCHECKTotalSales=ActRevPivotAdjSales] [bit] NULL,
[blank13] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTROL%NewCustomerOrders] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTROL%NewCustomerSales] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[blank14] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[blank15] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEST-ORDERSAdCodeNewCustomer] [float] NULL,
[TEST-ORDERSAdCodeExistingCustomer] [float] NULL,
[TEST-ORDERSURL_AdCodeNewCustomer] [float] NULL,
[TEST-ORDERSURL_AdCodeExistingCustomer] [float] NULL,
[TEST-SALESAdCodeNewCustomer] [float] NULL,
[TEST-SALESAdCodeExistingCustomer] [float] NULL,
[TEST-SALESURL_AdCodeNewCustomer] [float] NULL,
[TEST-SALESURL_AdCodeExistingCustomer] [float] NULL,
[TESTOrdersNewCustomer] [float] NULL,
[TESTOrdersExistingCustomer] [float] NULL,
[TESTTotalOrders] [float] NULL,
[T/FCHECKTotalOrders=ActRevPivotAdjOrder1] [bit] NULL,
[blank16] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TESTSalesNewCustomer] [float] NULL,
[TESTSalesExistingCustomer] [float] NULL,
[TESTTotalSales] [float] NULL,
[T/FCHECKTotalSales=ActRevPivotAdjSales1] [bit] NULL,
[blank17] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEST%NewCustomerOrders] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEST%NewCustomerSales] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalOrders(Control+Test)] [float] NULL,
[TotalSales(Control+Test)] [float] NULL,
[T/FCHECKTotalOrders=TotalOrders] [bit] NULL,
[T/FCHECKTotalSales=TotalSales] [bit] NULL,
[TotalNewCustomerOrders(Control+Test)] [float] NULL,
[TotalNewCustomerSales(Control+Test)] [float] NULL,
[blank18] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[%NewCustomerOrders(Control+Test)] [float] NULL,
[%NewCustomerSales(Control+Test)] [float] NULL,
[blank19] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Issuerundays(withexptail)] [float] NULL,
[Monthdue(YEAR)] [float] NULL,
[MonthDue(TEXT)] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMLastUpdated] [datetime] NULL CONSTRAINT [DF__CY_SpaceM__DMLas__2057CCD0] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
