CREATE TABLE [staging].[CY_Publications]
(
[MDCampaignID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Publication] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[International/Domestic] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Standard/1pBuffet] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrimStyle] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrimW] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrimH] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Frequency] [float] NULL,
[FreqText] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Circ] [float] NULL,
[2018Cost(USD$)] [money] NULL,
[CPM] [money] NULL,
[URL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PubType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2018Contribution%] [float] NULL,
[2018Avg_AOSFORECAST] [money] NULL,
[2018#Ads] [money] NULL,
[2018TotalOrdersFORECAST] [float] NULL,
[2018ProjTotalSales] [money] NULL,
[2018ProjTotalCosts] [money] NULL,
[2018AvgProjRev/Ad] [money] NULL,
[2018ProjProf/Order] [money] NULL,
[2017Avg_AOSACTUAL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2017#AdsRan] [float] NULL,
[2017TotalOrdersACTUAL] [float] NULL,
[2017AvgOrdersPerAdACTUAL] [float] NULL,
[2017AvgRev/AdACTUAL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[%NewCustomers] [float] NULL,
[ContactName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactPhone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contactemail] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [float] NULL,
[PositionRequested] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionInstructions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionInstructions2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherNotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PubIDs] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DAXCampaignTypeID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionInstructionsUpdated(ColAK/AL)] [datetime] NULL,
[PubIDconfirmed] [datetime] NULL,
[CampaignIDconfirmed] [datetime] NULL,
[Trimsizebothtabs-confirmed] [datetime] NULL,
[DMLastUpdated] [datetime] NULL CONSTRAINT [DF__CY_Public__DMLas__1C873BEC] DEFAULT (getdate())
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
