IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TEACHCO\SQLLink')
CREATE LOGIN [TEACHCO\SQLLink] FROM WINDOWS
GO
CREATE USER [TEACHCO\SQLLink] FOR LOGIN [TEACHCO\SQLLink]
GO
