CREATE TABLE [dbo].[DAX_TTCMKTSPLITTESTS]
(
[SPLITNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__33D4B598] DEFAULT (''),
[STARTDATE] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__START__34C8D9D1] DEFAULT ('1900-01-01 00:00:00.000'),
[ENDDATESCHEDULED] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__ENDDA__35BCFE0A] DEFAULT ('1900-01-01 00:00:00.000'),
[ENDDATEACTUAL] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__ENDDA__36B12243] DEFAULT ('1900-01-01 00:00:00.000'),
[MAXASSIGNMENTS] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__MAXAS__37A5467C] DEFAULT ((0)),
[ACTIVE] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__ACTIV__38996AB5] DEFAULT ((0)),
[MODIFIEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__398D8EEE] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[MODIFIEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__3A81B327] DEFAULT ('?'),
[CREATEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__3B75D760] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[CREATEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__3C69FB99] DEFAULT ('?'),
[RECVERSION] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__RECVE__3D5E1FD2] DEFAULT ((1)),
[RECID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DAX_TTCMKTSPLITTESTS] ADD CONSTRAINT [CK__DAX_TTCMK__RECID__3E52440B] CHECK (([RECID]<>(0)))
GO
CREATE UNIQUE CLUSTERED INDEX [I_40131SPLITNAMEIDX] ON [dbo].[DAX_TTCMKTSPLITTESTS] ([SPLITNAME], [RECID]) ON [PRIMARY]
GO
