CREATE TABLE [dbo].[JSCUSTCREDITREASONCODES]
(
[REASONCODE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTION] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MODIFIEDDATETIME] [datetime] NOT NULL,
[DEL_MODIFIEDTIME] [int] NOT NULL,
[MODIFIEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MODIFIEDTRANSACTIONID] [bigint] NOT NULL,
[CREATEDDATETIME] [datetime] NOT NULL,
[DEL_CREATEDTIME] [int] NOT NULL,
[CREATEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATEDTRANSACTIONID] [bigint] NOT NULL,
[DATAAREAID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RECVERSION] [int] NOT NULL,
[RECID] [bigint] NOT NULL
) ON [PRIMARY]
GO
