CREATE TABLE [dbo].[DAX_TTCMKTSPLITTESTSCENARIOS]
(
[SPLITNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__403A8C7D] DEFAULT (''),
[SPLITNUMBER] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__412EB0B6] DEFAULT ((0)),
[NUMBERASSIGNED] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__NUMBE__4222D4EF] DEFAULT ((0)),
[PERCENTORRATIO] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__PERCE__4316F928] DEFAULT ((0)),
[SPLITNUMBERDESCRIPTION] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__440B1D61] DEFAULT (''),
[MODIFIEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__44FF419A] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[MODIFIEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__45F365D3] DEFAULT ('?'),
[CREATEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__46E78A0C] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[CREATEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__47DBAE45] DEFAULT ('?'),
[RECVERSION] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__RECVE__48CFD27E] DEFAULT ((1)),
[RECID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DAX_TTCMKTSPLITTESTSCENARIOS] ADD CONSTRAINT [CK__DAX_TTCMK__RECID__49C3F6B7] CHECK (([RECID]<>(0)))
GO
CREATE UNIQUE NONCLUSTERED INDEX [I_40132IDX_SCENARIONAME] ON [dbo].[DAX_TTCMKTSPLITTESTSCENARIOS] ([SPLITNAME], [SPLITNUMBER], [RECID]) ON [PRIMARY]
GO
