CREATE TABLE [staging].[Load_InvItem_ToDatamart]
(
[UserStockItemID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CourseID] [int] NOT NULL,
[Packaging] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MediaTypeID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FormatID] [int] NULL,
[PartNumber] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullDescription] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemCategoryID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonStockItem] [tinyint] NOT NULL,
[ForSalebyCC] [tinyint] NULL,
[ForSaleonWeb] [tinyint] NULL,
[ForSaleToLibrary] [tinyint] NULL,
[ForSaleToConsumer] [tinyint] NULL,
[CouponCode] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinPurchase] [decimal] (19, 2) NULL,
[ClearanceStatus] [tinyint] NULL,
[ISBN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Taxable] [tinyint] NULL,
[Length] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boxes] [int] NULL,
[Units] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnOrderQty] [int] NULL,
[OnBackOrderQty] [int] NULL,
[OnOrderTotalQty] [int] NULL,
[OnBackOrderTotalQty] [int] NULL,
[GuideBookLength] [int] NULL,
[InvStatusID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalOnHandQty] [int] NULL,
[TotalBuildableQty] [int] NULL,
[OKToShipalone] [tinyint] NULL,
[KanbanTypeID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Components] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Assembly] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fabrication] [int] NULL,
[MediaQty] [int] NULL,
[VideoDubbing] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tape1Length] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tape2Length] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tape3Length] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Loaders] [int] NULL,
[CassettesinPart] [int] NULL,
[InvoiceSectionID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pieces] [int] NULL,
[CubeSize] [float] NULL,
[Weight] [float] NULL,
[IncludeInPickCount] [tinyint] NULL,
[DownloadFName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DownloadFSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataFormat] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
