CREATE TABLE [staging].[DAX_TTCMKTSPLITTESTSCENARIOS]
(
[SPLITNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__2B0A656D] DEFAULT (''),
[SPLITNUMBER] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__2BFE89A6] DEFAULT ((0)),
[NUMBERASSIGNED] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__NUMBE__2CF2ADDF] DEFAULT ((0)),
[PERCENTORRATIO] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__PERCE__2DE6D218] DEFAULT ((0)),
[SPLITNUMBERDESCRIPTION] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__2EDAF651] DEFAULT (''),
[MODIFIEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__2FCF1A8A] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[MODIFIEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__30C33EC3] DEFAULT ('?'),
[CREATEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__31B762FC] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[CREATEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__32AB8735] DEFAULT ('?'),
[RECVERSION] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__RECVE__339FAB6E] DEFAULT ((1)),
[RECID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [staging].[DAX_TTCMKTSPLITTESTSCENARIOS] ADD CONSTRAINT [CK__DAX_TTCMK__RECID__2A164134] CHECK (([RECID]<>(0)))
GO
