CREATE TABLE [staging].[DAX_TTCMKTSPLITTESTS]
(
[SPLITNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__SPLIT__367C1819] DEFAULT (''),
[STARTDATE] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__START__37703C52] DEFAULT ('1900-01-01 00:00:00.000'),
[ENDDATESCHEDULED] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__ENDDA__3864608B] DEFAULT ('1900-01-01 00:00:00.000'),
[ENDDATEACTUAL] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__ENDDA__395884C4] DEFAULT ('1900-01-01 00:00:00.000'),
[MAXASSIGNMENTS] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__MAXAS__3A4CA8FD] DEFAULT ((0)),
[ACTIVE] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__ACTIV__3B40CD36] DEFAULT ((0)),
[MODIFIEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__3C34F16F] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[MODIFIEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__MODIF__3D2915A8] DEFAULT ('?'),
[CREATEDDATETIME] [datetime] NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__3E1D39E1] DEFAULT (dateadd(millisecond,-datepart(millisecond,getutcdate()),getutcdate())),
[CREATEDBY] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DAX_TTCMK__CREAT__3F115E1A] DEFAULT ('?'),
[RECVERSION] [int] NOT NULL CONSTRAINT [DF__DAX_TTCMK__RECVE__40058253] DEFAULT ((1)),
[RECID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [staging].[DAX_TTCMKTSPLITTESTS] ADD CONSTRAINT [CK__DAX_TTCMK__RECID__3587F3E0] CHECK (([RECID]<>(0)))
GO
